/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetSocialBilibiliUserinfo200ResponseData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSocialBilibiliUserinfo200ResponseData{}

// GetSocialBilibiliUserinfo200ResponseData struct for GetSocialBilibiliUserinfo200ResponseData
type GetSocialBilibiliUserinfo200ResponseData struct {
	Face *string `json:"face,omitempty"`
	Level *int32 `json:"level,omitempty"`
	Mid *int32 `json:"mid,omitempty"`
	Name *string `json:"name,omitempty"`
	Sex *string `json:"sex,omitempty"`
	Sign *string `json:"sign,omitempty"`
}

// NewGetSocialBilibiliUserinfo200ResponseData instantiates a new GetSocialBilibiliUserinfo200ResponseData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSocialBilibiliUserinfo200ResponseData() *GetSocialBilibiliUserinfo200ResponseData {
	this := GetSocialBilibiliUserinfo200ResponseData{}
	return &this
}

// NewGetSocialBilibiliUserinfo200ResponseDataWithDefaults instantiates a new GetSocialBilibiliUserinfo200ResponseData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSocialBilibiliUserinfo200ResponseDataWithDefaults() *GetSocialBilibiliUserinfo200ResponseData {
	this := GetSocialBilibiliUserinfo200ResponseData{}
	return &this
}

// GetFace returns the Face field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetFace() string {
	if o == nil || IsNil(o.Face) {
		var ret string
		return ret
	}
	return *o.Face
}

// GetFaceOk returns a tuple with the Face field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetFaceOk() (*string, bool) {
	if o == nil || IsNil(o.Face) {
		return nil, false
	}
	return o.Face, true
}

// HasFace returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) HasFace() bool {
	if o != nil && !IsNil(o.Face) {
		return true
	}

	return false
}

// SetFace gets a reference to the given string and assigns it to the Face field.
func (o *GetSocialBilibiliUserinfo200ResponseData) SetFace(v string) {
	o.Face = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *GetSocialBilibiliUserinfo200ResponseData) SetLevel(v int32) {
	o.Level = &v
}

// GetMid returns the Mid field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetMid() int32 {
	if o == nil || IsNil(o.Mid) {
		var ret int32
		return ret
	}
	return *o.Mid
}

// GetMidOk returns a tuple with the Mid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetMidOk() (*int32, bool) {
	if o == nil || IsNil(o.Mid) {
		return nil, false
	}
	return o.Mid, true
}

// HasMid returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) HasMid() bool {
	if o != nil && !IsNil(o.Mid) {
		return true
	}

	return false
}

// SetMid gets a reference to the given int32 and assigns it to the Mid field.
func (o *GetSocialBilibiliUserinfo200ResponseData) SetMid(v int32) {
	o.Mid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetSocialBilibiliUserinfo200ResponseData) SetName(v string) {
	o.Name = &v
}

// GetSex returns the Sex field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetSex() string {
	if o == nil || IsNil(o.Sex) {
		var ret string
		return ret
	}
	return *o.Sex
}

// GetSexOk returns a tuple with the Sex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetSexOk() (*string, bool) {
	if o == nil || IsNil(o.Sex) {
		return nil, false
	}
	return o.Sex, true
}

// HasSex returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) HasSex() bool {
	if o != nil && !IsNil(o.Sex) {
		return true
	}

	return false
}

// SetSex gets a reference to the given string and assigns it to the Sex field.
func (o *GetSocialBilibiliUserinfo200ResponseData) SetSex(v string) {
	o.Sex = &v
}

// GetSign returns the Sign field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetSign() string {
	if o == nil || IsNil(o.Sign) {
		var ret string
		return ret
	}
	return *o.Sign
}

// GetSignOk returns a tuple with the Sign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) GetSignOk() (*string, bool) {
	if o == nil || IsNil(o.Sign) {
		return nil, false
	}
	return o.Sign, true
}

// HasSign returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200ResponseData) HasSign() bool {
	if o != nil && !IsNil(o.Sign) {
		return true
	}

	return false
}

// SetSign gets a reference to the given string and assigns it to the Sign field.
func (o *GetSocialBilibiliUserinfo200ResponseData) SetSign(v string) {
	o.Sign = &v
}

func (o GetSocialBilibiliUserinfo200ResponseData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSocialBilibiliUserinfo200ResponseData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Face) {
		toSerialize["face"] = o.Face
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Mid) {
		toSerialize["mid"] = o.Mid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Sex) {
		toSerialize["sex"] = o.Sex
	}
	if !IsNil(o.Sign) {
		toSerialize["sign"] = o.Sign
	}
	return toSerialize, nil
}

type NullableGetSocialBilibiliUserinfo200ResponseData struct {
	value *GetSocialBilibiliUserinfo200ResponseData
	isSet bool
}

func (v NullableGetSocialBilibiliUserinfo200ResponseData) Get() *GetSocialBilibiliUserinfo200ResponseData {
	return v.value
}

func (v *NullableGetSocialBilibiliUserinfo200ResponseData) Set(val *GetSocialBilibiliUserinfo200ResponseData) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSocialBilibiliUserinfo200ResponseData) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSocialBilibiliUserinfo200ResponseData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSocialBilibiliUserinfo200ResponseData(val *GetSocialBilibiliUserinfo200ResponseData) *NullableGetSocialBilibiliUserinfo200ResponseData {
	return &NullableGetSocialBilibiliUserinfo200ResponseData{value: val, isSet: true}
}

func (v NullableGetSocialBilibiliUserinfo200ResponseData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSocialBilibiliUserinfo200ResponseData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


