/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetHistoryProgrammer200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetHistoryProgrammer200Response{}

// GetHistoryProgrammer200Response struct for GetHistoryProgrammer200Response
type GetHistoryProgrammer200Response struct {
	Message *string `json:"message,omitempty"`
	Date *string `json:"date,omitempty"`
	Events []GetHistoryProgrammer200ResponseEventsInner `json:"events,omitempty"`
}

// NewGetHistoryProgrammer200Response instantiates a new GetHistoryProgrammer200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetHistoryProgrammer200Response() *GetHistoryProgrammer200Response {
	this := GetHistoryProgrammer200Response{}
	return &this
}

// NewGetHistoryProgrammer200ResponseWithDefaults instantiates a new GetHistoryProgrammer200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetHistoryProgrammer200ResponseWithDefaults() *GetHistoryProgrammer200Response {
	this := GetHistoryProgrammer200Response{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetHistoryProgrammer200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHistoryProgrammer200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetHistoryProgrammer200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetHistoryProgrammer200Response) SetMessage(v string) {
	o.Message = &v
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *GetHistoryProgrammer200Response) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHistoryProgrammer200Response) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *GetHistoryProgrammer200Response) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *GetHistoryProgrammer200Response) SetDate(v string) {
	o.Date = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *GetHistoryProgrammer200Response) GetEvents() []GetHistoryProgrammer200ResponseEventsInner {
	if o == nil || IsNil(o.Events) {
		var ret []GetHistoryProgrammer200ResponseEventsInner
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetHistoryProgrammer200Response) GetEventsOk() ([]GetHistoryProgrammer200ResponseEventsInner, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *GetHistoryProgrammer200Response) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []GetHistoryProgrammer200ResponseEventsInner and assigns it to the Events field.
func (o *GetHistoryProgrammer200Response) SetEvents(v []GetHistoryProgrammer200ResponseEventsInner) {
	o.Events = v
}

func (o GetHistoryProgrammer200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetHistoryProgrammer200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	return toSerialize, nil
}

type NullableGetHistoryProgrammer200Response struct {
	value *GetHistoryProgrammer200Response
	isSet bool
}

func (v NullableGetHistoryProgrammer200Response) Get() *GetHistoryProgrammer200Response {
	return v.value
}

func (v *NullableGetHistoryProgrammer200Response) Set(val *GetHistoryProgrammer200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetHistoryProgrammer200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetHistoryProgrammer200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetHistoryProgrammer200Response(val *GetHistoryProgrammer200Response) *NullableGetHistoryProgrammer200Response {
	return &NullableGetHistoryProgrammer200Response{value: val, isSet: true}
}

func (v NullableGetHistoryProgrammer200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetHistoryProgrammer200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


