/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetStatusUsage404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetStatusUsage404Response{}

// GetStatusUsage404Response struct for GetStatusUsage404Response
type GetStatusUsage404Response struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGetStatusUsage404Response instantiates a new GetStatusUsage404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetStatusUsage404Response() *GetStatusUsage404Response {
	this := GetStatusUsage404Response{}
	return &this
}

// NewGetStatusUsage404ResponseWithDefaults instantiates a new GetStatusUsage404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetStatusUsage404ResponseWithDefaults() *GetStatusUsage404Response {
	this := GetStatusUsage404Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetStatusUsage404Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatusUsage404Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetStatusUsage404Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetStatusUsage404Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetStatusUsage404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetStatusUsage404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetStatusUsage404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetStatusUsage404Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetStatusUsage404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetStatusUsage404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetStatusUsage404Response struct {
	value *GetStatusUsage404Response
	isSet bool
}

func (v NullableGetStatusUsage404Response) Get() *GetStatusUsage404Response {
	return v.value
}

func (v *NullableGetStatusUsage404Response) Set(val *GetStatusUsage404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetStatusUsage404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetStatusUsage404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetStatusUsage404Response(val *GetStatusUsage404Response) *NullableGetStatusUsage404Response {
	return &NullableGetStatusUsage404Response{value: val, isSet: true}
}

func (v NullableGetStatusUsage404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetStatusUsage404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


