/*
UAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostTextMarkdownToHtml400Response - struct for PostTextMarkdownToHtml400Response
type PostTextMarkdownToHtml400Response struct {
	Markdown *Markdown
	PostTextMarkdownToHtml400ResponseOneOf *PostTextMarkdownToHtml400ResponseOneOf
	PostTextMarkdownToHtml400ResponseOneOf1 *PostTextMarkdownToHtml400ResponseOneOf1
}

// MarkdownAsPostTextMarkdownToHtml400Response is a convenience function that returns Markdown wrapped in PostTextMarkdownToHtml400Response
func MarkdownAsPostTextMarkdownToHtml400Response(v *Markdown) PostTextMarkdownToHtml400Response {
	return PostTextMarkdownToHtml400Response{
		Markdown: v,
	}
}

// PostTextMarkdownToHtml400ResponseOneOfAsPostTextMarkdownToHtml400Response is a convenience function that returns PostTextMarkdownToHtml400ResponseOneOf wrapped in PostTextMarkdownToHtml400Response
func PostTextMarkdownToHtml400ResponseOneOfAsPostTextMarkdownToHtml400Response(v *PostTextMarkdownToHtml400ResponseOneOf) PostTextMarkdownToHtml400Response {
	return PostTextMarkdownToHtml400Response{
		PostTextMarkdownToHtml400ResponseOneOf: v,
	}
}

// PostTextMarkdownToHtml400ResponseOneOf1AsPostTextMarkdownToHtml400Response is a convenience function that returns PostTextMarkdownToHtml400ResponseOneOf1 wrapped in PostTextMarkdownToHtml400Response
func PostTextMarkdownToHtml400ResponseOneOf1AsPostTextMarkdownToHtml400Response(v *PostTextMarkdownToHtml400ResponseOneOf1) PostTextMarkdownToHtml400Response {
	return PostTextMarkdownToHtml400Response{
		PostTextMarkdownToHtml400ResponseOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostTextMarkdownToHtml400Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Markdown
	err = newStrictDecoder(data).Decode(&dst.Markdown)
	if err == nil {
		jsonMarkdown, _ := json.Marshal(dst.Markdown)
		if string(jsonMarkdown) == "{}" { // empty struct
			dst.Markdown = nil
		} else {
			if err = validator.Validate(dst.Markdown); err != nil {
				dst.Markdown = nil
			} else {
				match++
			}
		}
	} else {
		dst.Markdown = nil
	}

	// try to unmarshal data into PostTextMarkdownToHtml400ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToHtml400ResponseOneOf)
	if err == nil {
		jsonPostTextMarkdownToHtml400ResponseOneOf, _ := json.Marshal(dst.PostTextMarkdownToHtml400ResponseOneOf)
		if string(jsonPostTextMarkdownToHtml400ResponseOneOf) == "{}" { // empty struct
			dst.PostTextMarkdownToHtml400ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToHtml400ResponseOneOf); err != nil {
				dst.PostTextMarkdownToHtml400ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToHtml400ResponseOneOf = nil
	}

	// try to unmarshal data into PostTextMarkdownToHtml400ResponseOneOf1
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToHtml400ResponseOneOf1)
	if err == nil {
		jsonPostTextMarkdownToHtml400ResponseOneOf1, _ := json.Marshal(dst.PostTextMarkdownToHtml400ResponseOneOf1)
		if string(jsonPostTextMarkdownToHtml400ResponseOneOf1) == "{}" { // empty struct
			dst.PostTextMarkdownToHtml400ResponseOneOf1 = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToHtml400ResponseOneOf1); err != nil {
				dst.PostTextMarkdownToHtml400ResponseOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToHtml400ResponseOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Markdown = nil
		dst.PostTextMarkdownToHtml400ResponseOneOf = nil
		dst.PostTextMarkdownToHtml400ResponseOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostTextMarkdownToHtml400Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostTextMarkdownToHtml400Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostTextMarkdownToHtml400Response) MarshalJSON() ([]byte, error) {
	if src.Markdown != nil {
		return json.Marshal(&src.Markdown)
	}

	if src.PostTextMarkdownToHtml400ResponseOneOf != nil {
		return json.Marshal(&src.PostTextMarkdownToHtml400ResponseOneOf)
	}

	if src.PostTextMarkdownToHtml400ResponseOneOf1 != nil {
		return json.Marshal(&src.PostTextMarkdownToHtml400ResponseOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostTextMarkdownToHtml400Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Markdown != nil {
		return obj.Markdown
	}

	if obj.PostTextMarkdownToHtml400ResponseOneOf != nil {
		return obj.PostTextMarkdownToHtml400ResponseOneOf
	}

	if obj.PostTextMarkdownToHtml400ResponseOneOf1 != nil {
		return obj.PostTextMarkdownToHtml400ResponseOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PostTextMarkdownToHtml400Response) GetActualInstanceValue() (interface{}) {
	if obj.Markdown != nil {
		return *obj.Markdown
	}

	if obj.PostTextMarkdownToHtml400ResponseOneOf != nil {
		return *obj.PostTextMarkdownToHtml400ResponseOneOf
	}

	if obj.PostTextMarkdownToHtml400ResponseOneOf1 != nil {
		return *obj.PostTextMarkdownToHtml400ResponseOneOf1
	}

	// all schemas are nil
	return nil
}

type NullablePostTextMarkdownToHtml400Response struct {
	value *PostTextMarkdownToHtml400Response
	isSet bool
}

func (v NullablePostTextMarkdownToHtml400Response) Get() *PostTextMarkdownToHtml400Response {
	return v.value
}

func (v *NullablePostTextMarkdownToHtml400Response) Set(val *PostTextMarkdownToHtml400Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextMarkdownToHtml400Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextMarkdownToHtml400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextMarkdownToHtml400Response(val *PostTextMarkdownToHtml400Response) *NullablePostTextMarkdownToHtml400Response {
	return &NullablePostTextMarkdownToHtml400Response{value: val, isSet: true}
}

func (v NullablePostTextMarkdownToHtml400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextMarkdownToHtml400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


