/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetDailyWord200ResponseWordsInnerExamplesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetDailyWord200ResponseWordsInnerExamplesInner{}

// GetDailyWord200ResponseWordsInnerExamplesInner struct for GetDailyWord200ResponseWordsInnerExamplesInner
type GetDailyWord200ResponseWordsInnerExamplesInner struct {
	Text *string `json:"text,omitempty"`
	Translation *string `json:"translation,omitempty"`
}

// NewGetDailyWord200ResponseWordsInnerExamplesInner instantiates a new GetDailyWord200ResponseWordsInnerExamplesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetDailyWord200ResponseWordsInnerExamplesInner() *GetDailyWord200ResponseWordsInnerExamplesInner {
	this := GetDailyWord200ResponseWordsInnerExamplesInner{}
	return &this
}

// NewGetDailyWord200ResponseWordsInnerExamplesInnerWithDefaults instantiates a new GetDailyWord200ResponseWordsInnerExamplesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetDailyWord200ResponseWordsInnerExamplesInnerWithDefaults() *GetDailyWord200ResponseWordsInnerExamplesInner {
	this := GetDailyWord200ResponseWordsInnerExamplesInner{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) SetText(v string) {
	o.Text = &v
}

// GetTranslation returns the Translation field value if set, zero value otherwise.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) GetTranslation() string {
	if o == nil || IsNil(o.Translation) {
		var ret string
		return ret
	}
	return *o.Translation
}

// GetTranslationOk returns a tuple with the Translation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) GetTranslationOk() (*string, bool) {
	if o == nil || IsNil(o.Translation) {
		return nil, false
	}
	return o.Translation, true
}

// HasTranslation returns a boolean if a field has been set.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) HasTranslation() bool {
	if o != nil && !IsNil(o.Translation) {
		return true
	}

	return false
}

// SetTranslation gets a reference to the given string and assigns it to the Translation field.
func (o *GetDailyWord200ResponseWordsInnerExamplesInner) SetTranslation(v string) {
	o.Translation = &v
}

func (o GetDailyWord200ResponseWordsInnerExamplesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetDailyWord200ResponseWordsInnerExamplesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Translation) {
		toSerialize["translation"] = o.Translation
	}
	return toSerialize, nil
}

type NullableGetDailyWord200ResponseWordsInnerExamplesInner struct {
	value *GetDailyWord200ResponseWordsInnerExamplesInner
	isSet bool
}

func (v NullableGetDailyWord200ResponseWordsInnerExamplesInner) Get() *GetDailyWord200ResponseWordsInnerExamplesInner {
	return v.value
}

func (v *NullableGetDailyWord200ResponseWordsInnerExamplesInner) Set(val *GetDailyWord200ResponseWordsInnerExamplesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetDailyWord200ResponseWordsInnerExamplesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetDailyWord200ResponseWordsInnerExamplesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetDailyWord200ResponseWordsInnerExamplesInner(val *GetDailyWord200ResponseWordsInnerExamplesInner) *NullableGetDailyWord200ResponseWordsInnerExamplesInner {
	return &NullableGetDailyWord200ResponseWordsInnerExamplesInner{value: val, isSet: true}
}

func (v NullableGetDailyWord200ResponseWordsInnerExamplesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetDailyWord200ResponseWordsInnerExamplesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


