/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostTextMarkdownToPdf503Response - struct for PostTextMarkdownToPdf503Response
type PostTextMarkdownToPdf503Response struct {
	PostTextMarkdownToPdf503ResponseOneOf *PostTextMarkdownToPdf503ResponseOneOf
	PostTextMarkdownToPdf503ResponseOneOf1 *PostTextMarkdownToPdf503ResponseOneOf1
}

// PostTextMarkdownToPdf503ResponseOneOfAsPostTextMarkdownToPdf503Response is a convenience function that returns PostTextMarkdownToPdf503ResponseOneOf wrapped in PostTextMarkdownToPdf503Response
func PostTextMarkdownToPdf503ResponseOneOfAsPostTextMarkdownToPdf503Response(v *PostTextMarkdownToPdf503ResponseOneOf) PostTextMarkdownToPdf503Response {
	return PostTextMarkdownToPdf503Response{
		PostTextMarkdownToPdf503ResponseOneOf: v,
	}
}

// PostTextMarkdownToPdf503ResponseOneOf1AsPostTextMarkdownToPdf503Response is a convenience function that returns PostTextMarkdownToPdf503ResponseOneOf1 wrapped in PostTextMarkdownToPdf503Response
func PostTextMarkdownToPdf503ResponseOneOf1AsPostTextMarkdownToPdf503Response(v *PostTextMarkdownToPdf503ResponseOneOf1) PostTextMarkdownToPdf503Response {
	return PostTextMarkdownToPdf503Response{
		PostTextMarkdownToPdf503ResponseOneOf1: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostTextMarkdownToPdf503Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into PostTextMarkdownToPdf503ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToPdf503ResponseOneOf)
	if err == nil {
		jsonPostTextMarkdownToPdf503ResponseOneOf, _ := json.Marshal(dst.PostTextMarkdownToPdf503ResponseOneOf)
		if string(jsonPostTextMarkdownToPdf503ResponseOneOf) == "{}" { // empty struct
			dst.PostTextMarkdownToPdf503ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToPdf503ResponseOneOf); err != nil {
				dst.PostTextMarkdownToPdf503ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToPdf503ResponseOneOf = nil
	}

	// try to unmarshal data into PostTextMarkdownToPdf503ResponseOneOf1
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToPdf503ResponseOneOf1)
	if err == nil {
		jsonPostTextMarkdownToPdf503ResponseOneOf1, _ := json.Marshal(dst.PostTextMarkdownToPdf503ResponseOneOf1)
		if string(jsonPostTextMarkdownToPdf503ResponseOneOf1) == "{}" { // empty struct
			dst.PostTextMarkdownToPdf503ResponseOneOf1 = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToPdf503ResponseOneOf1); err != nil {
				dst.PostTextMarkdownToPdf503ResponseOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToPdf503ResponseOneOf1 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.PostTextMarkdownToPdf503ResponseOneOf = nil
		dst.PostTextMarkdownToPdf503ResponseOneOf1 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostTextMarkdownToPdf503Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostTextMarkdownToPdf503Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostTextMarkdownToPdf503Response) MarshalJSON() ([]byte, error) {
	if src.PostTextMarkdownToPdf503ResponseOneOf != nil {
		return json.Marshal(&src.PostTextMarkdownToPdf503ResponseOneOf)
	}

	if src.PostTextMarkdownToPdf503ResponseOneOf1 != nil {
		return json.Marshal(&src.PostTextMarkdownToPdf503ResponseOneOf1)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostTextMarkdownToPdf503Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.PostTextMarkdownToPdf503ResponseOneOf != nil {
		return obj.PostTextMarkdownToPdf503ResponseOneOf
	}

	if obj.PostTextMarkdownToPdf503ResponseOneOf1 != nil {
		return obj.PostTextMarkdownToPdf503ResponseOneOf1
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PostTextMarkdownToPdf503Response) GetActualInstanceValue() (interface{}) {
	if obj.PostTextMarkdownToPdf503ResponseOneOf != nil {
		return *obj.PostTextMarkdownToPdf503ResponseOneOf
	}

	if obj.PostTextMarkdownToPdf503ResponseOneOf1 != nil {
		return *obj.PostTextMarkdownToPdf503ResponseOneOf1
	}

	// all schemas are nil
	return nil
}

type NullablePostTextMarkdownToPdf503Response struct {
	value *PostTextMarkdownToPdf503Response
	isSet bool
}

func (v NullablePostTextMarkdownToPdf503Response) Get() *PostTextMarkdownToPdf503Response {
	return v.value
}

func (v *NullablePostTextMarkdownToPdf503Response) Set(val *PostTextMarkdownToPdf503Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextMarkdownToPdf503Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextMarkdownToPdf503Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextMarkdownToPdf503Response(val *PostTextMarkdownToPdf503Response) *NullablePostTextMarkdownToPdf503Response {
	return &NullablePostTextMarkdownToPdf503Response{value: val, isSet: true}
}

func (v NullablePostTextMarkdownToPdf503Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextMarkdownToPdf503Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


