/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetGithubRepo502Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGithubRepo502Response{}

// GetGithubRepo502Response struct for GetGithubRepo502Response
type GetGithubRepo502Response struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGetGithubRepo502Response instantiates a new GetGithubRepo502Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGithubRepo502Response() *GetGithubRepo502Response {
	this := GetGithubRepo502Response{}
	return &this
}

// NewGetGithubRepo502ResponseWithDefaults instantiates a new GetGithubRepo502Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGithubRepo502ResponseWithDefaults() *GetGithubRepo502Response {
	this := GetGithubRepo502Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetGithubRepo502Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubRepo502Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetGithubRepo502Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetGithubRepo502Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetGithubRepo502Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubRepo502Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetGithubRepo502Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetGithubRepo502Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetGithubRepo502Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGithubRepo502Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetGithubRepo502Response struct {
	value *GetGithubRepo502Response
	isSet bool
}

func (v NullableGetGithubRepo502Response) Get() *GetGithubRepo502Response {
	return v.value
}

func (v *NullableGetGithubRepo502Response) Set(val *GetGithubRepo502Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGithubRepo502Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGithubRepo502Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGithubRepo502Response(val *GetGithubRepo502Response) *NullableGetGithubRepo502Response {
	return &NullableGetGithubRepo502Response{value: val, isSet: true}
}

func (v NullableGetGithubRepo502Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGithubRepo502Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


