/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"fmt"
)


// GetWebTomarkdownAsyncStatus200Response struct for GetWebTomarkdownAsyncStatus200Response
type GetWebTomarkdownAsyncStatus200Response struct {
	GetWebTomarkdownAsyncStatus200ResponseAnyOf *GetWebTomarkdownAsyncStatus200ResponseAnyOf
	GetWebTomarkdownAsyncStatus200ResponseAnyOf1 *GetWebTomarkdownAsyncStatus200ResponseAnyOf1
	GetWebTomarkdownAsyncStatus200ResponseAnyOf2 *GetWebTomarkdownAsyncStatus200ResponseAnyOf2
	GetWebTomarkdownAsyncStatus200ResponseAnyOf3 *GetWebTomarkdownAsyncStatus200ResponseAnyOf3
}

// Unmarshal JSON data into any of the pointers in the struct
func (dst *GetWebTomarkdownAsyncStatus200Response) UnmarshalJSON(data []byte) error {
	var err error
	// try to unmarshal JSON data into GetWebTomarkdownAsyncStatus200ResponseAnyOf
	err = json.Unmarshal(data, &dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf);
	if err == nil {
		jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf, _ := json.Marshal(dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf)
		if string(jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf) == "{}" { // empty struct
			dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf = nil
		} else {
			return nil // data stored in dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf, return on the first match
		}
	} else {
		dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf = nil
	}

	// try to unmarshal JSON data into GetWebTomarkdownAsyncStatus200ResponseAnyOf1
	err = json.Unmarshal(data, &dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf1);
	if err == nil {
		jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf1, _ := json.Marshal(dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf1)
		if string(jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf1) == "{}" { // empty struct
			dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf1 = nil
		} else {
			return nil // data stored in dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf1, return on the first match
		}
	} else {
		dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf1 = nil
	}

	// try to unmarshal JSON data into GetWebTomarkdownAsyncStatus200ResponseAnyOf2
	err = json.Unmarshal(data, &dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf2);
	if err == nil {
		jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf2, _ := json.Marshal(dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf2)
		if string(jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf2) == "{}" { // empty struct
			dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf2 = nil
		} else {
			return nil // data stored in dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf2, return on the first match
		}
	} else {
		dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf2 = nil
	}

	// try to unmarshal JSON data into GetWebTomarkdownAsyncStatus200ResponseAnyOf3
	err = json.Unmarshal(data, &dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf3);
	if err == nil {
		jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf3, _ := json.Marshal(dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf3)
		if string(jsonGetWebTomarkdownAsyncStatus200ResponseAnyOf3) == "{}" { // empty struct
			dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf3 = nil
		} else {
			return nil // data stored in dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf3, return on the first match
		}
	} else {
		dst.GetWebTomarkdownAsyncStatus200ResponseAnyOf3 = nil
	}

	return fmt.Errorf("data failed to match schemas in anyOf(GetWebTomarkdownAsyncStatus200Response)")
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src GetWebTomarkdownAsyncStatus200Response) MarshalJSON() ([]byte, error) {
	if src.GetWebTomarkdownAsyncStatus200ResponseAnyOf != nil {
		return json.Marshal(&src.GetWebTomarkdownAsyncStatus200ResponseAnyOf)
	}

	if src.GetWebTomarkdownAsyncStatus200ResponseAnyOf1 != nil {
		return json.Marshal(&src.GetWebTomarkdownAsyncStatus200ResponseAnyOf1)
	}

	if src.GetWebTomarkdownAsyncStatus200ResponseAnyOf2 != nil {
		return json.Marshal(&src.GetWebTomarkdownAsyncStatus200ResponseAnyOf2)
	}

	if src.GetWebTomarkdownAsyncStatus200ResponseAnyOf3 != nil {
		return json.Marshal(&src.GetWebTomarkdownAsyncStatus200ResponseAnyOf3)
	}

	return nil, nil // no data in anyOf schemas
}


type NullableGetWebTomarkdownAsyncStatus200Response struct {
	value *GetWebTomarkdownAsyncStatus200Response
	isSet bool
}

func (v NullableGetWebTomarkdownAsyncStatus200Response) Get() *GetWebTomarkdownAsyncStatus200Response {
	return v.value
}

func (v *NullableGetWebTomarkdownAsyncStatus200Response) Set(val *GetWebTomarkdownAsyncStatus200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebTomarkdownAsyncStatus200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebTomarkdownAsyncStatus200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebTomarkdownAsyncStatus200Response(val *GetWebTomarkdownAsyncStatus200Response) *NullableGetWebTomarkdownAsyncStatus200Response {
	return &NullableGetWebTomarkdownAsyncStatus200Response{value: val, isSet: true}
}

func (v NullableGetWebTomarkdownAsyncStatus200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebTomarkdownAsyncStatus200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


