/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetSocialQqGroupinfo200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSocialQqGroupinfo200Response{}

// GetSocialQqGroupinfo200Response struct for GetSocialQqGroupinfo200Response
type GetSocialQqGroupinfo200Response struct {
	// 群号
	GroupId *string `json:"group_id,omitempty"`
	// 群名称
	GroupName *string `json:"group_name,omitempty"`
	// 群头像URL（标准尺寸100x100）
	AvatarUrl *string `json:"avatar_url,omitempty"`
	// 群描述/简介
	Description *string `json:"description,omitempty"`
	// 群标签
	Tag *string `json:"tag,omitempty"`
	// 加群链接（QR码URL）
	JoinUrl *string `json:"join_url,omitempty"`
	// 最后更新时间（ISO 8601格式）
	LastUpdated *string `json:"last_updated,omitempty"`
}

// NewGetSocialQqGroupinfo200Response instantiates a new GetSocialQqGroupinfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSocialQqGroupinfo200Response() *GetSocialQqGroupinfo200Response {
	this := GetSocialQqGroupinfo200Response{}
	return &this
}

// NewGetSocialQqGroupinfo200ResponseWithDefaults instantiates a new GetSocialQqGroupinfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSocialQqGroupinfo200ResponseWithDefaults() *GetSocialQqGroupinfo200Response {
	this := GetSocialQqGroupinfo200Response{}
	return &this
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *GetSocialQqGroupinfo200Response) GetGroupId() string {
	if o == nil || IsNil(o.GroupId) {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialQqGroupinfo200Response) GetGroupIdOk() (*string, bool) {
	if o == nil || IsNil(o.GroupId) {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *GetSocialQqGroupinfo200Response) HasGroupId() bool {
	if o != nil && !IsNil(o.GroupId) {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *GetSocialQqGroupinfo200Response) SetGroupId(v string) {
	o.GroupId = &v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *GetSocialQqGroupinfo200Response) GetGroupName() string {
	if o == nil || IsNil(o.GroupName) {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialQqGroupinfo200Response) GetGroupNameOk() (*string, bool) {
	if o == nil || IsNil(o.GroupName) {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *GetSocialQqGroupinfo200Response) HasGroupName() bool {
	if o != nil && !IsNil(o.GroupName) {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *GetSocialQqGroupinfo200Response) SetGroupName(v string) {
	o.GroupName = &v
}

// GetAvatarUrl returns the AvatarUrl field value if set, zero value otherwise.
func (o *GetSocialQqGroupinfo200Response) GetAvatarUrl() string {
	if o == nil || IsNil(o.AvatarUrl) {
		var ret string
		return ret
	}
	return *o.AvatarUrl
}

// GetAvatarUrlOk returns a tuple with the AvatarUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialQqGroupinfo200Response) GetAvatarUrlOk() (*string, bool) {
	if o == nil || IsNil(o.AvatarUrl) {
		return nil, false
	}
	return o.AvatarUrl, true
}

// HasAvatarUrl returns a boolean if a field has been set.
func (o *GetSocialQqGroupinfo200Response) HasAvatarUrl() bool {
	if o != nil && !IsNil(o.AvatarUrl) {
		return true
	}

	return false
}

// SetAvatarUrl gets a reference to the given string and assigns it to the AvatarUrl field.
func (o *GetSocialQqGroupinfo200Response) SetAvatarUrl(v string) {
	o.AvatarUrl = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetSocialQqGroupinfo200Response) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialQqGroupinfo200Response) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetSocialQqGroupinfo200Response) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetSocialQqGroupinfo200Response) SetDescription(v string) {
	o.Description = &v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *GetSocialQqGroupinfo200Response) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialQqGroupinfo200Response) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *GetSocialQqGroupinfo200Response) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *GetSocialQqGroupinfo200Response) SetTag(v string) {
	o.Tag = &v
}

// GetJoinUrl returns the JoinUrl field value if set, zero value otherwise.
func (o *GetSocialQqGroupinfo200Response) GetJoinUrl() string {
	if o == nil || IsNil(o.JoinUrl) {
		var ret string
		return ret
	}
	return *o.JoinUrl
}

// GetJoinUrlOk returns a tuple with the JoinUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialQqGroupinfo200Response) GetJoinUrlOk() (*string, bool) {
	if o == nil || IsNil(o.JoinUrl) {
		return nil, false
	}
	return o.JoinUrl, true
}

// HasJoinUrl returns a boolean if a field has been set.
func (o *GetSocialQqGroupinfo200Response) HasJoinUrl() bool {
	if o != nil && !IsNil(o.JoinUrl) {
		return true
	}

	return false
}

// SetJoinUrl gets a reference to the given string and assigns it to the JoinUrl field.
func (o *GetSocialQqGroupinfo200Response) SetJoinUrl(v string) {
	o.JoinUrl = &v
}

// GetLastUpdated returns the LastUpdated field value if set, zero value otherwise.
func (o *GetSocialQqGroupinfo200Response) GetLastUpdated() string {
	if o == nil || IsNil(o.LastUpdated) {
		var ret string
		return ret
	}
	return *o.LastUpdated
}

// GetLastUpdatedOk returns a tuple with the LastUpdated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialQqGroupinfo200Response) GetLastUpdatedOk() (*string, bool) {
	if o == nil || IsNil(o.LastUpdated) {
		return nil, false
	}
	return o.LastUpdated, true
}

// HasLastUpdated returns a boolean if a field has been set.
func (o *GetSocialQqGroupinfo200Response) HasLastUpdated() bool {
	if o != nil && !IsNil(o.LastUpdated) {
		return true
	}

	return false
}

// SetLastUpdated gets a reference to the given string and assigns it to the LastUpdated field.
func (o *GetSocialQqGroupinfo200Response) SetLastUpdated(v string) {
	o.LastUpdated = &v
}

func (o GetSocialQqGroupinfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSocialQqGroupinfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupId) {
		toSerialize["group_id"] = o.GroupId
	}
	if !IsNil(o.GroupName) {
		toSerialize["group_name"] = o.GroupName
	}
	if !IsNil(o.AvatarUrl) {
		toSerialize["avatar_url"] = o.AvatarUrl
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.JoinUrl) {
		toSerialize["join_url"] = o.JoinUrl
	}
	if !IsNil(o.LastUpdated) {
		toSerialize["last_updated"] = o.LastUpdated
	}
	return toSerialize, nil
}

type NullableGetSocialQqGroupinfo200Response struct {
	value *GetSocialQqGroupinfo200Response
	isSet bool
}

func (v NullableGetSocialQqGroupinfo200Response) Get() *GetSocialQqGroupinfo200Response {
	return v.value
}

func (v *NullableGetSocialQqGroupinfo200Response) Set(val *GetSocialQqGroupinfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSocialQqGroupinfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSocialQqGroupinfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSocialQqGroupinfo200Response(val *GetSocialQqGroupinfo200Response) *NullableGetSocialQqGroupinfo200Response {
	return &NullableGetSocialQqGroupinfo200Response{value: val, isSet: true}
}

func (v NullableGetSocialQqGroupinfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSocialQqGroupinfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


