/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetWebTomarkdownAsyncStatus200ResponseAnyOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWebTomarkdownAsyncStatus200ResponseAnyOf1{}

// GetWebTomarkdownAsyncStatus200ResponseAnyOf1 struct for GetWebTomarkdownAsyncStatus200ResponseAnyOf1
type GetWebTomarkdownAsyncStatus200ResponseAnyOf1 struct {
	TaskId *string `json:"task_id,omitempty"`
	Status *string `json:"status,omitempty"`
	Url *string `json:"url,omitempty"`
	Progress *int32 `json:"progress,omitempty"`
	CreatedAt *string `json:"created_at,omitempty"`
	StartedAt *string `json:"started_at,omitempty"`
	Elapsed *float32 `json:"elapsed,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGetWebTomarkdownAsyncStatus200ResponseAnyOf1 instantiates a new GetWebTomarkdownAsyncStatus200ResponseAnyOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWebTomarkdownAsyncStatus200ResponseAnyOf1() *GetWebTomarkdownAsyncStatus200ResponseAnyOf1 {
	this := GetWebTomarkdownAsyncStatus200ResponseAnyOf1{}
	return &this
}

// NewGetWebTomarkdownAsyncStatus200ResponseAnyOf1WithDefaults instantiates a new GetWebTomarkdownAsyncStatus200ResponseAnyOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWebTomarkdownAsyncStatus200ResponseAnyOf1WithDefaults() *GetWebTomarkdownAsyncStatus200ResponseAnyOf1 {
	this := GetWebTomarkdownAsyncStatus200ResponseAnyOf1{}
	return &this
}

// GetTaskId returns the TaskId field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetTaskId() string {
	if o == nil || IsNil(o.TaskId) {
		var ret string
		return ret
	}
	return *o.TaskId
}

// GetTaskIdOk returns a tuple with the TaskId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetTaskIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaskId) {
		return nil, false
	}
	return o.TaskId, true
}

// HasTaskId returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasTaskId() bool {
	if o != nil && !IsNil(o.TaskId) {
		return true
	}

	return false
}

// SetTaskId gets a reference to the given string and assigns it to the TaskId field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetTaskId(v string) {
	o.TaskId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetStatus(v string) {
	o.Status = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetUrl(v string) {
	o.Url = &v
}

// GetProgress returns the Progress field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetProgress() int32 {
	if o == nil || IsNil(o.Progress) {
		var ret int32
		return ret
	}
	return *o.Progress
}

// GetProgressOk returns a tuple with the Progress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetProgressOk() (*int32, bool) {
	if o == nil || IsNil(o.Progress) {
		return nil, false
	}
	return o.Progress, true
}

// HasProgress returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasProgress() bool {
	if o != nil && !IsNil(o.Progress) {
		return true
	}

	return false
}

// SetProgress gets a reference to the given int32 and assigns it to the Progress field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetProgress(v int32) {
	o.Progress = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetCreatedAt() string {
	if o == nil || IsNil(o.CreatedAt) {
		var ret string
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetCreatedAtOk() (*string, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given string and assigns it to the CreatedAt field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetCreatedAt(v string) {
	o.CreatedAt = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetStartedAt() string {
	if o == nil || IsNil(o.StartedAt) {
		var ret string
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetStartedAtOk() (*string, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given string and assigns it to the StartedAt field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetStartedAt(v string) {
	o.StartedAt = &v
}

// GetElapsed returns the Elapsed field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetElapsed() float32 {
	if o == nil || IsNil(o.Elapsed) {
		var ret float32
		return ret
	}
	return *o.Elapsed
}

// GetElapsedOk returns a tuple with the Elapsed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetElapsedOk() (*float32, bool) {
	if o == nil || IsNil(o.Elapsed) {
		return nil, false
	}
	return o.Elapsed, true
}

// HasElapsed returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasElapsed() bool {
	if o != nil && !IsNil(o.Elapsed) {
		return true
	}

	return false
}

// SetElapsed gets a reference to the given float32 and assigns it to the Elapsed field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetElapsed(v float32) {
	o.Elapsed = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) SetMessage(v string) {
	o.Message = &v
}

func (o GetWebTomarkdownAsyncStatus200ResponseAnyOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWebTomarkdownAsyncStatus200ResponseAnyOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaskId) {
		toSerialize["task_id"] = o.TaskId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	if !IsNil(o.Progress) {
		toSerialize["progress"] = o.Progress
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.Elapsed) {
		toSerialize["elapsed"] = o.Elapsed
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1 struct {
	value *GetWebTomarkdownAsyncStatus200ResponseAnyOf1
	isSet bool
}

func (v NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1) Get() *GetWebTomarkdownAsyncStatus200ResponseAnyOf1 {
	return v.value
}

func (v *NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1) Set(val *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1(val *GetWebTomarkdownAsyncStatus200ResponseAnyOf1) *NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1 {
	return &NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1{value: val, isSet: true}
}

func (v NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebTomarkdownAsyncStatus200ResponseAnyOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


