/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostTextMd5Verify200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTextMd5Verify200Response{}

// PostTextMd5Verify200Response struct for PostTextMd5Verify200Response
type PostTextMd5Verify200Response struct {
	Match *bool `json:"match,omitempty"`
}

// NewPostTextMd5Verify200Response instantiates a new PostTextMd5Verify200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTextMd5Verify200Response() *PostTextMd5Verify200Response {
	this := PostTextMd5Verify200Response{}
	return &this
}

// NewPostTextMd5Verify200ResponseWithDefaults instantiates a new PostTextMd5Verify200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTextMd5Verify200ResponseWithDefaults() *PostTextMd5Verify200Response {
	this := PostTextMd5Verify200Response{}
	return &this
}

// GetMatch returns the Match field value if set, zero value otherwise.
func (o *PostTextMd5Verify200Response) GetMatch() bool {
	if o == nil || IsNil(o.Match) {
		var ret bool
		return ret
	}
	return *o.Match
}

// GetMatchOk returns a tuple with the Match field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTextMd5Verify200Response) GetMatchOk() (*bool, bool) {
	if o == nil || IsNil(o.Match) {
		return nil, false
	}
	return o.Match, true
}

// HasMatch returns a boolean if a field has been set.
func (o *PostTextMd5Verify200Response) HasMatch() bool {
	if o != nil && !IsNil(o.Match) {
		return true
	}

	return false
}

// SetMatch gets a reference to the given bool and assigns it to the Match field.
func (o *PostTextMd5Verify200Response) SetMatch(v bool) {
	o.Match = &v
}

func (o PostTextMd5Verify200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTextMd5Verify200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Match) {
		toSerialize["match"] = o.Match
	}
	return toSerialize, nil
}

type NullablePostTextMd5Verify200Response struct {
	value *PostTextMd5Verify200Response
	isSet bool
}

func (v NullablePostTextMd5Verify200Response) Get() *PostTextMd5Verify200Response {
	return v.value
}

func (v *NullablePostTextMd5Verify200Response) Set(val *PostTextMd5Verify200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextMd5Verify200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextMd5Verify200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextMd5Verify200Response(val *PostTextMd5Verify200Response) *NullablePostTextMd5Verify200Response {
	return &NullablePostTextMd5Verify200Response{value: val, isSet: true}
}

func (v NullablePostTextMd5Verify200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextMd5Verify200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


