/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostImageFrombase64Request type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostImageFrombase64Request{}

// PostImageFrombase64Request struct for PostImageFrombase64Request
type PostImageFrombase64Request struct {
	// 图片的Base64 Data URI，必须包含MIME类型头。例如：`data:image/png;base64,...`
	ImageData string `json:"imageData"`
}

type _PostImageFrombase64Request PostImageFrombase64Request

// NewPostImageFrombase64Request instantiates a new PostImageFrombase64Request object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostImageFrombase64Request(imageData string) *PostImageFrombase64Request {
	this := PostImageFrombase64Request{}
	this.ImageData = imageData
	return &this
}

// NewPostImageFrombase64RequestWithDefaults instantiates a new PostImageFrombase64Request object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostImageFrombase64RequestWithDefaults() *PostImageFrombase64Request {
	this := PostImageFrombase64Request{}
	return &this
}

// GetImageData returns the ImageData field value
func (o *PostImageFrombase64Request) GetImageData() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ImageData
}

// GetImageDataOk returns a tuple with the ImageData field value
// and a boolean to check if the value has been set.
func (o *PostImageFrombase64Request) GetImageDataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ImageData, true
}

// SetImageData sets field value
func (o *PostImageFrombase64Request) SetImageData(v string) {
	o.ImageData = v
}

func (o PostImageFrombase64Request) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostImageFrombase64Request) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["imageData"] = o.ImageData
	return toSerialize, nil
}

func (o *PostImageFrombase64Request) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"imageData",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostImageFrombase64Request := _PostImageFrombase64Request{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostImageFrombase64Request)

	if err != nil {
		return err
	}

	*o = PostImageFrombase64Request(varPostImageFrombase64Request)

	return err
}

type NullablePostImageFrombase64Request struct {
	value *PostImageFrombase64Request
	isSet bool
}

func (v NullablePostImageFrombase64Request) Get() *PostImageFrombase64Request {
	return v.value
}

func (v *NullablePostImageFrombase64Request) Set(val *PostImageFrombase64Request) {
	v.value = val
	v.isSet = true
}

func (v NullablePostImageFrombase64Request) IsSet() bool {
	return v.isSet
}

func (v *NullablePostImageFrombase64Request) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostImageFrombase64Request(val *PostImageFrombase64Request) *NullablePostImageFrombase64Request {
	return &NullablePostImageFrombase64Request{value: val, isSet: true}
}

func (v NullablePostImageFrombase64Request) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostImageFrombase64Request) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


