/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetGithubRepo200ResponseCollaboratorsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGithubRepo200ResponseCollaboratorsInner{}

// GetGithubRepo200ResponseCollaboratorsInner struct for GetGithubRepo200ResponseCollaboratorsInner
type GetGithubRepo200ResponseCollaboratorsInner struct {
	Login *string `json:"login,omitempty"`
	Name *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
	Url *string `json:"url,omitempty"`
}

// NewGetGithubRepo200ResponseCollaboratorsInner instantiates a new GetGithubRepo200ResponseCollaboratorsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGithubRepo200ResponseCollaboratorsInner() *GetGithubRepo200ResponseCollaboratorsInner {
	this := GetGithubRepo200ResponseCollaboratorsInner{}
	return &this
}

// NewGetGithubRepo200ResponseCollaboratorsInnerWithDefaults instantiates a new GetGithubRepo200ResponseCollaboratorsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGithubRepo200ResponseCollaboratorsInnerWithDefaults() *GetGithubRepo200ResponseCollaboratorsInner {
	this := GetGithubRepo200ResponseCollaboratorsInner{}
	return &this
}

// GetLogin returns the Login field value if set, zero value otherwise.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetLogin() string {
	if o == nil || IsNil(o.Login) {
		var ret string
		return ret
	}
	return *o.Login
}

// GetLoginOk returns a tuple with the Login field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetLoginOk() (*string, bool) {
	if o == nil || IsNil(o.Login) {
		return nil, false
	}
	return o.Login, true
}

// HasLogin returns a boolean if a field has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) HasLogin() bool {
	if o != nil && !IsNil(o.Login) {
		return true
	}

	return false
}

// SetLogin gets a reference to the given string and assigns it to the Login field.
func (o *GetGithubRepo200ResponseCollaboratorsInner) SetLogin(v string) {
	o.Login = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetGithubRepo200ResponseCollaboratorsInner) SetName(v string) {
	o.Name = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *GetGithubRepo200ResponseCollaboratorsInner) SetEmail(v string) {
	o.Email = &v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *GetGithubRepo200ResponseCollaboratorsInner) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *GetGithubRepo200ResponseCollaboratorsInner) SetUrl(v string) {
	o.Url = &v
}

func (o GetGithubRepo200ResponseCollaboratorsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGithubRepo200ResponseCollaboratorsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Login) {
		toSerialize["login"] = o.Login
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableGetGithubRepo200ResponseCollaboratorsInner struct {
	value *GetGithubRepo200ResponseCollaboratorsInner
	isSet bool
}

func (v NullableGetGithubRepo200ResponseCollaboratorsInner) Get() *GetGithubRepo200ResponseCollaboratorsInner {
	return v.value
}

func (v *NullableGetGithubRepo200ResponseCollaboratorsInner) Set(val *GetGithubRepo200ResponseCollaboratorsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGithubRepo200ResponseCollaboratorsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGithubRepo200ResponseCollaboratorsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGithubRepo200ResponseCollaboratorsInner(val *GetGithubRepo200ResponseCollaboratorsInner) *NullableGetGithubRepo200ResponseCollaboratorsInner {
	return &NullableGetGithubRepo200ResponseCollaboratorsInner{value: val, isSet: true}
}

func (v NullableGetGithubRepo200ResponseCollaboratorsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGithubRepo200ResponseCollaboratorsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


