/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscWeatherHistory200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscWeatherHistory200Response{}

// GetMiscWeatherHistory200Response struct for GetMiscWeatherHistory200Response
type GetMiscWeatherHistory200Response struct {
	Adcode *string `json:"adcode,omitempty"`
	City *string `json:"city,omitempty"`
	Days []GetMiscWeatherHistory200ResponseDaysInner `json:"days,omitempty"`
	EndDate *string `json:"end_date,omitempty"`
	StartDate *string `json:"start_date,omitempty"`
}

// NewGetMiscWeatherHistory200Response instantiates a new GetMiscWeatherHistory200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscWeatherHistory200Response() *GetMiscWeatherHistory200Response {
	this := GetMiscWeatherHistory200Response{}
	return &this
}

// NewGetMiscWeatherHistory200ResponseWithDefaults instantiates a new GetMiscWeatherHistory200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscWeatherHistory200ResponseWithDefaults() *GetMiscWeatherHistory200Response {
	this := GetMiscWeatherHistory200Response{}
	return &this
}

// GetAdcode returns the Adcode field value if set, zero value otherwise.
func (o *GetMiscWeatherHistory200Response) GetAdcode() string {
	if o == nil || IsNil(o.Adcode) {
		var ret string
		return ret
	}
	return *o.Adcode
}

// GetAdcodeOk returns a tuple with the Adcode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeatherHistory200Response) GetAdcodeOk() (*string, bool) {
	if o == nil || IsNil(o.Adcode) {
		return nil, false
	}
	return o.Adcode, true
}

// HasAdcode returns a boolean if a field has been set.
func (o *GetMiscWeatherHistory200Response) HasAdcode() bool {
	if o != nil && !IsNil(o.Adcode) {
		return true
	}

	return false
}

// SetAdcode gets a reference to the given string and assigns it to the Adcode field.
func (o *GetMiscWeatherHistory200Response) SetAdcode(v string) {
	o.Adcode = &v
}

// GetCity returns the City field value if set, zero value otherwise.
func (o *GetMiscWeatherHistory200Response) GetCity() string {
	if o == nil || IsNil(o.City) {
		var ret string
		return ret
	}
	return *o.City
}

// GetCityOk returns a tuple with the City field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeatherHistory200Response) GetCityOk() (*string, bool) {
	if o == nil || IsNil(o.City) {
		return nil, false
	}
	return o.City, true
}

// HasCity returns a boolean if a field has been set.
func (o *GetMiscWeatherHistory200Response) HasCity() bool {
	if o != nil && !IsNil(o.City) {
		return true
	}

	return false
}

// SetCity gets a reference to the given string and assigns it to the City field.
func (o *GetMiscWeatherHistory200Response) SetCity(v string) {
	o.City = &v
}

// GetDays returns the Days field value if set, zero value otherwise.
func (o *GetMiscWeatherHistory200Response) GetDays() []GetMiscWeatherHistory200ResponseDaysInner {
	if o == nil || IsNil(o.Days) {
		var ret []GetMiscWeatherHistory200ResponseDaysInner
		return ret
	}
	return o.Days
}

// GetDaysOk returns a tuple with the Days field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeatherHistory200Response) GetDaysOk() ([]GetMiscWeatherHistory200ResponseDaysInner, bool) {
	if o == nil || IsNil(o.Days) {
		return nil, false
	}
	return o.Days, true
}

// HasDays returns a boolean if a field has been set.
func (o *GetMiscWeatherHistory200Response) HasDays() bool {
	if o != nil && !IsNil(o.Days) {
		return true
	}

	return false
}

// SetDays gets a reference to the given []GetMiscWeatherHistory200ResponseDaysInner and assigns it to the Days field.
func (o *GetMiscWeatherHistory200Response) SetDays(v []GetMiscWeatherHistory200ResponseDaysInner) {
	o.Days = v
}

// GetEndDate returns the EndDate field value if set, zero value otherwise.
func (o *GetMiscWeatherHistory200Response) GetEndDate() string {
	if o == nil || IsNil(o.EndDate) {
		var ret string
		return ret
	}
	return *o.EndDate
}

// GetEndDateOk returns a tuple with the EndDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeatherHistory200Response) GetEndDateOk() (*string, bool) {
	if o == nil || IsNil(o.EndDate) {
		return nil, false
	}
	return o.EndDate, true
}

// HasEndDate returns a boolean if a field has been set.
func (o *GetMiscWeatherHistory200Response) HasEndDate() bool {
	if o != nil && !IsNil(o.EndDate) {
		return true
	}

	return false
}

// SetEndDate gets a reference to the given string and assigns it to the EndDate field.
func (o *GetMiscWeatherHistory200Response) SetEndDate(v string) {
	o.EndDate = &v
}

// GetStartDate returns the StartDate field value if set, zero value otherwise.
func (o *GetMiscWeatherHistory200Response) GetStartDate() string {
	if o == nil || IsNil(o.StartDate) {
		var ret string
		return ret
	}
	return *o.StartDate
}

// GetStartDateOk returns a tuple with the StartDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeatherHistory200Response) GetStartDateOk() (*string, bool) {
	if o == nil || IsNil(o.StartDate) {
		return nil, false
	}
	return o.StartDate, true
}

// HasStartDate returns a boolean if a field has been set.
func (o *GetMiscWeatherHistory200Response) HasStartDate() bool {
	if o != nil && !IsNil(o.StartDate) {
		return true
	}

	return false
}

// SetStartDate gets a reference to the given string and assigns it to the StartDate field.
func (o *GetMiscWeatherHistory200Response) SetStartDate(v string) {
	o.StartDate = &v
}

func (o GetMiscWeatherHistory200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscWeatherHistory200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Adcode) {
		toSerialize["adcode"] = o.Adcode
	}
	if !IsNil(o.City) {
		toSerialize["city"] = o.City
	}
	if !IsNil(o.Days) {
		toSerialize["days"] = o.Days
	}
	if !IsNil(o.EndDate) {
		toSerialize["end_date"] = o.EndDate
	}
	if !IsNil(o.StartDate) {
		toSerialize["start_date"] = o.StartDate
	}
	return toSerialize, nil
}

type NullableGetMiscWeatherHistory200Response struct {
	value *GetMiscWeatherHistory200Response
	isSet bool
}

func (v NullableGetMiscWeatherHistory200Response) Get() *GetMiscWeatherHistory200Response {
	return v.value
}

func (v *NullableGetMiscWeatherHistory200Response) Set(val *GetMiscWeatherHistory200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscWeatherHistory200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscWeatherHistory200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscWeatherHistory200Response(val *GetMiscWeatherHistory200Response) *NullableGetMiscWeatherHistory200Response {
	return &NullableGetMiscWeatherHistory200Response{value: val, isSet: true}
}

func (v NullableGetMiscWeatherHistory200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscWeatherHistory200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


