/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetNetworkPing400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkPing400Response{}

// GetNetworkPing400Response struct for GetNetworkPing400Response
type GetNetworkPing400Response struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGetNetworkPing400Response instantiates a new GetNetworkPing400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkPing400Response() *GetNetworkPing400Response {
	this := GetNetworkPing400Response{}
	return &this
}

// NewGetNetworkPing400ResponseWithDefaults instantiates a new GetNetworkPing400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkPing400ResponseWithDefaults() *GetNetworkPing400Response {
	this := GetNetworkPing400Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetNetworkPing400Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing400Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetNetworkPing400Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetNetworkPing400Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetNetworkPing400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetNetworkPing400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetNetworkPing400Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetNetworkPing400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkPing400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetNetworkPing400Response struct {
	value *GetNetworkPing400Response
	isSet bool
}

func (v NullableGetNetworkPing400Response) Get() *GetNetworkPing400Response {
	return v.value
}

func (v *NullableGetNetworkPing400Response) Set(val *GetNetworkPing400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkPing400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkPing400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkPing400Response(val *GetNetworkPing400Response) *NullableGetNetworkPing400Response {
	return &NullableGetNetworkPing400Response{value: val, isSet: true}
}

func (v NullableGetNetworkPing400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkPing400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


