/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscTimestamp200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscTimestamp200Response{}

// GetMiscTimestamp200Response struct for GetMiscTimestamp200Response
type GetMiscTimestamp200Response struct {
	DatetimeLocal *string `json:"datetime_local,omitempty"`
	DatetimeUtc *string `json:"datetime_utc,omitempty"`
	Input *string `json:"input,omitempty"`
	Type *string `json:"type,omitempty"`
	UnixTimestamp *int32 `json:"unix_timestamp,omitempty"`
}

// NewGetMiscTimestamp200Response instantiates a new GetMiscTimestamp200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscTimestamp200Response() *GetMiscTimestamp200Response {
	this := GetMiscTimestamp200Response{}
	return &this
}

// NewGetMiscTimestamp200ResponseWithDefaults instantiates a new GetMiscTimestamp200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscTimestamp200ResponseWithDefaults() *GetMiscTimestamp200Response {
	this := GetMiscTimestamp200Response{}
	return &this
}

// GetDatetimeLocal returns the DatetimeLocal field value if set, zero value otherwise.
func (o *GetMiscTimestamp200Response) GetDatetimeLocal() string {
	if o == nil || IsNil(o.DatetimeLocal) {
		var ret string
		return ret
	}
	return *o.DatetimeLocal
}

// GetDatetimeLocalOk returns a tuple with the DatetimeLocal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTimestamp200Response) GetDatetimeLocalOk() (*string, bool) {
	if o == nil || IsNil(o.DatetimeLocal) {
		return nil, false
	}
	return o.DatetimeLocal, true
}

// HasDatetimeLocal returns a boolean if a field has been set.
func (o *GetMiscTimestamp200Response) HasDatetimeLocal() bool {
	if o != nil && !IsNil(o.DatetimeLocal) {
		return true
	}

	return false
}

// SetDatetimeLocal gets a reference to the given string and assigns it to the DatetimeLocal field.
func (o *GetMiscTimestamp200Response) SetDatetimeLocal(v string) {
	o.DatetimeLocal = &v
}

// GetDatetimeUtc returns the DatetimeUtc field value if set, zero value otherwise.
func (o *GetMiscTimestamp200Response) GetDatetimeUtc() string {
	if o == nil || IsNil(o.DatetimeUtc) {
		var ret string
		return ret
	}
	return *o.DatetimeUtc
}

// GetDatetimeUtcOk returns a tuple with the DatetimeUtc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTimestamp200Response) GetDatetimeUtcOk() (*string, bool) {
	if o == nil || IsNil(o.DatetimeUtc) {
		return nil, false
	}
	return o.DatetimeUtc, true
}

// HasDatetimeUtc returns a boolean if a field has been set.
func (o *GetMiscTimestamp200Response) HasDatetimeUtc() bool {
	if o != nil && !IsNil(o.DatetimeUtc) {
		return true
	}

	return false
}

// SetDatetimeUtc gets a reference to the given string and assigns it to the DatetimeUtc field.
func (o *GetMiscTimestamp200Response) SetDatetimeUtc(v string) {
	o.DatetimeUtc = &v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *GetMiscTimestamp200Response) GetInput() string {
	if o == nil || IsNil(o.Input) {
		var ret string
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTimestamp200Response) GetInputOk() (*string, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *GetMiscTimestamp200Response) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given string and assigns it to the Input field.
func (o *GetMiscTimestamp200Response) SetInput(v string) {
	o.Input = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetMiscTimestamp200Response) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTimestamp200Response) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetMiscTimestamp200Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetMiscTimestamp200Response) SetType(v string) {
	o.Type = &v
}

// GetUnixTimestamp returns the UnixTimestamp field value if set, zero value otherwise.
func (o *GetMiscTimestamp200Response) GetUnixTimestamp() int32 {
	if o == nil || IsNil(o.UnixTimestamp) {
		var ret int32
		return ret
	}
	return *o.UnixTimestamp
}

// GetUnixTimestampOk returns a tuple with the UnixTimestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTimestamp200Response) GetUnixTimestampOk() (*int32, bool) {
	if o == nil || IsNil(o.UnixTimestamp) {
		return nil, false
	}
	return o.UnixTimestamp, true
}

// HasUnixTimestamp returns a boolean if a field has been set.
func (o *GetMiscTimestamp200Response) HasUnixTimestamp() bool {
	if o != nil && !IsNil(o.UnixTimestamp) {
		return true
	}

	return false
}

// SetUnixTimestamp gets a reference to the given int32 and assigns it to the UnixTimestamp field.
func (o *GetMiscTimestamp200Response) SetUnixTimestamp(v int32) {
	o.UnixTimestamp = &v
}

func (o GetMiscTimestamp200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscTimestamp200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DatetimeLocal) {
		toSerialize["datetime_local"] = o.DatetimeLocal
	}
	if !IsNil(o.DatetimeUtc) {
		toSerialize["datetime_utc"] = o.DatetimeUtc
	}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UnixTimestamp) {
		toSerialize["unix_timestamp"] = o.UnixTimestamp
	}
	return toSerialize, nil
}

type NullableGetMiscTimestamp200Response struct {
	value *GetMiscTimestamp200Response
	isSet bool
}

func (v NullableGetMiscTimestamp200Response) Get() *GetMiscTimestamp200Response {
	return v.value
}

func (v *NullableGetMiscTimestamp200Response) Set(val *GetMiscTimestamp200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscTimestamp200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscTimestamp200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscTimestamp200Response(val *GetMiscTimestamp200Response) *NullableGetMiscTimestamp200Response {
	return &NullableGetMiscTimestamp200Response{value: val, isSet: true}
}

func (v NullableGetMiscTimestamp200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscTimestamp200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


