/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostTranslateTextRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTranslateTextRequest{}

// PostTranslateTextRequest struct for PostTranslateTextRequest
type PostTranslateTextRequest struct {
	// 待翻译的文本内容。
	Text string `json:"text"`
}

type _PostTranslateTextRequest PostTranslateTextRequest

// NewPostTranslateTextRequest instantiates a new PostTranslateTextRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTranslateTextRequest(text string) *PostTranslateTextRequest {
	this := PostTranslateTextRequest{}
	this.Text = text
	return &this
}

// NewPostTranslateTextRequestWithDefaults instantiates a new PostTranslateTextRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTranslateTextRequestWithDefaults() *PostTranslateTextRequest {
	this := PostTranslateTextRequest{}
	return &this
}

// GetText returns the Text field value
func (o *PostTranslateTextRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PostTranslateTextRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PostTranslateTextRequest) SetText(v string) {
	o.Text = v
}

func (o PostTranslateTextRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTranslateTextRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *PostTranslateTextRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostTranslateTextRequest := _PostTranslateTextRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostTranslateTextRequest)

	if err != nil {
		return err
	}

	*o = PostTranslateTextRequest(varPostTranslateTextRequest)

	return err
}

type NullablePostTranslateTextRequest struct {
	value *PostTranslateTextRequest
	isSet bool
}

func (v NullablePostTranslateTextRequest) Get() *PostTranslateTextRequest {
	return v.value
}

func (v *NullablePostTranslateTextRequest) Set(val *PostTranslateTextRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTranslateTextRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTranslateTextRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTranslateTextRequest(val *PostTranslateTextRequest) *NullablePostTranslateTextRequest {
	return &NullablePostTranslateTextRequest{value: val, isSet: true}
}

func (v NullablePostTranslateTextRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTranslateTextRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


