/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscMovieBoxOffice200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscMovieBoxOffice200Response{}

// GetMiscMovieBoxOffice200Response struct for GetMiscMovieBoxOffice200Response
type GetMiscMovieBoxOffice200Response struct {
	// 影片排名列表
	List []GetMiscMovieBoxOffice200ResponseListInner `json:"list,omitempty"`
	Market *GetMiscMovieBoxOffice200ResponseMarket `json:"market,omitempty"`
	// 返回的影片数量
	TotalItems *int32 `json:"total_items,omitempty"`
	// 上游数据刷新间隔（秒）
	UpdateGapSeconds *int32 `json:"update_gap_seconds,omitempty"`
	// 数据更新时间的格式化字符串
	UpdateTime *string `json:"update_time,omitempty"`
	// 数据更新时间戳（毫秒）
	UpdatedAt *int32 `json:"updated_at,omitempty"`
}

// NewGetMiscMovieBoxOffice200Response instantiates a new GetMiscMovieBoxOffice200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscMovieBoxOffice200Response() *GetMiscMovieBoxOffice200Response {
	this := GetMiscMovieBoxOffice200Response{}
	return &this
}

// NewGetMiscMovieBoxOffice200ResponseWithDefaults instantiates a new GetMiscMovieBoxOffice200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscMovieBoxOffice200ResponseWithDefaults() *GetMiscMovieBoxOffice200Response {
	this := GetMiscMovieBoxOffice200Response{}
	return &this
}

// GetList returns the List field value if set, zero value otherwise.
func (o *GetMiscMovieBoxOffice200Response) GetList() []GetMiscMovieBoxOffice200ResponseListInner {
	if o == nil || IsNil(o.List) {
		var ret []GetMiscMovieBoxOffice200ResponseListInner
		return ret
	}
	return o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscMovieBoxOffice200Response) GetListOk() ([]GetMiscMovieBoxOffice200ResponseListInner, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *GetMiscMovieBoxOffice200Response) HasList() bool {
	if o != nil && !IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given []GetMiscMovieBoxOffice200ResponseListInner and assigns it to the List field.
func (o *GetMiscMovieBoxOffice200Response) SetList(v []GetMiscMovieBoxOffice200ResponseListInner) {
	o.List = v
}

// GetMarket returns the Market field value if set, zero value otherwise.
func (o *GetMiscMovieBoxOffice200Response) GetMarket() GetMiscMovieBoxOffice200ResponseMarket {
	if o == nil || IsNil(o.Market) {
		var ret GetMiscMovieBoxOffice200ResponseMarket
		return ret
	}
	return *o.Market
}

// GetMarketOk returns a tuple with the Market field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscMovieBoxOffice200Response) GetMarketOk() (*GetMiscMovieBoxOffice200ResponseMarket, bool) {
	if o == nil || IsNil(o.Market) {
		return nil, false
	}
	return o.Market, true
}

// HasMarket returns a boolean if a field has been set.
func (o *GetMiscMovieBoxOffice200Response) HasMarket() bool {
	if o != nil && !IsNil(o.Market) {
		return true
	}

	return false
}

// SetMarket gets a reference to the given GetMiscMovieBoxOffice200ResponseMarket and assigns it to the Market field.
func (o *GetMiscMovieBoxOffice200Response) SetMarket(v GetMiscMovieBoxOffice200ResponseMarket) {
	o.Market = &v
}

// GetTotalItems returns the TotalItems field value if set, zero value otherwise.
func (o *GetMiscMovieBoxOffice200Response) GetTotalItems() int32 {
	if o == nil || IsNil(o.TotalItems) {
		var ret int32
		return ret
	}
	return *o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscMovieBoxOffice200Response) GetTotalItemsOk() (*int32, bool) {
	if o == nil || IsNil(o.TotalItems) {
		return nil, false
	}
	return o.TotalItems, true
}

// HasTotalItems returns a boolean if a field has been set.
func (o *GetMiscMovieBoxOffice200Response) HasTotalItems() bool {
	if o != nil && !IsNil(o.TotalItems) {
		return true
	}

	return false
}

// SetTotalItems gets a reference to the given int32 and assigns it to the TotalItems field.
func (o *GetMiscMovieBoxOffice200Response) SetTotalItems(v int32) {
	o.TotalItems = &v
}

// GetUpdateGapSeconds returns the UpdateGapSeconds field value if set, zero value otherwise.
func (o *GetMiscMovieBoxOffice200Response) GetUpdateGapSeconds() int32 {
	if o == nil || IsNil(o.UpdateGapSeconds) {
		var ret int32
		return ret
	}
	return *o.UpdateGapSeconds
}

// GetUpdateGapSecondsOk returns a tuple with the UpdateGapSeconds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscMovieBoxOffice200Response) GetUpdateGapSecondsOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdateGapSeconds) {
		return nil, false
	}
	return o.UpdateGapSeconds, true
}

// HasUpdateGapSeconds returns a boolean if a field has been set.
func (o *GetMiscMovieBoxOffice200Response) HasUpdateGapSeconds() bool {
	if o != nil && !IsNil(o.UpdateGapSeconds) {
		return true
	}

	return false
}

// SetUpdateGapSeconds gets a reference to the given int32 and assigns it to the UpdateGapSeconds field.
func (o *GetMiscMovieBoxOffice200Response) SetUpdateGapSeconds(v int32) {
	o.UpdateGapSeconds = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *GetMiscMovieBoxOffice200Response) GetUpdateTime() string {
	if o == nil || IsNil(o.UpdateTime) {
		var ret string
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscMovieBoxOffice200Response) GetUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *GetMiscMovieBoxOffice200Response) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given string and assigns it to the UpdateTime field.
func (o *GetMiscMovieBoxOffice200Response) SetUpdateTime(v string) {
	o.UpdateTime = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetMiscMovieBoxOffice200Response) GetUpdatedAt() int32 {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret int32
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscMovieBoxOffice200Response) GetUpdatedAtOk() (*int32, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetMiscMovieBoxOffice200Response) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given int32 and assigns it to the UpdatedAt field.
func (o *GetMiscMovieBoxOffice200Response) SetUpdatedAt(v int32) {
	o.UpdatedAt = &v
}

func (o GetMiscMovieBoxOffice200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscMovieBoxOffice200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.List) {
		toSerialize["list"] = o.List
	}
	if !IsNil(o.Market) {
		toSerialize["market"] = o.Market
	}
	if !IsNil(o.TotalItems) {
		toSerialize["total_items"] = o.TotalItems
	}
	if !IsNil(o.UpdateGapSeconds) {
		toSerialize["update_gap_seconds"] = o.UpdateGapSeconds
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["update_time"] = o.UpdateTime
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	return toSerialize, nil
}

type NullableGetMiscMovieBoxOffice200Response struct {
	value *GetMiscMovieBoxOffice200Response
	isSet bool
}

func (v NullableGetMiscMovieBoxOffice200Response) Get() *GetMiscMovieBoxOffice200Response {
	return v.value
}

func (v *NullableGetMiscMovieBoxOffice200Response) Set(val *GetMiscMovieBoxOffice200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscMovieBoxOffice200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscMovieBoxOffice200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscMovieBoxOffice200Response(val *GetMiscMovieBoxOffice200Response) *NullableGetMiscMovieBoxOffice200Response {
	return &NullableGetMiscMovieBoxOffice200Response{value: val, isSet: true}
}

func (v NullableGetMiscMovieBoxOffice200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscMovieBoxOffice200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


