/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetNetworkPing200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkPing200Response{}

// GetNetworkPing200Response struct for GetNetworkPing200Response
type GetNetworkPing200Response struct {
	// 平均延迟(ms)
	Avg *float32 `json:"avg,omitempty"`
	Host *string `json:"host,omitempty"`
	Ip *string `json:"ip,omitempty"`
	Location *string `json:"location,omitempty"`
	// 最大延迟(ms)
	Max *float32 `json:"max,omitempty"`
	// 最小延迟(ms)
	Min *float32 `json:"min,omitempty"`
}

// NewGetNetworkPing200Response instantiates a new GetNetworkPing200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkPing200Response() *GetNetworkPing200Response {
	this := GetNetworkPing200Response{}
	return &this
}

// NewGetNetworkPing200ResponseWithDefaults instantiates a new GetNetworkPing200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkPing200ResponseWithDefaults() *GetNetworkPing200Response {
	this := GetNetworkPing200Response{}
	return &this
}

// GetAvg returns the Avg field value if set, zero value otherwise.
func (o *GetNetworkPing200Response) GetAvg() float32 {
	if o == nil || IsNil(o.Avg) {
		var ret float32
		return ret
	}
	return *o.Avg
}

// GetAvgOk returns a tuple with the Avg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing200Response) GetAvgOk() (*float32, bool) {
	if o == nil || IsNil(o.Avg) {
		return nil, false
	}
	return o.Avg, true
}

// HasAvg returns a boolean if a field has been set.
func (o *GetNetworkPing200Response) HasAvg() bool {
	if o != nil && !IsNil(o.Avg) {
		return true
	}

	return false
}

// SetAvg gets a reference to the given float32 and assigns it to the Avg field.
func (o *GetNetworkPing200Response) SetAvg(v float32) {
	o.Avg = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *GetNetworkPing200Response) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing200Response) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *GetNetworkPing200Response) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *GetNetworkPing200Response) SetHost(v string) {
	o.Host = &v
}

// GetIp returns the Ip field value if set, zero value otherwise.
func (o *GetNetworkPing200Response) GetIp() string {
	if o == nil || IsNil(o.Ip) {
		var ret string
		return ret
	}
	return *o.Ip
}

// GetIpOk returns a tuple with the Ip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing200Response) GetIpOk() (*string, bool) {
	if o == nil || IsNil(o.Ip) {
		return nil, false
	}
	return o.Ip, true
}

// HasIp returns a boolean if a field has been set.
func (o *GetNetworkPing200Response) HasIp() bool {
	if o != nil && !IsNil(o.Ip) {
		return true
	}

	return false
}

// SetIp gets a reference to the given string and assigns it to the Ip field.
func (o *GetNetworkPing200Response) SetIp(v string) {
	o.Ip = &v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *GetNetworkPing200Response) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing200Response) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *GetNetworkPing200Response) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *GetNetworkPing200Response) SetLocation(v string) {
	o.Location = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *GetNetworkPing200Response) GetMax() float32 {
	if o == nil || IsNil(o.Max) {
		var ret float32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing200Response) GetMaxOk() (*float32, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *GetNetworkPing200Response) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given float32 and assigns it to the Max field.
func (o *GetNetworkPing200Response) SetMax(v float32) {
	o.Max = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *GetNetworkPing200Response) GetMin() float32 {
	if o == nil || IsNil(o.Min) {
		var ret float32
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkPing200Response) GetMinOk() (*float32, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *GetNetworkPing200Response) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given float32 and assigns it to the Min field.
func (o *GetNetworkPing200Response) SetMin(v float32) {
	o.Min = &v
}

func (o GetNetworkPing200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkPing200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Avg) {
		toSerialize["avg"] = o.Avg
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	if !IsNil(o.Ip) {
		toSerialize["ip"] = o.Ip
	}
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	return toSerialize, nil
}

type NullableGetNetworkPing200Response struct {
	value *GetNetworkPing200Response
	isSet bool
}

func (v NullableGetNetworkPing200Response) Get() *GetNetworkPing200Response {
	return v.value
}

func (v *NullableGetNetworkPing200Response) Set(val *GetNetworkPing200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkPing200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkPing200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkPing200Response(val *GetNetworkPing200Response) *NullableGetNetworkPing200Response {
	return &NullableGetNetworkPing200Response{value: val, isSet: true}
}

func (v NullableGetNetworkPing200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkPing200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


