/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetSocialBilibiliUserinfo200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSocialBilibiliUserinfo200Response{}

// GetSocialBilibiliUserinfo200Response struct for GetSocialBilibiliUserinfo200Response
type GetSocialBilibiliUserinfo200Response struct {
	Mid *int32 `json:"mid,omitempty"`
	Name *string `json:"name,omitempty"`
	Sex *string `json:"sex,omitempty"`
	Face *string `json:"face,omitempty"`
	Sign *string `json:"sign,omitempty"`
	Level *int32 `json:"level,omitempty"`
	Birthday *string `json:"birthday,omitempty"`
	VipType *int32 `json:"vip_type,omitempty"`
	VipStatus *int32 `json:"vip_status,omitempty"`
	Following *int32 `json:"following,omitempty"`
	Follower *int32 `json:"follower,omitempty"`
	ArchiveCount *int32 `json:"archive_count,omitempty"`
	ArticleCount *int32 `json:"article_count,omitempty"`
}

// NewGetSocialBilibiliUserinfo200Response instantiates a new GetSocialBilibiliUserinfo200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSocialBilibiliUserinfo200Response() *GetSocialBilibiliUserinfo200Response {
	this := GetSocialBilibiliUserinfo200Response{}
	return &this
}

// NewGetSocialBilibiliUserinfo200ResponseWithDefaults instantiates a new GetSocialBilibiliUserinfo200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSocialBilibiliUserinfo200ResponseWithDefaults() *GetSocialBilibiliUserinfo200Response {
	this := GetSocialBilibiliUserinfo200Response{}
	return &this
}

// GetMid returns the Mid field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetMid() int32 {
	if o == nil || IsNil(o.Mid) {
		var ret int32
		return ret
	}
	return *o.Mid
}

// GetMidOk returns a tuple with the Mid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetMidOk() (*int32, bool) {
	if o == nil || IsNil(o.Mid) {
		return nil, false
	}
	return o.Mid, true
}

// HasMid returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasMid() bool {
	if o != nil && !IsNil(o.Mid) {
		return true
	}

	return false
}

// SetMid gets a reference to the given int32 and assigns it to the Mid field.
func (o *GetSocialBilibiliUserinfo200Response) SetMid(v int32) {
	o.Mid = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetSocialBilibiliUserinfo200Response) SetName(v string) {
	o.Name = &v
}

// GetSex returns the Sex field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetSex() string {
	if o == nil || IsNil(o.Sex) {
		var ret string
		return ret
	}
	return *o.Sex
}

// GetSexOk returns a tuple with the Sex field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetSexOk() (*string, bool) {
	if o == nil || IsNil(o.Sex) {
		return nil, false
	}
	return o.Sex, true
}

// HasSex returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasSex() bool {
	if o != nil && !IsNil(o.Sex) {
		return true
	}

	return false
}

// SetSex gets a reference to the given string and assigns it to the Sex field.
func (o *GetSocialBilibiliUserinfo200Response) SetSex(v string) {
	o.Sex = &v
}

// GetFace returns the Face field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetFace() string {
	if o == nil || IsNil(o.Face) {
		var ret string
		return ret
	}
	return *o.Face
}

// GetFaceOk returns a tuple with the Face field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetFaceOk() (*string, bool) {
	if o == nil || IsNil(o.Face) {
		return nil, false
	}
	return o.Face, true
}

// HasFace returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasFace() bool {
	if o != nil && !IsNil(o.Face) {
		return true
	}

	return false
}

// SetFace gets a reference to the given string and assigns it to the Face field.
func (o *GetSocialBilibiliUserinfo200Response) SetFace(v string) {
	o.Face = &v
}

// GetSign returns the Sign field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetSign() string {
	if o == nil || IsNil(o.Sign) {
		var ret string
		return ret
	}
	return *o.Sign
}

// GetSignOk returns a tuple with the Sign field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetSignOk() (*string, bool) {
	if o == nil || IsNil(o.Sign) {
		return nil, false
	}
	return o.Sign, true
}

// HasSign returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasSign() bool {
	if o != nil && !IsNil(o.Sign) {
		return true
	}

	return false
}

// SetSign gets a reference to the given string and assigns it to the Sign field.
func (o *GetSocialBilibiliUserinfo200Response) SetSign(v string) {
	o.Sign = &v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetLevel() int32 {
	if o == nil || IsNil(o.Level) {
		var ret int32
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetLevelOk() (*int32, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given int32 and assigns it to the Level field.
func (o *GetSocialBilibiliUserinfo200Response) SetLevel(v int32) {
	o.Level = &v
}

// GetBirthday returns the Birthday field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetBirthday() string {
	if o == nil || IsNil(o.Birthday) {
		var ret string
		return ret
	}
	return *o.Birthday
}

// GetBirthdayOk returns a tuple with the Birthday field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetBirthdayOk() (*string, bool) {
	if o == nil || IsNil(o.Birthday) {
		return nil, false
	}
	return o.Birthday, true
}

// HasBirthday returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasBirthday() bool {
	if o != nil && !IsNil(o.Birthday) {
		return true
	}

	return false
}

// SetBirthday gets a reference to the given string and assigns it to the Birthday field.
func (o *GetSocialBilibiliUserinfo200Response) SetBirthday(v string) {
	o.Birthday = &v
}

// GetVipType returns the VipType field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetVipType() int32 {
	if o == nil || IsNil(o.VipType) {
		var ret int32
		return ret
	}
	return *o.VipType
}

// GetVipTypeOk returns a tuple with the VipType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetVipTypeOk() (*int32, bool) {
	if o == nil || IsNil(o.VipType) {
		return nil, false
	}
	return o.VipType, true
}

// HasVipType returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasVipType() bool {
	if o != nil && !IsNil(o.VipType) {
		return true
	}

	return false
}

// SetVipType gets a reference to the given int32 and assigns it to the VipType field.
func (o *GetSocialBilibiliUserinfo200Response) SetVipType(v int32) {
	o.VipType = &v
}

// GetVipStatus returns the VipStatus field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetVipStatus() int32 {
	if o == nil || IsNil(o.VipStatus) {
		var ret int32
		return ret
	}
	return *o.VipStatus
}

// GetVipStatusOk returns a tuple with the VipStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetVipStatusOk() (*int32, bool) {
	if o == nil || IsNil(o.VipStatus) {
		return nil, false
	}
	return o.VipStatus, true
}

// HasVipStatus returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasVipStatus() bool {
	if o != nil && !IsNil(o.VipStatus) {
		return true
	}

	return false
}

// SetVipStatus gets a reference to the given int32 and assigns it to the VipStatus field.
func (o *GetSocialBilibiliUserinfo200Response) SetVipStatus(v int32) {
	o.VipStatus = &v
}

// GetFollowing returns the Following field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetFollowing() int32 {
	if o == nil || IsNil(o.Following) {
		var ret int32
		return ret
	}
	return *o.Following
}

// GetFollowingOk returns a tuple with the Following field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetFollowingOk() (*int32, bool) {
	if o == nil || IsNil(o.Following) {
		return nil, false
	}
	return o.Following, true
}

// HasFollowing returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasFollowing() bool {
	if o != nil && !IsNil(o.Following) {
		return true
	}

	return false
}

// SetFollowing gets a reference to the given int32 and assigns it to the Following field.
func (o *GetSocialBilibiliUserinfo200Response) SetFollowing(v int32) {
	o.Following = &v
}

// GetFollower returns the Follower field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetFollower() int32 {
	if o == nil || IsNil(o.Follower) {
		var ret int32
		return ret
	}
	return *o.Follower
}

// GetFollowerOk returns a tuple with the Follower field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetFollowerOk() (*int32, bool) {
	if o == nil || IsNil(o.Follower) {
		return nil, false
	}
	return o.Follower, true
}

// HasFollower returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasFollower() bool {
	if o != nil && !IsNil(o.Follower) {
		return true
	}

	return false
}

// SetFollower gets a reference to the given int32 and assigns it to the Follower field.
func (o *GetSocialBilibiliUserinfo200Response) SetFollower(v int32) {
	o.Follower = &v
}

// GetArchiveCount returns the ArchiveCount field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetArchiveCount() int32 {
	if o == nil || IsNil(o.ArchiveCount) {
		var ret int32
		return ret
	}
	return *o.ArchiveCount
}

// GetArchiveCountOk returns a tuple with the ArchiveCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetArchiveCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ArchiveCount) {
		return nil, false
	}
	return o.ArchiveCount, true
}

// HasArchiveCount returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasArchiveCount() bool {
	if o != nil && !IsNil(o.ArchiveCount) {
		return true
	}

	return false
}

// SetArchiveCount gets a reference to the given int32 and assigns it to the ArchiveCount field.
func (o *GetSocialBilibiliUserinfo200Response) SetArchiveCount(v int32) {
	o.ArchiveCount = &v
}

// GetArticleCount returns the ArticleCount field value if set, zero value otherwise.
func (o *GetSocialBilibiliUserinfo200Response) GetArticleCount() int32 {
	if o == nil || IsNil(o.ArticleCount) {
		var ret int32
		return ret
	}
	return *o.ArticleCount
}

// GetArticleCountOk returns a tuple with the ArticleCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliUserinfo200Response) GetArticleCountOk() (*int32, bool) {
	if o == nil || IsNil(o.ArticleCount) {
		return nil, false
	}
	return o.ArticleCount, true
}

// HasArticleCount returns a boolean if a field has been set.
func (o *GetSocialBilibiliUserinfo200Response) HasArticleCount() bool {
	if o != nil && !IsNil(o.ArticleCount) {
		return true
	}

	return false
}

// SetArticleCount gets a reference to the given int32 and assigns it to the ArticleCount field.
func (o *GetSocialBilibiliUserinfo200Response) SetArticleCount(v int32) {
	o.ArticleCount = &v
}

func (o GetSocialBilibiliUserinfo200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSocialBilibiliUserinfo200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Mid) {
		toSerialize["mid"] = o.Mid
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Sex) {
		toSerialize["sex"] = o.Sex
	}
	if !IsNil(o.Face) {
		toSerialize["face"] = o.Face
	}
	if !IsNil(o.Sign) {
		toSerialize["sign"] = o.Sign
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Birthday) {
		toSerialize["birthday"] = o.Birthday
	}
	if !IsNil(o.VipType) {
		toSerialize["vip_type"] = o.VipType
	}
	if !IsNil(o.VipStatus) {
		toSerialize["vip_status"] = o.VipStatus
	}
	if !IsNil(o.Following) {
		toSerialize["following"] = o.Following
	}
	if !IsNil(o.Follower) {
		toSerialize["follower"] = o.Follower
	}
	if !IsNil(o.ArchiveCount) {
		toSerialize["archive_count"] = o.ArchiveCount
	}
	if !IsNil(o.ArticleCount) {
		toSerialize["article_count"] = o.ArticleCount
	}
	return toSerialize, nil
}

type NullableGetSocialBilibiliUserinfo200Response struct {
	value *GetSocialBilibiliUserinfo200Response
	isSet bool
}

func (v NullableGetSocialBilibiliUserinfo200Response) Get() *GetSocialBilibiliUserinfo200Response {
	return v.value
}

func (v *NullableGetSocialBilibiliUserinfo200Response) Set(val *GetSocialBilibiliUserinfo200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSocialBilibiliUserinfo200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSocialBilibiliUserinfo200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSocialBilibiliUserinfo200Response(val *GetSocialBilibiliUserinfo200Response) *NullableGetSocialBilibiliUserinfo200Response {
	return &NullableGetSocialBilibiliUserinfo200Response{value: val, isSet: true}
}

func (v NullableGetSocialBilibiliUserinfo200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSocialBilibiliUserinfo200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


