/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetSocialBilibiliVideoinfo200ResponseStat type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSocialBilibiliVideoinfo200ResponseStat{}

// GetSocialBilibiliVideoinfo200ResponseStat 视频的核心数据统计。
type GetSocialBilibiliVideoinfo200ResponseStat struct {
	// 播放数。
	View *float32 `json:"view,omitempty"`
	// 弹幕数。
	Danmaku *float32 `json:"danmaku,omitempty"`
	// 评论数。
	Reply *float32 `json:"reply,omitempty"`
	// 收藏数。
	Favorite *float32 `json:"favorite,omitempty"`
	// 投币数。
	Coin *float32 `json:"coin,omitempty"`
	// 分享数。
	Share *float32 `json:"share,omitempty"`
	// 获赞数。
	Like *float32 `json:"like,omitempty"`
}

// NewGetSocialBilibiliVideoinfo200ResponseStat instantiates a new GetSocialBilibiliVideoinfo200ResponseStat object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSocialBilibiliVideoinfo200ResponseStat() *GetSocialBilibiliVideoinfo200ResponseStat {
	this := GetSocialBilibiliVideoinfo200ResponseStat{}
	return &this
}

// NewGetSocialBilibiliVideoinfo200ResponseStatWithDefaults instantiates a new GetSocialBilibiliVideoinfo200ResponseStat object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSocialBilibiliVideoinfo200ResponseStatWithDefaults() *GetSocialBilibiliVideoinfo200ResponseStat {
	this := GetSocialBilibiliVideoinfo200ResponseStat{}
	return &this
}

// GetView returns the View field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetView() float32 {
	if o == nil || IsNil(o.View) {
		var ret float32
		return ret
	}
	return *o.View
}

// GetViewOk returns a tuple with the View field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetViewOk() (*float32, bool) {
	if o == nil || IsNil(o.View) {
		return nil, false
	}
	return o.View, true
}

// HasView returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) HasView() bool {
	if o != nil && !IsNil(o.View) {
		return true
	}

	return false
}

// SetView gets a reference to the given float32 and assigns it to the View field.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) SetView(v float32) {
	o.View = &v
}

// GetDanmaku returns the Danmaku field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetDanmaku() float32 {
	if o == nil || IsNil(o.Danmaku) {
		var ret float32
		return ret
	}
	return *o.Danmaku
}

// GetDanmakuOk returns a tuple with the Danmaku field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetDanmakuOk() (*float32, bool) {
	if o == nil || IsNil(o.Danmaku) {
		return nil, false
	}
	return o.Danmaku, true
}

// HasDanmaku returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) HasDanmaku() bool {
	if o != nil && !IsNil(o.Danmaku) {
		return true
	}

	return false
}

// SetDanmaku gets a reference to the given float32 and assigns it to the Danmaku field.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) SetDanmaku(v float32) {
	o.Danmaku = &v
}

// GetReply returns the Reply field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetReply() float32 {
	if o == nil || IsNil(o.Reply) {
		var ret float32
		return ret
	}
	return *o.Reply
}

// GetReplyOk returns a tuple with the Reply field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetReplyOk() (*float32, bool) {
	if o == nil || IsNil(o.Reply) {
		return nil, false
	}
	return o.Reply, true
}

// HasReply returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) HasReply() bool {
	if o != nil && !IsNil(o.Reply) {
		return true
	}

	return false
}

// SetReply gets a reference to the given float32 and assigns it to the Reply field.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) SetReply(v float32) {
	o.Reply = &v
}

// GetFavorite returns the Favorite field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetFavorite() float32 {
	if o == nil || IsNil(o.Favorite) {
		var ret float32
		return ret
	}
	return *o.Favorite
}

// GetFavoriteOk returns a tuple with the Favorite field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetFavoriteOk() (*float32, bool) {
	if o == nil || IsNil(o.Favorite) {
		return nil, false
	}
	return o.Favorite, true
}

// HasFavorite returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) HasFavorite() bool {
	if o != nil && !IsNil(o.Favorite) {
		return true
	}

	return false
}

// SetFavorite gets a reference to the given float32 and assigns it to the Favorite field.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) SetFavorite(v float32) {
	o.Favorite = &v
}

// GetCoin returns the Coin field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetCoin() float32 {
	if o == nil || IsNil(o.Coin) {
		var ret float32
		return ret
	}
	return *o.Coin
}

// GetCoinOk returns a tuple with the Coin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetCoinOk() (*float32, bool) {
	if o == nil || IsNil(o.Coin) {
		return nil, false
	}
	return o.Coin, true
}

// HasCoin returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) HasCoin() bool {
	if o != nil && !IsNil(o.Coin) {
		return true
	}

	return false
}

// SetCoin gets a reference to the given float32 and assigns it to the Coin field.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) SetCoin(v float32) {
	o.Coin = &v
}

// GetShare returns the Share field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetShare() float32 {
	if o == nil || IsNil(o.Share) {
		var ret float32
		return ret
	}
	return *o.Share
}

// GetShareOk returns a tuple with the Share field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetShareOk() (*float32, bool) {
	if o == nil || IsNil(o.Share) {
		return nil, false
	}
	return o.Share, true
}

// HasShare returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) HasShare() bool {
	if o != nil && !IsNil(o.Share) {
		return true
	}

	return false
}

// SetShare gets a reference to the given float32 and assigns it to the Share field.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) SetShare(v float32) {
	o.Share = &v
}

// GetLike returns the Like field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetLike() float32 {
	if o == nil || IsNil(o.Like) {
		var ret float32
		return ret
	}
	return *o.Like
}

// GetLikeOk returns a tuple with the Like field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) GetLikeOk() (*float32, bool) {
	if o == nil || IsNil(o.Like) {
		return nil, false
	}
	return o.Like, true
}

// HasLike returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) HasLike() bool {
	if o != nil && !IsNil(o.Like) {
		return true
	}

	return false
}

// SetLike gets a reference to the given float32 and assigns it to the Like field.
func (o *GetSocialBilibiliVideoinfo200ResponseStat) SetLike(v float32) {
	o.Like = &v
}

func (o GetSocialBilibiliVideoinfo200ResponseStat) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSocialBilibiliVideoinfo200ResponseStat) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.View) {
		toSerialize["view"] = o.View
	}
	if !IsNil(o.Danmaku) {
		toSerialize["danmaku"] = o.Danmaku
	}
	if !IsNil(o.Reply) {
		toSerialize["reply"] = o.Reply
	}
	if !IsNil(o.Favorite) {
		toSerialize["favorite"] = o.Favorite
	}
	if !IsNil(o.Coin) {
		toSerialize["coin"] = o.Coin
	}
	if !IsNil(o.Share) {
		toSerialize["share"] = o.Share
	}
	if !IsNil(o.Like) {
		toSerialize["like"] = o.Like
	}
	return toSerialize, nil
}

type NullableGetSocialBilibiliVideoinfo200ResponseStat struct {
	value *GetSocialBilibiliVideoinfo200ResponseStat
	isSet bool
}

func (v NullableGetSocialBilibiliVideoinfo200ResponseStat) Get() *GetSocialBilibiliVideoinfo200ResponseStat {
	return v.value
}

func (v *NullableGetSocialBilibiliVideoinfo200ResponseStat) Set(val *GetSocialBilibiliVideoinfo200ResponseStat) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSocialBilibiliVideoinfo200ResponseStat) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSocialBilibiliVideoinfo200ResponseStat) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSocialBilibiliVideoinfo200ResponseStat(val *GetSocialBilibiliVideoinfo200ResponseStat) *NullableGetSocialBilibiliVideoinfo200ResponseStat {
	return &NullableGetSocialBilibiliVideoinfo200ResponseStat{value: val, isSet: true}
}

func (v NullableGetSocialBilibiliVideoinfo200ResponseStat) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSocialBilibiliVideoinfo200ResponseStat) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


