/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscWeather200ResponseMinutelyPrecipDataInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscWeather200ResponseMinutelyPrecipDataInner{}

// GetMiscWeather200ResponseMinutelyPrecipDataInner struct for GetMiscWeather200ResponseMinutelyPrecipDataInner
type GetMiscWeather200ResponseMinutelyPrecipDataInner struct {
	// 预报时间 ISO8601
	Time *string `json:"time,omitempty"`
	// 5分钟累计降水量 mm
	Precip *float32 `json:"precip,omitempty"`
	// 降水类型：rain / snow
	Type *string `json:"type,omitempty"`
}

// NewGetMiscWeather200ResponseMinutelyPrecipDataInner instantiates a new GetMiscWeather200ResponseMinutelyPrecipDataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscWeather200ResponseMinutelyPrecipDataInner() *GetMiscWeather200ResponseMinutelyPrecipDataInner {
	this := GetMiscWeather200ResponseMinutelyPrecipDataInner{}
	return &this
}

// NewGetMiscWeather200ResponseMinutelyPrecipDataInnerWithDefaults instantiates a new GetMiscWeather200ResponseMinutelyPrecipDataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscWeather200ResponseMinutelyPrecipDataInnerWithDefaults() *GetMiscWeather200ResponseMinutelyPrecipDataInner {
	this := GetMiscWeather200ResponseMinutelyPrecipDataInner{}
	return &this
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) GetTime() string {
	if o == nil || IsNil(o.Time) {
		var ret string
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) GetTimeOk() (*string, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given string and assigns it to the Time field.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) SetTime(v string) {
	o.Time = &v
}

// GetPrecip returns the Precip field value if set, zero value otherwise.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) GetPrecip() float32 {
	if o == nil || IsNil(o.Precip) {
		var ret float32
		return ret
	}
	return *o.Precip
}

// GetPrecipOk returns a tuple with the Precip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) GetPrecipOk() (*float32, bool) {
	if o == nil || IsNil(o.Precip) {
		return nil, false
	}
	return o.Precip, true
}

// HasPrecip returns a boolean if a field has been set.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) HasPrecip() bool {
	if o != nil && !IsNil(o.Precip) {
		return true
	}

	return false
}

// SetPrecip gets a reference to the given float32 and assigns it to the Precip field.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) SetPrecip(v float32) {
	o.Precip = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetMiscWeather200ResponseMinutelyPrecipDataInner) SetType(v string) {
	o.Type = &v
}

func (o GetMiscWeather200ResponseMinutelyPrecipDataInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscWeather200ResponseMinutelyPrecipDataInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Precip) {
		toSerialize["precip"] = o.Precip
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableGetMiscWeather200ResponseMinutelyPrecipDataInner struct {
	value *GetMiscWeather200ResponseMinutelyPrecipDataInner
	isSet bool
}

func (v NullableGetMiscWeather200ResponseMinutelyPrecipDataInner) Get() *GetMiscWeather200ResponseMinutelyPrecipDataInner {
	return v.value
}

func (v *NullableGetMiscWeather200ResponseMinutelyPrecipDataInner) Set(val *GetMiscWeather200ResponseMinutelyPrecipDataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscWeather200ResponseMinutelyPrecipDataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscWeather200ResponseMinutelyPrecipDataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscWeather200ResponseMinutelyPrecipDataInner(val *GetMiscWeather200ResponseMinutelyPrecipDataInner) *NullableGetMiscWeather200ResponseMinutelyPrecipDataInner {
	return &NullableGetMiscWeather200ResponseMinutelyPrecipDataInner{value: val, isSet: true}
}

func (v NullableGetMiscWeather200ResponseMinutelyPrecipDataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscWeather200ResponseMinutelyPrecipDataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


