/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetWebTomarkdownAsyncStatus404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWebTomarkdownAsyncStatus404Response{}

// GetWebTomarkdownAsyncStatus404Response struct for GetWebTomarkdownAsyncStatus404Response
type GetWebTomarkdownAsyncStatus404Response struct {
	Error *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
	Code *int32 `json:"code,omitempty"`
}

// NewGetWebTomarkdownAsyncStatus404Response instantiates a new GetWebTomarkdownAsyncStatus404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWebTomarkdownAsyncStatus404Response() *GetWebTomarkdownAsyncStatus404Response {
	this := GetWebTomarkdownAsyncStatus404Response{}
	return &this
}

// NewGetWebTomarkdownAsyncStatus404ResponseWithDefaults instantiates a new GetWebTomarkdownAsyncStatus404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWebTomarkdownAsyncStatus404ResponseWithDefaults() *GetWebTomarkdownAsyncStatus404Response {
	this := GetWebTomarkdownAsyncStatus404Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus404Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus404Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus404Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetWebTomarkdownAsyncStatus404Response) SetError(v string) {
	o.Error = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetWebTomarkdownAsyncStatus404Response) SetMessage(v string) {
	o.Message = &v
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetWebTomarkdownAsyncStatus404Response) GetCode() int32 {
	if o == nil || IsNil(o.Code) {
		var ret int32
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebTomarkdownAsyncStatus404Response) GetCodeOk() (*int32, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetWebTomarkdownAsyncStatus404Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given int32 and assigns it to the Code field.
func (o *GetWebTomarkdownAsyncStatus404Response) SetCode(v int32) {
	o.Code = &v
}

func (o GetWebTomarkdownAsyncStatus404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWebTomarkdownAsyncStatus404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	return toSerialize, nil
}

type NullableGetWebTomarkdownAsyncStatus404Response struct {
	value *GetWebTomarkdownAsyncStatus404Response
	isSet bool
}

func (v NullableGetWebTomarkdownAsyncStatus404Response) Get() *GetWebTomarkdownAsyncStatus404Response {
	return v.value
}

func (v *NullableGetWebTomarkdownAsyncStatus404Response) Set(val *GetWebTomarkdownAsyncStatus404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebTomarkdownAsyncStatus404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebTomarkdownAsyncStatus404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebTomarkdownAsyncStatus404Response(val *GetWebTomarkdownAsyncStatus404Response) *NullableGetWebTomarkdownAsyncStatus404Response {
	return &NullableGetWebTomarkdownAsyncStatus404Response{value: val, isSet: true}
}

func (v NullableGetWebTomarkdownAsyncStatus404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebTomarkdownAsyncStatus404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


