/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the EndpointsAggregate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EndpointsAggregate{}

// EndpointsAggregate struct for EndpointsAggregate
type EndpointsAggregate struct {
	Endpoints []EndpointsAggregateEndpointsInner `json:"endpoints,omitempty"`
	Unaggregated *EndpointsAggregateUnaggregated `json:"unaggregated,omitempty"`
}

// NewEndpointsAggregate instantiates a new EndpointsAggregate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEndpointsAggregate() *EndpointsAggregate {
	this := EndpointsAggregate{}
	return &this
}

// NewEndpointsAggregateWithDefaults instantiates a new EndpointsAggregate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEndpointsAggregateWithDefaults() *EndpointsAggregate {
	this := EndpointsAggregate{}
	return &this
}

// GetEndpoints returns the Endpoints field value if set, zero value otherwise.
func (o *EndpointsAggregate) GetEndpoints() []EndpointsAggregateEndpointsInner {
	if o == nil || IsNil(o.Endpoints) {
		var ret []EndpointsAggregateEndpointsInner
		return ret
	}
	return o.Endpoints
}

// GetEndpointsOk returns a tuple with the Endpoints field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsAggregate) GetEndpointsOk() ([]EndpointsAggregateEndpointsInner, bool) {
	if o == nil || IsNil(o.Endpoints) {
		return nil, false
	}
	return o.Endpoints, true
}

// HasEndpoints returns a boolean if a field has been set.
func (o *EndpointsAggregate) HasEndpoints() bool {
	if o != nil && !IsNil(o.Endpoints) {
		return true
	}

	return false
}

// SetEndpoints gets a reference to the given []EndpointsAggregateEndpointsInner and assigns it to the Endpoints field.
func (o *EndpointsAggregate) SetEndpoints(v []EndpointsAggregateEndpointsInner) {
	o.Endpoints = v
}

// GetUnaggregated returns the Unaggregated field value if set, zero value otherwise.
func (o *EndpointsAggregate) GetUnaggregated() EndpointsAggregateUnaggregated {
	if o == nil || IsNil(o.Unaggregated) {
		var ret EndpointsAggregateUnaggregated
		return ret
	}
	return *o.Unaggregated
}

// GetUnaggregatedOk returns a tuple with the Unaggregated field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EndpointsAggregate) GetUnaggregatedOk() (*EndpointsAggregateUnaggregated, bool) {
	if o == nil || IsNil(o.Unaggregated) {
		return nil, false
	}
	return o.Unaggregated, true
}

// HasUnaggregated returns a boolean if a field has been set.
func (o *EndpointsAggregate) HasUnaggregated() bool {
	if o != nil && !IsNil(o.Unaggregated) {
		return true
	}

	return false
}

// SetUnaggregated gets a reference to the given EndpointsAggregateUnaggregated and assigns it to the Unaggregated field.
func (o *EndpointsAggregate) SetUnaggregated(v EndpointsAggregateUnaggregated) {
	o.Unaggregated = &v
}

func (o EndpointsAggregate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EndpointsAggregate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Endpoints) {
		toSerialize["endpoints"] = o.Endpoints
	}
	if !IsNil(o.Unaggregated) {
		toSerialize["unaggregated"] = o.Unaggregated
	}
	return toSerialize, nil
}

type NullableEndpointsAggregate struct {
	value *EndpointsAggregate
	isSet bool
}

func (v NullableEndpointsAggregate) Get() *EndpointsAggregate {
	return v.value
}

func (v *NullableEndpointsAggregate) Set(val *EndpointsAggregate) {
	v.value = val
	v.isSet = true
}

func (v NullableEndpointsAggregate) IsSet() bool {
	return v.isSet
}

func (v *NullableEndpointsAggregate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEndpointsAggregate(val *EndpointsAggregate) *NullableEndpointsAggregate {
	return &NullableEndpointsAggregate{value: val, isSet: true}
}

func (v NullableEndpointsAggregate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEndpointsAggregate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


