/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetWebparseMetadata200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWebparseMetadata200Response{}

// GetWebparseMetadata200Response struct for GetWebparseMetadata200Response
type GetWebparseMetadata200Response struct {
	PageUrl *string `json:"page_url,omitempty"`
	Title *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Keywords []string `json:"keywords,omitempty"`
	FaviconUrl *string `json:"favicon_url,omitempty"`
	Language *string `json:"language,omitempty"`
	Author *string `json:"author,omitempty"`
	PublishedTime *string `json:"published_time,omitempty"`
	CanonicalUrl *string `json:"canonical_url,omitempty"`
	Generator *string `json:"generator,omitempty"`
	OpenGraph map[string]interface{} `json:"open_graph,omitempty"`
}

// NewGetWebparseMetadata200Response instantiates a new GetWebparseMetadata200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWebparseMetadata200Response() *GetWebparseMetadata200Response {
	this := GetWebparseMetadata200Response{}
	return &this
}

// NewGetWebparseMetadata200ResponseWithDefaults instantiates a new GetWebparseMetadata200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWebparseMetadata200ResponseWithDefaults() *GetWebparseMetadata200Response {
	this := GetWebparseMetadata200Response{}
	return &this
}

// GetPageUrl returns the PageUrl field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetPageUrl() string {
	if o == nil || IsNil(o.PageUrl) {
		var ret string
		return ret
	}
	return *o.PageUrl
}

// GetPageUrlOk returns a tuple with the PageUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetPageUrlOk() (*string, bool) {
	if o == nil || IsNil(o.PageUrl) {
		return nil, false
	}
	return o.PageUrl, true
}

// HasPageUrl returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasPageUrl() bool {
	if o != nil && !IsNil(o.PageUrl) {
		return true
	}

	return false
}

// SetPageUrl gets a reference to the given string and assigns it to the PageUrl field.
func (o *GetWebparseMetadata200Response) SetPageUrl(v string) {
	o.PageUrl = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *GetWebparseMetadata200Response) SetTitle(v string) {
	o.Title = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetWebparseMetadata200Response) SetDescription(v string) {
	o.Description = &v
}

// GetKeywords returns the Keywords field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetKeywords() []string {
	if o == nil || IsNil(o.Keywords) {
		var ret []string
		return ret
	}
	return o.Keywords
}

// GetKeywordsOk returns a tuple with the Keywords field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetKeywordsOk() ([]string, bool) {
	if o == nil || IsNil(o.Keywords) {
		return nil, false
	}
	return o.Keywords, true
}

// HasKeywords returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasKeywords() bool {
	if o != nil && !IsNil(o.Keywords) {
		return true
	}

	return false
}

// SetKeywords gets a reference to the given []string and assigns it to the Keywords field.
func (o *GetWebparseMetadata200Response) SetKeywords(v []string) {
	o.Keywords = v
}

// GetFaviconUrl returns the FaviconUrl field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetFaviconUrl() string {
	if o == nil || IsNil(o.FaviconUrl) {
		var ret string
		return ret
	}
	return *o.FaviconUrl
}

// GetFaviconUrlOk returns a tuple with the FaviconUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetFaviconUrlOk() (*string, bool) {
	if o == nil || IsNil(o.FaviconUrl) {
		return nil, false
	}
	return o.FaviconUrl, true
}

// HasFaviconUrl returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasFaviconUrl() bool {
	if o != nil && !IsNil(o.FaviconUrl) {
		return true
	}

	return false
}

// SetFaviconUrl gets a reference to the given string and assigns it to the FaviconUrl field.
func (o *GetWebparseMetadata200Response) SetFaviconUrl(v string) {
	o.FaviconUrl = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *GetWebparseMetadata200Response) SetLanguage(v string) {
	o.Language = &v
}

// GetAuthor returns the Author field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetAuthor() string {
	if o == nil || IsNil(o.Author) {
		var ret string
		return ret
	}
	return *o.Author
}

// GetAuthorOk returns a tuple with the Author field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetAuthorOk() (*string, bool) {
	if o == nil || IsNil(o.Author) {
		return nil, false
	}
	return o.Author, true
}

// HasAuthor returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasAuthor() bool {
	if o != nil && !IsNil(o.Author) {
		return true
	}

	return false
}

// SetAuthor gets a reference to the given string and assigns it to the Author field.
func (o *GetWebparseMetadata200Response) SetAuthor(v string) {
	o.Author = &v
}

// GetPublishedTime returns the PublishedTime field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetPublishedTime() string {
	if o == nil || IsNil(o.PublishedTime) {
		var ret string
		return ret
	}
	return *o.PublishedTime
}

// GetPublishedTimeOk returns a tuple with the PublishedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetPublishedTimeOk() (*string, bool) {
	if o == nil || IsNil(o.PublishedTime) {
		return nil, false
	}
	return o.PublishedTime, true
}

// HasPublishedTime returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasPublishedTime() bool {
	if o != nil && !IsNil(o.PublishedTime) {
		return true
	}

	return false
}

// SetPublishedTime gets a reference to the given string and assigns it to the PublishedTime field.
func (o *GetWebparseMetadata200Response) SetPublishedTime(v string) {
	o.PublishedTime = &v
}

// GetCanonicalUrl returns the CanonicalUrl field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetCanonicalUrl() string {
	if o == nil || IsNil(o.CanonicalUrl) {
		var ret string
		return ret
	}
	return *o.CanonicalUrl
}

// GetCanonicalUrlOk returns a tuple with the CanonicalUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetCanonicalUrlOk() (*string, bool) {
	if o == nil || IsNil(o.CanonicalUrl) {
		return nil, false
	}
	return o.CanonicalUrl, true
}

// HasCanonicalUrl returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasCanonicalUrl() bool {
	if o != nil && !IsNil(o.CanonicalUrl) {
		return true
	}

	return false
}

// SetCanonicalUrl gets a reference to the given string and assigns it to the CanonicalUrl field.
func (o *GetWebparseMetadata200Response) SetCanonicalUrl(v string) {
	o.CanonicalUrl = &v
}

// GetGenerator returns the Generator field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetGenerator() string {
	if o == nil || IsNil(o.Generator) {
		var ret string
		return ret
	}
	return *o.Generator
}

// GetGeneratorOk returns a tuple with the Generator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetGeneratorOk() (*string, bool) {
	if o == nil || IsNil(o.Generator) {
		return nil, false
	}
	return o.Generator, true
}

// HasGenerator returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasGenerator() bool {
	if o != nil && !IsNil(o.Generator) {
		return true
	}

	return false
}

// SetGenerator gets a reference to the given string and assigns it to the Generator field.
func (o *GetWebparseMetadata200Response) SetGenerator(v string) {
	o.Generator = &v
}

// GetOpenGraph returns the OpenGraph field value if set, zero value otherwise.
func (o *GetWebparseMetadata200Response) GetOpenGraph() map[string]interface{} {
	if o == nil || IsNil(o.OpenGraph) {
		var ret map[string]interface{}
		return ret
	}
	return o.OpenGraph
}

// GetOpenGraphOk returns a tuple with the OpenGraph field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetWebparseMetadata200Response) GetOpenGraphOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.OpenGraph) {
		return map[string]interface{}{}, false
	}
	return o.OpenGraph, true
}

// HasOpenGraph returns a boolean if a field has been set.
func (o *GetWebparseMetadata200Response) HasOpenGraph() bool {
	if o != nil && !IsNil(o.OpenGraph) {
		return true
	}

	return false
}

// SetOpenGraph gets a reference to the given map[string]interface{} and assigns it to the OpenGraph field.
func (o *GetWebparseMetadata200Response) SetOpenGraph(v map[string]interface{}) {
	o.OpenGraph = v
}

func (o GetWebparseMetadata200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWebparseMetadata200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.PageUrl) {
		toSerialize["page_url"] = o.PageUrl
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Keywords) {
		toSerialize["keywords"] = o.Keywords
	}
	if !IsNil(o.FaviconUrl) {
		toSerialize["favicon_url"] = o.FaviconUrl
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.Author) {
		toSerialize["author"] = o.Author
	}
	if !IsNil(o.PublishedTime) {
		toSerialize["published_time"] = o.PublishedTime
	}
	if !IsNil(o.CanonicalUrl) {
		toSerialize["canonical_url"] = o.CanonicalUrl
	}
	if !IsNil(o.Generator) {
		toSerialize["generator"] = o.Generator
	}
	if !IsNil(o.OpenGraph) {
		toSerialize["open_graph"] = o.OpenGraph
	}
	return toSerialize, nil
}

type NullableGetWebparseMetadata200Response struct {
	value *GetWebparseMetadata200Response
	isSet bool
}

func (v NullableGetWebparseMetadata200Response) Get() *GetWebparseMetadata200Response {
	return v.value
}

func (v *NullableGetWebparseMetadata200Response) Set(val *GetWebparseMetadata200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebparseMetadata200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebparseMetadata200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebparseMetadata200Response(val *GetWebparseMetadata200Response) *NullableGetWebparseMetadata200Response {
	return &NullableGetWebparseMetadata200Response{value: val, isSet: true}
}

func (v NullableGetWebparseMetadata200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebparseMetadata200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


