/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscHotboard200ResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscHotboard200ResponseOneOf1{}

// GetMiscHotboard200ResponseOneOf1 struct for GetMiscHotboard200ResponseOneOf1
type GetMiscHotboard200ResponseOneOf1 struct {
	// 匹配到的结果数量。
	Count *int32 `json:"count,omitempty"`
	// 搜索关键词。
	Keyword *string `json:"keyword,omitempty"`
	// 搜索结果数组。
	Results []GetMiscHotboard200ResponseOneOf1ResultsInner `json:"results,omitempty"`
	Type *string `json:"type,omitempty"`
}

// NewGetMiscHotboard200ResponseOneOf1 instantiates a new GetMiscHotboard200ResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscHotboard200ResponseOneOf1() *GetMiscHotboard200ResponseOneOf1 {
	this := GetMiscHotboard200ResponseOneOf1{}
	return &this
}

// NewGetMiscHotboard200ResponseOneOf1WithDefaults instantiates a new GetMiscHotboard200ResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscHotboard200ResponseOneOf1WithDefaults() *GetMiscHotboard200ResponseOneOf1 {
	this := GetMiscHotboard200ResponseOneOf1{}
	return &this
}

// GetCount returns the Count field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf1) GetCount() int32 {
	if o == nil || IsNil(o.Count) {
		var ret int32
		return ret
	}
	return *o.Count
}

// GetCountOk returns a tuple with the Count field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf1) GetCountOk() (*int32, bool) {
	if o == nil || IsNil(o.Count) {
		return nil, false
	}
	return o.Count, true
}

// HasCount returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf1) HasCount() bool {
	if o != nil && !IsNil(o.Count) {
		return true
	}

	return false
}

// SetCount gets a reference to the given int32 and assigns it to the Count field.
func (o *GetMiscHotboard200ResponseOneOf1) SetCount(v int32) {
	o.Count = &v
}

// GetKeyword returns the Keyword field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf1) GetKeyword() string {
	if o == nil || IsNil(o.Keyword) {
		var ret string
		return ret
	}
	return *o.Keyword
}

// GetKeywordOk returns a tuple with the Keyword field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf1) GetKeywordOk() (*string, bool) {
	if o == nil || IsNil(o.Keyword) {
		return nil, false
	}
	return o.Keyword, true
}

// HasKeyword returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf1) HasKeyword() bool {
	if o != nil && !IsNil(o.Keyword) {
		return true
	}

	return false
}

// SetKeyword gets a reference to the given string and assigns it to the Keyword field.
func (o *GetMiscHotboard200ResponseOneOf1) SetKeyword(v string) {
	o.Keyword = &v
}

// GetResults returns the Results field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf1) GetResults() []GetMiscHotboard200ResponseOneOf1ResultsInner {
	if o == nil || IsNil(o.Results) {
		var ret []GetMiscHotboard200ResponseOneOf1ResultsInner
		return ret
	}
	return o.Results
}

// GetResultsOk returns a tuple with the Results field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf1) GetResultsOk() ([]GetMiscHotboard200ResponseOneOf1ResultsInner, bool) {
	if o == nil || IsNil(o.Results) {
		return nil, false
	}
	return o.Results, true
}

// HasResults returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf1) HasResults() bool {
	if o != nil && !IsNil(o.Results) {
		return true
	}

	return false
}

// SetResults gets a reference to the given []GetMiscHotboard200ResponseOneOf1ResultsInner and assigns it to the Results field.
func (o *GetMiscHotboard200ResponseOneOf1) SetResults(v []GetMiscHotboard200ResponseOneOf1ResultsInner) {
	o.Results = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf1) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf1) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf1) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetMiscHotboard200ResponseOneOf1) SetType(v string) {
	o.Type = &v
}

func (o GetMiscHotboard200ResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscHotboard200ResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Count) {
		toSerialize["count"] = o.Count
	}
	if !IsNil(o.Keyword) {
		toSerialize["keyword"] = o.Keyword
	}
	if !IsNil(o.Results) {
		toSerialize["results"] = o.Results
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableGetMiscHotboard200ResponseOneOf1 struct {
	value *GetMiscHotboard200ResponseOneOf1
	isSet bool
}

func (v NullableGetMiscHotboard200ResponseOneOf1) Get() *GetMiscHotboard200ResponseOneOf1 {
	return v.value
}

func (v *NullableGetMiscHotboard200ResponseOneOf1) Set(val *GetMiscHotboard200ResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscHotboard200ResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscHotboard200ResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscHotboard200ResponseOneOf1(val *GetMiscHotboard200ResponseOneOf1) *NullableGetMiscHotboard200ResponseOneOf1 {
	return &NullableGetMiscHotboard200ResponseOneOf1{value: val, isSet: true}
}

func (v NullableGetMiscHotboard200ResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscHotboard200ResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


