/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscTrackingDetect200ResponseAlternativesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscTrackingDetect200ResponseAlternativesInner{}

// GetMiscTrackingDetect200ResponseAlternativesInner struct for GetMiscTrackingDetect200ResponseAlternativesInner
type GetMiscTrackingDetect200ResponseAlternativesInner struct {
	// 快递公司编码
	Code *string `json:"code,omitempty"`
	// 快递公司名称
	Name *string `json:"name,omitempty"`
}

// NewGetMiscTrackingDetect200ResponseAlternativesInner instantiates a new GetMiscTrackingDetect200ResponseAlternativesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscTrackingDetect200ResponseAlternativesInner() *GetMiscTrackingDetect200ResponseAlternativesInner {
	this := GetMiscTrackingDetect200ResponseAlternativesInner{}
	return &this
}

// NewGetMiscTrackingDetect200ResponseAlternativesInnerWithDefaults instantiates a new GetMiscTrackingDetect200ResponseAlternativesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscTrackingDetect200ResponseAlternativesInnerWithDefaults() *GetMiscTrackingDetect200ResponseAlternativesInner {
	this := GetMiscTrackingDetect200ResponseAlternativesInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetMiscTrackingDetect200ResponseAlternativesInner) SetName(v string) {
	o.Name = &v
}

func (o GetMiscTrackingDetect200ResponseAlternativesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscTrackingDetect200ResponseAlternativesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGetMiscTrackingDetect200ResponseAlternativesInner struct {
	value *GetMiscTrackingDetect200ResponseAlternativesInner
	isSet bool
}

func (v NullableGetMiscTrackingDetect200ResponseAlternativesInner) Get() *GetMiscTrackingDetect200ResponseAlternativesInner {
	return v.value
}

func (v *NullableGetMiscTrackingDetect200ResponseAlternativesInner) Set(val *GetMiscTrackingDetect200ResponseAlternativesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscTrackingDetect200ResponseAlternativesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscTrackingDetect200ResponseAlternativesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscTrackingDetect200ResponseAlternativesInner(val *GetMiscTrackingDetect200ResponseAlternativesInner) *NullableGetMiscTrackingDetect200ResponseAlternativesInner {
	return &NullableGetMiscTrackingDetect200ResponseAlternativesInner{value: val, isSet: true}
}

func (v NullableGetMiscTrackingDetect200ResponseAlternativesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscTrackingDetect200ResponseAlternativesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


