/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostTranslateText200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTranslateText200Response{}

// PostTranslateText200Response struct for PostTranslateText200Response
type PostTranslateText200Response struct {
	// 原始文本。
	Text *string `json:"text,omitempty"`
	// 翻译后的文本。
	Translate *string `json:"translate,omitempty"`
}

// NewPostTranslateText200Response instantiates a new PostTranslateText200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTranslateText200Response() *PostTranslateText200Response {
	this := PostTranslateText200Response{}
	return &this
}

// NewPostTranslateText200ResponseWithDefaults instantiates a new PostTranslateText200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTranslateText200ResponseWithDefaults() *PostTranslateText200Response {
	this := PostTranslateText200Response{}
	return &this
}

// GetText returns the Text field value if set, zero value otherwise.
func (o *PostTranslateText200Response) GetText() string {
	if o == nil || IsNil(o.Text) {
		var ret string
		return ret
	}
	return *o.Text
}

// GetTextOk returns a tuple with the Text field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTranslateText200Response) GetTextOk() (*string, bool) {
	if o == nil || IsNil(o.Text) {
		return nil, false
	}
	return o.Text, true
}

// HasText returns a boolean if a field has been set.
func (o *PostTranslateText200Response) HasText() bool {
	if o != nil && !IsNil(o.Text) {
		return true
	}

	return false
}

// SetText gets a reference to the given string and assigns it to the Text field.
func (o *PostTranslateText200Response) SetText(v string) {
	o.Text = &v
}

// GetTranslate returns the Translate field value if set, zero value otherwise.
func (o *PostTranslateText200Response) GetTranslate() string {
	if o == nil || IsNil(o.Translate) {
		var ret string
		return ret
	}
	return *o.Translate
}

// GetTranslateOk returns a tuple with the Translate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTranslateText200Response) GetTranslateOk() (*string, bool) {
	if o == nil || IsNil(o.Translate) {
		return nil, false
	}
	return o.Translate, true
}

// HasTranslate returns a boolean if a field has been set.
func (o *PostTranslateText200Response) HasTranslate() bool {
	if o != nil && !IsNil(o.Translate) {
		return true
	}

	return false
}

// SetTranslate gets a reference to the given string and assigns it to the Translate field.
func (o *PostTranslateText200Response) SetTranslate(v string) {
	o.Translate = &v
}

func (o PostTranslateText200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTranslateText200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Text) {
		toSerialize["text"] = o.Text
	}
	if !IsNil(o.Translate) {
		toSerialize["translate"] = o.Translate
	}
	return toSerialize, nil
}

type NullablePostTranslateText200Response struct {
	value *PostTranslateText200Response
	isSet bool
}

func (v NullablePostTranslateText200Response) Get() *PostTranslateText200Response {
	return v.value
}

func (v *NullablePostTranslateText200Response) Set(val *PostTranslateText200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTranslateText200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTranslateText200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTranslateText200Response(val *PostTranslateText200Response) *NullablePostTranslateText200Response {
	return &NullablePostTranslateText200Response{value: val, isSet: true}
}

func (v NullablePostTranslateText200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTranslateText200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


