/*
UAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscHotboard200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscHotboard200ResponseOneOf{}

// GetMiscHotboard200ResponseOneOf struct for GetMiscHotboard200ResponseOneOf
type GetMiscHotboard200ResponseOneOf struct {
	Type *string `json:"type,omitempty"`
	// 热榜更新时间。时光机无匹配快照时可能为空字符串。
	UpdateTime *string `json:"update_time,omitempty"`
	// 时光机模式返回的快照实际时间戳（毫秒）。当前热榜模式下通常不返回。
	SnapshotTime *int32 `json:"snapshot_time,omitempty"`
	// 热榜条目列表。
	List []GetMiscHotboard200ResponseOneOfListInner `json:"list,omitempty"`
}

// NewGetMiscHotboard200ResponseOneOf instantiates a new GetMiscHotboard200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscHotboard200ResponseOneOf() *GetMiscHotboard200ResponseOneOf {
	this := GetMiscHotboard200ResponseOneOf{}
	return &this
}

// NewGetMiscHotboard200ResponseOneOfWithDefaults instantiates a new GetMiscHotboard200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscHotboard200ResponseOneOfWithDefaults() *GetMiscHotboard200ResponseOneOf {
	this := GetMiscHotboard200ResponseOneOf{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetMiscHotboard200ResponseOneOf) SetType(v string) {
	o.Type = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf) GetUpdateTime() string {
	if o == nil || IsNil(o.UpdateTime) {
		var ret string
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf) GetUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given string and assigns it to the UpdateTime field.
func (o *GetMiscHotboard200ResponseOneOf) SetUpdateTime(v string) {
	o.UpdateTime = &v
}

// GetSnapshotTime returns the SnapshotTime field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf) GetSnapshotTime() int32 {
	if o == nil || IsNil(o.SnapshotTime) {
		var ret int32
		return ret
	}
	return *o.SnapshotTime
}

// GetSnapshotTimeOk returns a tuple with the SnapshotTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf) GetSnapshotTimeOk() (*int32, bool) {
	if o == nil || IsNil(o.SnapshotTime) {
		return nil, false
	}
	return o.SnapshotTime, true
}

// HasSnapshotTime returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf) HasSnapshotTime() bool {
	if o != nil && !IsNil(o.SnapshotTime) {
		return true
	}

	return false
}

// SetSnapshotTime gets a reference to the given int32 and assigns it to the SnapshotTime field.
func (o *GetMiscHotboard200ResponseOneOf) SetSnapshotTime(v int32) {
	o.SnapshotTime = &v
}

// GetList returns the List field value if set, zero value otherwise.
func (o *GetMiscHotboard200ResponseOneOf) GetList() []GetMiscHotboard200ResponseOneOfListInner {
	if o == nil || IsNil(o.List) {
		var ret []GetMiscHotboard200ResponseOneOfListInner
		return ret
	}
	return o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200ResponseOneOf) GetListOk() ([]GetMiscHotboard200ResponseOneOfListInner, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *GetMiscHotboard200ResponseOneOf) HasList() bool {
	if o != nil && !IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given []GetMiscHotboard200ResponseOneOfListInner and assigns it to the List field.
func (o *GetMiscHotboard200ResponseOneOf) SetList(v []GetMiscHotboard200ResponseOneOfListInner) {
	o.List = v
}

func (o GetMiscHotboard200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscHotboard200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["update_time"] = o.UpdateTime
	}
	if !IsNil(o.SnapshotTime) {
		toSerialize["snapshot_time"] = o.SnapshotTime
	}
	if !IsNil(o.List) {
		toSerialize["list"] = o.List
	}
	return toSerialize, nil
}

type NullableGetMiscHotboard200ResponseOneOf struct {
	value *GetMiscHotboard200ResponseOneOf
	isSet bool
}

func (v NullableGetMiscHotboard200ResponseOneOf) Get() *GetMiscHotboard200ResponseOneOf {
	return v.value
}

func (v *NullableGetMiscHotboard200ResponseOneOf) Set(val *GetMiscHotboard200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscHotboard200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscHotboard200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscHotboard200ResponseOneOf(val *GetMiscHotboard200ResponseOneOf) *NullableGetMiscHotboard200ResponseOneOf {
	return &NullableGetMiscHotboard200ResponseOneOf{value: val, isSet: true}
}

func (v NullableGetMiscHotboard200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscHotboard200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


