/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the Base64 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Base64{}

// Base64 struct for Base64
type Base64 struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewBase64 instantiates a new Base64 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBase64() *Base64 {
	this := Base64{}
	return &this
}

// NewBase64WithDefaults instantiates a new Base64 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBase64WithDefaults() *Base64 {
	this := Base64{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *Base64) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Base64) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *Base64) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *Base64) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *Base64) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Base64) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *Base64) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *Base64) SetMessage(v string) {
	o.Message = &v
}

func (o Base64) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Base64) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableBase64 struct {
	value *Base64
	isSet bool
}

func (v NullableBase64) Get() *Base64 {
	return v.value
}

func (v *NullableBase64) Set(val *Base64) {
	v.value = val
	v.isSet = true
}

func (v NullableBase64) IsSet() bool {
	return v.isSet
}

func (v *NullableBase64) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBase64(val *Base64) *NullableBase64 {
	return &NullableBase64{value: val, isSet: true}
}

func (v NullableBase64) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBase64) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


