/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"time"
)

// checks if the GetGithubUser200ResponsePinnedRepositoriesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetGithubUser200ResponsePinnedRepositoriesInner{}

// GetGithubUser200ResponsePinnedRepositoriesInner struct for GetGithubUser200ResponsePinnedRepositoriesInner
type GetGithubUser200ResponsePinnedRepositoriesInner struct {
	// 该仓库是否已归档。
	Archived *bool `json:"archived,omitempty"`
	// 仓库简介。
	Description *string `json:"description,omitempty"`
	// 该仓库是否为 fork。
	Fork *bool `json:"fork,omitempty"`
	// Fork 数量。
	Forks *int32 `json:"forks,omitempty"`
	// 包含所有者的完整仓库名。
	FullName *string `json:"full_name,omitempty"`
	// 仓库填写的官网地址。
	Homepage *string `json:"homepage,omitempty"`
	// 仓库主页链接。
	HtmlUrl *string `json:"html_url,omitempty"`
	// 仓库主语言。
	Language *string `json:"language,omitempty"`
	// 仓库名。
	Name *string `json:"name,omitempty"`
	// 最近一次 push 时间。
	PushedAt *time.Time `json:"pushed_at,omitempty"`
	// Star 数量。
	Stargazers *int32 `json:"stargazers,omitempty"`
	// 最近一次资料更新时间。
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// 仓库可见性。
	Visibility *string `json:"visibility,omitempty"`
}

// NewGetGithubUser200ResponsePinnedRepositoriesInner instantiates a new GetGithubUser200ResponsePinnedRepositoriesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetGithubUser200ResponsePinnedRepositoriesInner() *GetGithubUser200ResponsePinnedRepositoriesInner {
	this := GetGithubUser200ResponsePinnedRepositoriesInner{}
	return &this
}

// NewGetGithubUser200ResponsePinnedRepositoriesInnerWithDefaults instantiates a new GetGithubUser200ResponsePinnedRepositoriesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetGithubUser200ResponsePinnedRepositoriesInnerWithDefaults() *GetGithubUser200ResponsePinnedRepositoriesInner {
	this := GetGithubUser200ResponsePinnedRepositoriesInner{}
	return &this
}

// GetArchived returns the Archived field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetArchived() bool {
	if o == nil || IsNil(o.Archived) {
		var ret bool
		return ret
	}
	return *o.Archived
}

// GetArchivedOk returns a tuple with the Archived field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetArchivedOk() (*bool, bool) {
	if o == nil || IsNil(o.Archived) {
		return nil, false
	}
	return o.Archived, true
}

// HasArchived returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasArchived() bool {
	if o != nil && !IsNil(o.Archived) {
		return true
	}

	return false
}

// SetArchived gets a reference to the given bool and assigns it to the Archived field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetArchived(v bool) {
	o.Archived = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetDescription(v string) {
	o.Description = &v
}

// GetFork returns the Fork field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetFork() bool {
	if o == nil || IsNil(o.Fork) {
		var ret bool
		return ret
	}
	return *o.Fork
}

// GetForkOk returns a tuple with the Fork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetForkOk() (*bool, bool) {
	if o == nil || IsNil(o.Fork) {
		return nil, false
	}
	return o.Fork, true
}

// HasFork returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasFork() bool {
	if o != nil && !IsNil(o.Fork) {
		return true
	}

	return false
}

// SetFork gets a reference to the given bool and assigns it to the Fork field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetFork(v bool) {
	o.Fork = &v
}

// GetForks returns the Forks field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetForks() int32 {
	if o == nil || IsNil(o.Forks) {
		var ret int32
		return ret
	}
	return *o.Forks
}

// GetForksOk returns a tuple with the Forks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetForksOk() (*int32, bool) {
	if o == nil || IsNil(o.Forks) {
		return nil, false
	}
	return o.Forks, true
}

// HasForks returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasForks() bool {
	if o != nil && !IsNil(o.Forks) {
		return true
	}

	return false
}

// SetForks gets a reference to the given int32 and assigns it to the Forks field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetForks(v int32) {
	o.Forks = &v
}

// GetFullName returns the FullName field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetFullName() string {
	if o == nil || IsNil(o.FullName) {
		var ret string
		return ret
	}
	return *o.FullName
}

// GetFullNameOk returns a tuple with the FullName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetFullNameOk() (*string, bool) {
	if o == nil || IsNil(o.FullName) {
		return nil, false
	}
	return o.FullName, true
}

// HasFullName returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasFullName() bool {
	if o != nil && !IsNil(o.FullName) {
		return true
	}

	return false
}

// SetFullName gets a reference to the given string and assigns it to the FullName field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetFullName(v string) {
	o.FullName = &v
}

// GetHomepage returns the Homepage field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetHomepage() string {
	if o == nil || IsNil(o.Homepage) {
		var ret string
		return ret
	}
	return *o.Homepage
}

// GetHomepageOk returns a tuple with the Homepage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetHomepageOk() (*string, bool) {
	if o == nil || IsNil(o.Homepage) {
		return nil, false
	}
	return o.Homepage, true
}

// HasHomepage returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasHomepage() bool {
	if o != nil && !IsNil(o.Homepage) {
		return true
	}

	return false
}

// SetHomepage gets a reference to the given string and assigns it to the Homepage field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetHomepage(v string) {
	o.Homepage = &v
}

// GetHtmlUrl returns the HtmlUrl field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetHtmlUrl() string {
	if o == nil || IsNil(o.HtmlUrl) {
		var ret string
		return ret
	}
	return *o.HtmlUrl
}

// GetHtmlUrlOk returns a tuple with the HtmlUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetHtmlUrlOk() (*string, bool) {
	if o == nil || IsNil(o.HtmlUrl) {
		return nil, false
	}
	return o.HtmlUrl, true
}

// HasHtmlUrl returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasHtmlUrl() bool {
	if o != nil && !IsNil(o.HtmlUrl) {
		return true
	}

	return false
}

// SetHtmlUrl gets a reference to the given string and assigns it to the HtmlUrl field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetHtmlUrl(v string) {
	o.HtmlUrl = &v
}

// GetLanguage returns the Language field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetLanguage() string {
	if o == nil || IsNil(o.Language) {
		var ret string
		return ret
	}
	return *o.Language
}

// GetLanguageOk returns a tuple with the Language field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetLanguageOk() (*string, bool) {
	if o == nil || IsNil(o.Language) {
		return nil, false
	}
	return o.Language, true
}

// HasLanguage returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasLanguage() bool {
	if o != nil && !IsNil(o.Language) {
		return true
	}

	return false
}

// SetLanguage gets a reference to the given string and assigns it to the Language field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetLanguage(v string) {
	o.Language = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetName(v string) {
	o.Name = &v
}

// GetPushedAt returns the PushedAt field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetPushedAt() time.Time {
	if o == nil || IsNil(o.PushedAt) {
		var ret time.Time
		return ret
	}
	return *o.PushedAt
}

// GetPushedAtOk returns a tuple with the PushedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetPushedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.PushedAt) {
		return nil, false
	}
	return o.PushedAt, true
}

// HasPushedAt returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasPushedAt() bool {
	if o != nil && !IsNil(o.PushedAt) {
		return true
	}

	return false
}

// SetPushedAt gets a reference to the given time.Time and assigns it to the PushedAt field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetPushedAt(v time.Time) {
	o.PushedAt = &v
}

// GetStargazers returns the Stargazers field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetStargazers() int32 {
	if o == nil || IsNil(o.Stargazers) {
		var ret int32
		return ret
	}
	return *o.Stargazers
}

// GetStargazersOk returns a tuple with the Stargazers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetStargazersOk() (*int32, bool) {
	if o == nil || IsNil(o.Stargazers) {
		return nil, false
	}
	return o.Stargazers, true
}

// HasStargazers returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasStargazers() bool {
	if o != nil && !IsNil(o.Stargazers) {
		return true
	}

	return false
}

// SetStargazers gets a reference to the given int32 and assigns it to the Stargazers field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetStargazers(v int32) {
	o.Stargazers = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetVisibility returns the Visibility field value if set, zero value otherwise.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetVisibility() string {
	if o == nil || IsNil(o.Visibility) {
		var ret string
		return ret
	}
	return *o.Visibility
}

// GetVisibilityOk returns a tuple with the Visibility field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) GetVisibilityOk() (*string, bool) {
	if o == nil || IsNil(o.Visibility) {
		return nil, false
	}
	return o.Visibility, true
}

// HasVisibility returns a boolean if a field has been set.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) HasVisibility() bool {
	if o != nil && !IsNil(o.Visibility) {
		return true
	}

	return false
}

// SetVisibility gets a reference to the given string and assigns it to the Visibility field.
func (o *GetGithubUser200ResponsePinnedRepositoriesInner) SetVisibility(v string) {
	o.Visibility = &v
}

func (o GetGithubUser200ResponsePinnedRepositoriesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetGithubUser200ResponsePinnedRepositoriesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Archived) {
		toSerialize["archived"] = o.Archived
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Fork) {
		toSerialize["fork"] = o.Fork
	}
	if !IsNil(o.Forks) {
		toSerialize["forks"] = o.Forks
	}
	if !IsNil(o.FullName) {
		toSerialize["full_name"] = o.FullName
	}
	if !IsNil(o.Homepage) {
		toSerialize["homepage"] = o.Homepage
	}
	if !IsNil(o.HtmlUrl) {
		toSerialize["html_url"] = o.HtmlUrl
	}
	if !IsNil(o.Language) {
		toSerialize["language"] = o.Language
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PushedAt) {
		toSerialize["pushed_at"] = o.PushedAt
	}
	if !IsNil(o.Stargazers) {
		toSerialize["stargazers"] = o.Stargazers
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	if !IsNil(o.Visibility) {
		toSerialize["visibility"] = o.Visibility
	}
	return toSerialize, nil
}

type NullableGetGithubUser200ResponsePinnedRepositoriesInner struct {
	value *GetGithubUser200ResponsePinnedRepositoriesInner
	isSet bool
}

func (v NullableGetGithubUser200ResponsePinnedRepositoriesInner) Get() *GetGithubUser200ResponsePinnedRepositoriesInner {
	return v.value
}

func (v *NullableGetGithubUser200ResponsePinnedRepositoriesInner) Set(val *GetGithubUser200ResponsePinnedRepositoriesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetGithubUser200ResponsePinnedRepositoriesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetGithubUser200ResponsePinnedRepositoriesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetGithubUser200ResponsePinnedRepositoriesInner(val *GetGithubUser200ResponsePinnedRepositoriesInner) *NullableGetGithubUser200ResponsePinnedRepositoriesInner {
	return &NullableGetGithubUser200ResponsePinnedRepositoriesInner{value: val, isSet: true}
}

func (v NullableGetGithubUser200ResponsePinnedRepositoriesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetGithubUser200ResponsePinnedRepositoriesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


