/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostImageMotou400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostImageMotou400Response{}

// PostImageMotou400Response struct for PostImageMotou400Response
type PostImageMotou400Response struct {
	Error *string `json:"error,omitempty"`
}

// NewPostImageMotou400Response instantiates a new PostImageMotou400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostImageMotou400Response() *PostImageMotou400Response {
	this := PostImageMotou400Response{}
	return &this
}

// NewPostImageMotou400ResponseWithDefaults instantiates a new PostImageMotou400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostImageMotou400ResponseWithDefaults() *PostImageMotou400Response {
	this := PostImageMotou400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PostImageMotou400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostImageMotou400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PostImageMotou400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *PostImageMotou400Response) SetError(v string) {
	o.Error = &v
}

func (o PostImageMotou400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostImageMotou400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullablePostImageMotou400Response struct {
	value *PostImageMotou400Response
	isSet bool
}

func (v NullablePostImageMotou400Response) Get() *PostImageMotou400Response {
	return v.value
}

func (v *NullablePostImageMotou400Response) Set(val *PostImageMotou400Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostImageMotou400Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostImageMotou400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostImageMotou400Response(val *PostImageMotou400Response) *NullablePostImageMotou400Response {
	return &NullablePostImageMotou400Response{value: val, isSet: true}
}

func (v NullablePostImageMotou400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostImageMotou400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


