/*
UAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscHolidayCalendar200ResponseNearbyNextInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscHolidayCalendar200ResponseNearbyNextInner{}

// GetMiscHolidayCalendar200ResponseNearbyNextInner struct for GetMiscHolidayCalendar200ResponseNearbyNextInner
type GetMiscHolidayCalendar200ResponseNearbyNextInner struct {
	// 聚合日期。
	Date *string `json:"date,omitempty"`
	// 该日期上的节日事件列表。
	Events []GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner `json:"events,omitempty"`
}

// NewGetMiscHolidayCalendar200ResponseNearbyNextInner instantiates a new GetMiscHolidayCalendar200ResponseNearbyNextInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscHolidayCalendar200ResponseNearbyNextInner() *GetMiscHolidayCalendar200ResponseNearbyNextInner {
	this := GetMiscHolidayCalendar200ResponseNearbyNextInner{}
	return &this
}

// NewGetMiscHolidayCalendar200ResponseNearbyNextInnerWithDefaults instantiates a new GetMiscHolidayCalendar200ResponseNearbyNextInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscHolidayCalendar200ResponseNearbyNextInnerWithDefaults() *GetMiscHolidayCalendar200ResponseNearbyNextInner {
	this := GetMiscHolidayCalendar200ResponseNearbyNextInner{}
	return &this
}

// GetDate returns the Date field value if set, zero value otherwise.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) GetDate() string {
	if o == nil || IsNil(o.Date) {
		var ret string
		return ret
	}
	return *o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) GetDateOk() (*string, bool) {
	if o == nil || IsNil(o.Date) {
		return nil, false
	}
	return o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) HasDate() bool {
	if o != nil && !IsNil(o.Date) {
		return true
	}

	return false
}

// SetDate gets a reference to the given string and assigns it to the Date field.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) SetDate(v string) {
	o.Date = &v
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) GetEvents() []GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner {
	if o == nil || IsNil(o.Events) {
		var ret []GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) GetEventsOk() ([]GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner and assigns it to the Events field.
func (o *GetMiscHolidayCalendar200ResponseNearbyNextInner) SetEvents(v []GetMiscHolidayCalendar200ResponseNearbyNextInnerEventsInner) {
	o.Events = v
}

func (o GetMiscHolidayCalendar200ResponseNearbyNextInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscHolidayCalendar200ResponseNearbyNextInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Date) {
		toSerialize["date"] = o.Date
	}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	return toSerialize, nil
}

type NullableGetMiscHolidayCalendar200ResponseNearbyNextInner struct {
	value *GetMiscHolidayCalendar200ResponseNearbyNextInner
	isSet bool
}

func (v NullableGetMiscHolidayCalendar200ResponseNearbyNextInner) Get() *GetMiscHolidayCalendar200ResponseNearbyNextInner {
	return v.value
}

func (v *NullableGetMiscHolidayCalendar200ResponseNearbyNextInner) Set(val *GetMiscHolidayCalendar200ResponseNearbyNextInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscHolidayCalendar200ResponseNearbyNextInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscHolidayCalendar200ResponseNearbyNextInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscHolidayCalendar200ResponseNearbyNextInner(val *GetMiscHolidayCalendar200ResponseNearbyNextInner) *NullableGetMiscHolidayCalendar200ResponseNearbyNextInner {
	return &NullableGetMiscHolidayCalendar200ResponseNearbyNextInner{value: val, isSet: true}
}

func (v NullableGetMiscHolidayCalendar200ResponseNearbyNextInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscHolidayCalendar200ResponseNearbyNextInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


