/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostAiTranslate200ResponseDataExplanation type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostAiTranslate200ResponseDataExplanation{}

// PostAiTranslate200ResponseDataExplanation struct for PostAiTranslate200ResponseDataExplanation
type PostAiTranslate200ResponseDataExplanation struct {
	KeyPhrases []map[string]interface{} `json:"key_phrases,omitempty"`
	CulturalNotes []string `json:"cultural_notes,omitempty"`
	GrammarNotes []string `json:"grammar_notes,omitempty"`
}

// NewPostAiTranslate200ResponseDataExplanation instantiates a new PostAiTranslate200ResponseDataExplanation object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostAiTranslate200ResponseDataExplanation() *PostAiTranslate200ResponseDataExplanation {
	this := PostAiTranslate200ResponseDataExplanation{}
	return &this
}

// NewPostAiTranslate200ResponseDataExplanationWithDefaults instantiates a new PostAiTranslate200ResponseDataExplanation object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostAiTranslate200ResponseDataExplanationWithDefaults() *PostAiTranslate200ResponseDataExplanation {
	this := PostAiTranslate200ResponseDataExplanation{}
	return &this
}

// GetKeyPhrases returns the KeyPhrases field value if set, zero value otherwise.
func (o *PostAiTranslate200ResponseDataExplanation) GetKeyPhrases() []map[string]interface{} {
	if o == nil || IsNil(o.KeyPhrases) {
		var ret []map[string]interface{}
		return ret
	}
	return o.KeyPhrases
}

// GetKeyPhrasesOk returns a tuple with the KeyPhrases field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAiTranslate200ResponseDataExplanation) GetKeyPhrasesOk() ([]map[string]interface{}, bool) {
	if o == nil || IsNil(o.KeyPhrases) {
		return nil, false
	}
	return o.KeyPhrases, true
}

// HasKeyPhrases returns a boolean if a field has been set.
func (o *PostAiTranslate200ResponseDataExplanation) HasKeyPhrases() bool {
	if o != nil && !IsNil(o.KeyPhrases) {
		return true
	}

	return false
}

// SetKeyPhrases gets a reference to the given []map[string]interface{} and assigns it to the KeyPhrases field.
func (o *PostAiTranslate200ResponseDataExplanation) SetKeyPhrases(v []map[string]interface{}) {
	o.KeyPhrases = v
}

// GetCulturalNotes returns the CulturalNotes field value if set, zero value otherwise.
func (o *PostAiTranslate200ResponseDataExplanation) GetCulturalNotes() []string {
	if o == nil || IsNil(o.CulturalNotes) {
		var ret []string
		return ret
	}
	return o.CulturalNotes
}

// GetCulturalNotesOk returns a tuple with the CulturalNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAiTranslate200ResponseDataExplanation) GetCulturalNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.CulturalNotes) {
		return nil, false
	}
	return o.CulturalNotes, true
}

// HasCulturalNotes returns a boolean if a field has been set.
func (o *PostAiTranslate200ResponseDataExplanation) HasCulturalNotes() bool {
	if o != nil && !IsNil(o.CulturalNotes) {
		return true
	}

	return false
}

// SetCulturalNotes gets a reference to the given []string and assigns it to the CulturalNotes field.
func (o *PostAiTranslate200ResponseDataExplanation) SetCulturalNotes(v []string) {
	o.CulturalNotes = v
}

// GetGrammarNotes returns the GrammarNotes field value if set, zero value otherwise.
func (o *PostAiTranslate200ResponseDataExplanation) GetGrammarNotes() []string {
	if o == nil || IsNil(o.GrammarNotes) {
		var ret []string
		return ret
	}
	return o.GrammarNotes
}

// GetGrammarNotesOk returns a tuple with the GrammarNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostAiTranslate200ResponseDataExplanation) GetGrammarNotesOk() ([]string, bool) {
	if o == nil || IsNil(o.GrammarNotes) {
		return nil, false
	}
	return o.GrammarNotes, true
}

// HasGrammarNotes returns a boolean if a field has been set.
func (o *PostAiTranslate200ResponseDataExplanation) HasGrammarNotes() bool {
	if o != nil && !IsNil(o.GrammarNotes) {
		return true
	}

	return false
}

// SetGrammarNotes gets a reference to the given []string and assigns it to the GrammarNotes field.
func (o *PostAiTranslate200ResponseDataExplanation) SetGrammarNotes(v []string) {
	o.GrammarNotes = v
}

func (o PostAiTranslate200ResponseDataExplanation) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostAiTranslate200ResponseDataExplanation) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.KeyPhrases) {
		toSerialize["key_phrases"] = o.KeyPhrases
	}
	if !IsNil(o.CulturalNotes) {
		toSerialize["cultural_notes"] = o.CulturalNotes
	}
	if !IsNil(o.GrammarNotes) {
		toSerialize["grammar_notes"] = o.GrammarNotes
	}
	return toSerialize, nil
}

type NullablePostAiTranslate200ResponseDataExplanation struct {
	value *PostAiTranslate200ResponseDataExplanation
	isSet bool
}

func (v NullablePostAiTranslate200ResponseDataExplanation) Get() *PostAiTranslate200ResponseDataExplanation {
	return v.value
}

func (v *NullablePostAiTranslate200ResponseDataExplanation) Set(val *PostAiTranslate200ResponseDataExplanation) {
	v.value = val
	v.isSet = true
}

func (v NullablePostAiTranslate200ResponseDataExplanation) IsSet() bool {
	return v.isSet
}

func (v *NullablePostAiTranslate200ResponseDataExplanation) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostAiTranslate200ResponseDataExplanation(val *PostAiTranslate200ResponseDataExplanation) *NullablePostAiTranslate200ResponseDataExplanation {
	return &NullablePostAiTranslate200ResponseDataExplanation{value: val, isSet: true}
}

func (v NullablePostAiTranslate200ResponseDataExplanation) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostAiTranslate200ResponseDataExplanation) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


