/*
UAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostTextMarkdownToPdf503ResponseOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTextMarkdownToPdf503ResponseOneOf1{}

// PostTextMarkdownToPdf503ResponseOneOf1 struct for PostTextMarkdownToPdf503ResponseOneOf1
type PostTextMarkdownToPdf503ResponseOneOf1 struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewPostTextMarkdownToPdf503ResponseOneOf1 instantiates a new PostTextMarkdownToPdf503ResponseOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTextMarkdownToPdf503ResponseOneOf1() *PostTextMarkdownToPdf503ResponseOneOf1 {
	this := PostTextMarkdownToPdf503ResponseOneOf1{}
	return &this
}

// NewPostTextMarkdownToPdf503ResponseOneOf1WithDefaults instantiates a new PostTextMarkdownToPdf503ResponseOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTextMarkdownToPdf503ResponseOneOf1WithDefaults() *PostTextMarkdownToPdf503ResponseOneOf1 {
	this := PostTextMarkdownToPdf503ResponseOneOf1{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PostTextMarkdownToPdf503ResponseOneOf1) SetMessage(v string) {
	o.Message = &v
}

func (o PostTextMarkdownToPdf503ResponseOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTextMarkdownToPdf503ResponseOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePostTextMarkdownToPdf503ResponseOneOf1 struct {
	value *PostTextMarkdownToPdf503ResponseOneOf1
	isSet bool
}

func (v NullablePostTextMarkdownToPdf503ResponseOneOf1) Get() *PostTextMarkdownToPdf503ResponseOneOf1 {
	return v.value
}

func (v *NullablePostTextMarkdownToPdf503ResponseOneOf1) Set(val *PostTextMarkdownToPdf503ResponseOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextMarkdownToPdf503ResponseOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextMarkdownToPdf503ResponseOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextMarkdownToPdf503ResponseOneOf1(val *PostTextMarkdownToPdf503ResponseOneOf1) *NullablePostTextMarkdownToPdf503ResponseOneOf1 {
	return &NullablePostTextMarkdownToPdf503ResponseOneOf1{value: val, isSet: true}
}

func (v NullablePostTextMarkdownToPdf503ResponseOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextMarkdownToPdf503ResponseOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


