/*
UAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetImageBingDailyHistory400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetImageBingDailyHistory400Response{}

// GetImageBingDailyHistory400Response struct for GetImageBingDailyHistory400Response
type GetImageBingDailyHistory400Response struct {
	Error *string `json:"error,omitempty"`
}

// NewGetImageBingDailyHistory400Response instantiates a new GetImageBingDailyHistory400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetImageBingDailyHistory400Response() *GetImageBingDailyHistory400Response {
	this := GetImageBingDailyHistory400Response{}
	return &this
}

// NewGetImageBingDailyHistory400ResponseWithDefaults instantiates a new GetImageBingDailyHistory400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetImageBingDailyHistory400ResponseWithDefaults() *GetImageBingDailyHistory400Response {
	this := GetImageBingDailyHistory400Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *GetImageBingDailyHistory400Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetImageBingDailyHistory400Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *GetImageBingDailyHistory400Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *GetImageBingDailyHistory400Response) SetError(v string) {
	o.Error = &v
}

func (o GetImageBingDailyHistory400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetImageBingDailyHistory400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullableGetImageBingDailyHistory400Response struct {
	value *GetImageBingDailyHistory400Response
	isSet bool
}

func (v NullableGetImageBingDailyHistory400Response) Get() *GetImageBingDailyHistory400Response {
	return v.value
}

func (v *NullableGetImageBingDailyHistory400Response) Set(val *GetImageBingDailyHistory400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetImageBingDailyHistory400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetImageBingDailyHistory400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetImageBingDailyHistory400Response(val *GetImageBingDailyHistory400Response) *NullableGetImageBingDailyHistory400Response {
	return &NullableGetImageBingDailyHistory400Response{value: val, isSet: true}
}

func (v NullableGetImageBingDailyHistory400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetImageBingDailyHistory400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


