/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetConvertUnixtime400Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetConvertUnixtime400Response{}

// GetConvertUnixtime400Response struct for GetConvertUnixtime400Response
type GetConvertUnixtime400Response struct {
	// 机器可读的错误代码。
	Code *string `json:"code,omitempty"`
	// 包含错误详情的对象。
	Details map[string]interface{} `json:"details,omitempty"`
	// 人类可读的错误描述信息。
	Message *string `json:"message,omitempty"`
}

// NewGetConvertUnixtime400Response instantiates a new GetConvertUnixtime400Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetConvertUnixtime400Response() *GetConvertUnixtime400Response {
	this := GetConvertUnixtime400Response{}
	return &this
}

// NewGetConvertUnixtime400ResponseWithDefaults instantiates a new GetConvertUnixtime400Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetConvertUnixtime400ResponseWithDefaults() *GetConvertUnixtime400Response {
	this := GetConvertUnixtime400Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetConvertUnixtime400Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConvertUnixtime400Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetConvertUnixtime400Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetConvertUnixtime400Response) SetCode(v string) {
	o.Code = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *GetConvertUnixtime400Response) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConvertUnixtime400Response) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *GetConvertUnixtime400Response) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *GetConvertUnixtime400Response) SetDetails(v map[string]interface{}) {
	o.Details = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetConvertUnixtime400Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetConvertUnixtime400Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetConvertUnixtime400Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetConvertUnixtime400Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetConvertUnixtime400Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetConvertUnixtime400Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetConvertUnixtime400Response struct {
	value *GetConvertUnixtime400Response
	isSet bool
}

func (v NullableGetConvertUnixtime400Response) Get() *GetConvertUnixtime400Response {
	return v.value
}

func (v *NullableGetConvertUnixtime400Response) Set(val *GetConvertUnixtime400Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetConvertUnixtime400Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetConvertUnixtime400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetConvertUnixtime400Response(val *GetConvertUnixtime400Response) *NullableGetConvertUnixtime400Response {
	return &NullableGetConvertUnixtime400Response{value: val, isSet: true}
}

func (v NullableGetConvertUnixtime400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetConvertUnixtime400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


