/*
UAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostTextMarkdownToPdf400Response - struct for PostTextMarkdownToPdf400Response
type PostTextMarkdownToPdf400Response struct {
	HTML *HTML
	Markdown *Markdown
	PostTextMarkdownToHtml400ResponseOneOf *PostTextMarkdownToHtml400ResponseOneOf
	PostTextMarkdownToPdf400ResponseOneOf *PostTextMarkdownToPdf400ResponseOneOf
	PostTextMarkdownToPdf400ResponseOneOf1 *PostTextMarkdownToPdf400ResponseOneOf1
	PostTextMarkdownToPdf400ResponseOneOf2 *PostTextMarkdownToPdf400ResponseOneOf2
	PostTextMarkdownToPdf400ResponseOneOf3 *PostTextMarkdownToPdf400ResponseOneOf3
}

// HTMLAsPostTextMarkdownToPdf400Response is a convenience function that returns HTML wrapped in PostTextMarkdownToPdf400Response
func HTMLAsPostTextMarkdownToPdf400Response(v *HTML) PostTextMarkdownToPdf400Response {
	return PostTextMarkdownToPdf400Response{
		HTML: v,
	}
}

// MarkdownAsPostTextMarkdownToPdf400Response is a convenience function that returns Markdown wrapped in PostTextMarkdownToPdf400Response
func MarkdownAsPostTextMarkdownToPdf400Response(v *Markdown) PostTextMarkdownToPdf400Response {
	return PostTextMarkdownToPdf400Response{
		Markdown: v,
	}
}

// PostTextMarkdownToHtml400ResponseOneOfAsPostTextMarkdownToPdf400Response is a convenience function that returns PostTextMarkdownToHtml400ResponseOneOf wrapped in PostTextMarkdownToPdf400Response
func PostTextMarkdownToHtml400ResponseOneOfAsPostTextMarkdownToPdf400Response(v *PostTextMarkdownToHtml400ResponseOneOf) PostTextMarkdownToPdf400Response {
	return PostTextMarkdownToPdf400Response{
		PostTextMarkdownToHtml400ResponseOneOf: v,
	}
}

// PostTextMarkdownToPdf400ResponseOneOfAsPostTextMarkdownToPdf400Response is a convenience function that returns PostTextMarkdownToPdf400ResponseOneOf wrapped in PostTextMarkdownToPdf400Response
func PostTextMarkdownToPdf400ResponseOneOfAsPostTextMarkdownToPdf400Response(v *PostTextMarkdownToPdf400ResponseOneOf) PostTextMarkdownToPdf400Response {
	return PostTextMarkdownToPdf400Response{
		PostTextMarkdownToPdf400ResponseOneOf: v,
	}
}

// PostTextMarkdownToPdf400ResponseOneOf1AsPostTextMarkdownToPdf400Response is a convenience function that returns PostTextMarkdownToPdf400ResponseOneOf1 wrapped in PostTextMarkdownToPdf400Response
func PostTextMarkdownToPdf400ResponseOneOf1AsPostTextMarkdownToPdf400Response(v *PostTextMarkdownToPdf400ResponseOneOf1) PostTextMarkdownToPdf400Response {
	return PostTextMarkdownToPdf400Response{
		PostTextMarkdownToPdf400ResponseOneOf1: v,
	}
}

// PostTextMarkdownToPdf400ResponseOneOf2AsPostTextMarkdownToPdf400Response is a convenience function that returns PostTextMarkdownToPdf400ResponseOneOf2 wrapped in PostTextMarkdownToPdf400Response
func PostTextMarkdownToPdf400ResponseOneOf2AsPostTextMarkdownToPdf400Response(v *PostTextMarkdownToPdf400ResponseOneOf2) PostTextMarkdownToPdf400Response {
	return PostTextMarkdownToPdf400Response{
		PostTextMarkdownToPdf400ResponseOneOf2: v,
	}
}

// PostTextMarkdownToPdf400ResponseOneOf3AsPostTextMarkdownToPdf400Response is a convenience function that returns PostTextMarkdownToPdf400ResponseOneOf3 wrapped in PostTextMarkdownToPdf400Response
func PostTextMarkdownToPdf400ResponseOneOf3AsPostTextMarkdownToPdf400Response(v *PostTextMarkdownToPdf400ResponseOneOf3) PostTextMarkdownToPdf400Response {
	return PostTextMarkdownToPdf400Response{
		PostTextMarkdownToPdf400ResponseOneOf3: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostTextMarkdownToPdf400Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into HTML
	err = newStrictDecoder(data).Decode(&dst.HTML)
	if err == nil {
		jsonHTML, _ := json.Marshal(dst.HTML)
		if string(jsonHTML) == "{}" { // empty struct
			dst.HTML = nil
		} else {
			if err = validator.Validate(dst.HTML); err != nil {
				dst.HTML = nil
			} else {
				match++
			}
		}
	} else {
		dst.HTML = nil
	}

	// try to unmarshal data into Markdown
	err = newStrictDecoder(data).Decode(&dst.Markdown)
	if err == nil {
		jsonMarkdown, _ := json.Marshal(dst.Markdown)
		if string(jsonMarkdown) == "{}" { // empty struct
			dst.Markdown = nil
		} else {
			if err = validator.Validate(dst.Markdown); err != nil {
				dst.Markdown = nil
			} else {
				match++
			}
		}
	} else {
		dst.Markdown = nil
	}

	// try to unmarshal data into PostTextMarkdownToHtml400ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToHtml400ResponseOneOf)
	if err == nil {
		jsonPostTextMarkdownToHtml400ResponseOneOf, _ := json.Marshal(dst.PostTextMarkdownToHtml400ResponseOneOf)
		if string(jsonPostTextMarkdownToHtml400ResponseOneOf) == "{}" { // empty struct
			dst.PostTextMarkdownToHtml400ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToHtml400ResponseOneOf); err != nil {
				dst.PostTextMarkdownToHtml400ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToHtml400ResponseOneOf = nil
	}

	// try to unmarshal data into PostTextMarkdownToPdf400ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToPdf400ResponseOneOf)
	if err == nil {
		jsonPostTextMarkdownToPdf400ResponseOneOf, _ := json.Marshal(dst.PostTextMarkdownToPdf400ResponseOneOf)
		if string(jsonPostTextMarkdownToPdf400ResponseOneOf) == "{}" { // empty struct
			dst.PostTextMarkdownToPdf400ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToPdf400ResponseOneOf); err != nil {
				dst.PostTextMarkdownToPdf400ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToPdf400ResponseOneOf = nil
	}

	// try to unmarshal data into PostTextMarkdownToPdf400ResponseOneOf1
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToPdf400ResponseOneOf1)
	if err == nil {
		jsonPostTextMarkdownToPdf400ResponseOneOf1, _ := json.Marshal(dst.PostTextMarkdownToPdf400ResponseOneOf1)
		if string(jsonPostTextMarkdownToPdf400ResponseOneOf1) == "{}" { // empty struct
			dst.PostTextMarkdownToPdf400ResponseOneOf1 = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToPdf400ResponseOneOf1); err != nil {
				dst.PostTextMarkdownToPdf400ResponseOneOf1 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToPdf400ResponseOneOf1 = nil
	}

	// try to unmarshal data into PostTextMarkdownToPdf400ResponseOneOf2
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToPdf400ResponseOneOf2)
	if err == nil {
		jsonPostTextMarkdownToPdf400ResponseOneOf2, _ := json.Marshal(dst.PostTextMarkdownToPdf400ResponseOneOf2)
		if string(jsonPostTextMarkdownToPdf400ResponseOneOf2) == "{}" { // empty struct
			dst.PostTextMarkdownToPdf400ResponseOneOf2 = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToPdf400ResponseOneOf2); err != nil {
				dst.PostTextMarkdownToPdf400ResponseOneOf2 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToPdf400ResponseOneOf2 = nil
	}

	// try to unmarshal data into PostTextMarkdownToPdf400ResponseOneOf3
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToPdf400ResponseOneOf3)
	if err == nil {
		jsonPostTextMarkdownToPdf400ResponseOneOf3, _ := json.Marshal(dst.PostTextMarkdownToPdf400ResponseOneOf3)
		if string(jsonPostTextMarkdownToPdf400ResponseOneOf3) == "{}" { // empty struct
			dst.PostTextMarkdownToPdf400ResponseOneOf3 = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToPdf400ResponseOneOf3); err != nil {
				dst.PostTextMarkdownToPdf400ResponseOneOf3 = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToPdf400ResponseOneOf3 = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.HTML = nil
		dst.Markdown = nil
		dst.PostTextMarkdownToHtml400ResponseOneOf = nil
		dst.PostTextMarkdownToPdf400ResponseOneOf = nil
		dst.PostTextMarkdownToPdf400ResponseOneOf1 = nil
		dst.PostTextMarkdownToPdf400ResponseOneOf2 = nil
		dst.PostTextMarkdownToPdf400ResponseOneOf3 = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostTextMarkdownToPdf400Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostTextMarkdownToPdf400Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostTextMarkdownToPdf400Response) MarshalJSON() ([]byte, error) {
	if src.HTML != nil {
		return json.Marshal(&src.HTML)
	}

	if src.Markdown != nil {
		return json.Marshal(&src.Markdown)
	}

	if src.PostTextMarkdownToHtml400ResponseOneOf != nil {
		return json.Marshal(&src.PostTextMarkdownToHtml400ResponseOneOf)
	}

	if src.PostTextMarkdownToPdf400ResponseOneOf != nil {
		return json.Marshal(&src.PostTextMarkdownToPdf400ResponseOneOf)
	}

	if src.PostTextMarkdownToPdf400ResponseOneOf1 != nil {
		return json.Marshal(&src.PostTextMarkdownToPdf400ResponseOneOf1)
	}

	if src.PostTextMarkdownToPdf400ResponseOneOf2 != nil {
		return json.Marshal(&src.PostTextMarkdownToPdf400ResponseOneOf2)
	}

	if src.PostTextMarkdownToPdf400ResponseOneOf3 != nil {
		return json.Marshal(&src.PostTextMarkdownToPdf400ResponseOneOf3)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostTextMarkdownToPdf400Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.HTML != nil {
		return obj.HTML
	}

	if obj.Markdown != nil {
		return obj.Markdown
	}

	if obj.PostTextMarkdownToHtml400ResponseOneOf != nil {
		return obj.PostTextMarkdownToHtml400ResponseOneOf
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf != nil {
		return obj.PostTextMarkdownToPdf400ResponseOneOf
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf1 != nil {
		return obj.PostTextMarkdownToPdf400ResponseOneOf1
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf2 != nil {
		return obj.PostTextMarkdownToPdf400ResponseOneOf2
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf3 != nil {
		return obj.PostTextMarkdownToPdf400ResponseOneOf3
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PostTextMarkdownToPdf400Response) GetActualInstanceValue() (interface{}) {
	if obj.HTML != nil {
		return *obj.HTML
	}

	if obj.Markdown != nil {
		return *obj.Markdown
	}

	if obj.PostTextMarkdownToHtml400ResponseOneOf != nil {
		return *obj.PostTextMarkdownToHtml400ResponseOneOf
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf != nil {
		return *obj.PostTextMarkdownToPdf400ResponseOneOf
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf1 != nil {
		return *obj.PostTextMarkdownToPdf400ResponseOneOf1
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf2 != nil {
		return *obj.PostTextMarkdownToPdf400ResponseOneOf2
	}

	if obj.PostTextMarkdownToPdf400ResponseOneOf3 != nil {
		return *obj.PostTextMarkdownToPdf400ResponseOneOf3
	}

	// all schemas are nil
	return nil
}

type NullablePostTextMarkdownToPdf400Response struct {
	value *PostTextMarkdownToPdf400Response
	isSet bool
}

func (v NullablePostTextMarkdownToPdf400Response) Get() *PostTextMarkdownToPdf400Response {
	return v.value
}

func (v *NullablePostTextMarkdownToPdf400Response) Set(val *PostTextMarkdownToPdf400Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextMarkdownToPdf400Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextMarkdownToPdf400Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextMarkdownToPdf400Response(val *PostTextMarkdownToPdf400Response) *NullablePostTextMarkdownToPdf400Response {
	return &NullablePostTextMarkdownToPdf400Response{value: val, isSet: true}
}

func (v NullablePostTextMarkdownToPdf400Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextMarkdownToPdf400Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


