/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostTextBase64EncodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTextBase64EncodeRequest{}

// PostTextBase64EncodeRequest struct for PostTextBase64EncodeRequest
type PostTextBase64EncodeRequest struct {
	Text string `json:"text"`
}

type _PostTextBase64EncodeRequest PostTextBase64EncodeRequest

// NewPostTextBase64EncodeRequest instantiates a new PostTextBase64EncodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTextBase64EncodeRequest(text string) *PostTextBase64EncodeRequest {
	this := PostTextBase64EncodeRequest{}
	this.Text = text
	return &this
}

// NewPostTextBase64EncodeRequestWithDefaults instantiates a new PostTextBase64EncodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTextBase64EncodeRequestWithDefaults() *PostTextBase64EncodeRequest {
	this := PostTextBase64EncodeRequest{}
	return &this
}

// GetText returns the Text field value
func (o *PostTextBase64EncodeRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PostTextBase64EncodeRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PostTextBase64EncodeRequest) SetText(v string) {
	o.Text = v
}

func (o PostTextBase64EncodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTextBase64EncodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	return toSerialize, nil
}

func (o *PostTextBase64EncodeRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostTextBase64EncodeRequest := _PostTextBase64EncodeRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostTextBase64EncodeRequest)

	if err != nil {
		return err
	}

	*o = PostTextBase64EncodeRequest(varPostTextBase64EncodeRequest)

	return err
}

type NullablePostTextBase64EncodeRequest struct {
	value *PostTextBase64EncodeRequest
	isSet bool
}

func (v NullablePostTextBase64EncodeRequest) Get() *PostTextBase64EncodeRequest {
	return v.value
}

func (v *NullablePostTextBase64EncodeRequest) Set(val *PostTextBase64EncodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextBase64EncodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextBase64EncodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextBase64EncodeRequest(val *PostTextBase64EncodeRequest) *NullablePostTextBase64EncodeRequest {
	return &NullablePostTextBase64EncodeRequest{value: val, isSet: true}
}

func (v NullablePostTextBase64EncodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextBase64EncodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


