/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostWatermarkEmbed200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostWatermarkEmbed200Response{}

// PostWatermarkEmbed200Response struct for PostWatermarkEmbed200Response
type PostWatermarkEmbed200Response struct {
	// 在当前图片和配置下，能够嵌入的最大字符数。
	CapacityChars *int32 `json:"capacity_chars,omitempty"`
	// 处理耗时（毫秒）。
	EmbedMs *float32 `json:"embed_ms,omitempty"`
	// 实际输出的图片格式。
	Format *string `json:"format,omitempty"`
	// 处理完成后的图片 Base64 编码。
	ImageBase64 *string `json:"image_base64,omitempty"`
	// 原始图片文件名（若请求中包含则返回）。
	ImageName *string `json:"image_name,omitempty"`
	// 实际嵌入的标识内容。
	Payload *string `json:"payload,omitempty"`
}

// NewPostWatermarkEmbed200Response instantiates a new PostWatermarkEmbed200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostWatermarkEmbed200Response() *PostWatermarkEmbed200Response {
	this := PostWatermarkEmbed200Response{}
	return &this
}

// NewPostWatermarkEmbed200ResponseWithDefaults instantiates a new PostWatermarkEmbed200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostWatermarkEmbed200ResponseWithDefaults() *PostWatermarkEmbed200Response {
	this := PostWatermarkEmbed200Response{}
	return &this
}

// GetCapacityChars returns the CapacityChars field value if set, zero value otherwise.
func (o *PostWatermarkEmbed200Response) GetCapacityChars() int32 {
	if o == nil || IsNil(o.CapacityChars) {
		var ret int32
		return ret
	}
	return *o.CapacityChars
}

// GetCapacityCharsOk returns a tuple with the CapacityChars field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostWatermarkEmbed200Response) GetCapacityCharsOk() (*int32, bool) {
	if o == nil || IsNil(o.CapacityChars) {
		return nil, false
	}
	return o.CapacityChars, true
}

// HasCapacityChars returns a boolean if a field has been set.
func (o *PostWatermarkEmbed200Response) HasCapacityChars() bool {
	if o != nil && !IsNil(o.CapacityChars) {
		return true
	}

	return false
}

// SetCapacityChars gets a reference to the given int32 and assigns it to the CapacityChars field.
func (o *PostWatermarkEmbed200Response) SetCapacityChars(v int32) {
	o.CapacityChars = &v
}

// GetEmbedMs returns the EmbedMs field value if set, zero value otherwise.
func (o *PostWatermarkEmbed200Response) GetEmbedMs() float32 {
	if o == nil || IsNil(o.EmbedMs) {
		var ret float32
		return ret
	}
	return *o.EmbedMs
}

// GetEmbedMsOk returns a tuple with the EmbedMs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostWatermarkEmbed200Response) GetEmbedMsOk() (*float32, bool) {
	if o == nil || IsNil(o.EmbedMs) {
		return nil, false
	}
	return o.EmbedMs, true
}

// HasEmbedMs returns a boolean if a field has been set.
func (o *PostWatermarkEmbed200Response) HasEmbedMs() bool {
	if o != nil && !IsNil(o.EmbedMs) {
		return true
	}

	return false
}

// SetEmbedMs gets a reference to the given float32 and assigns it to the EmbedMs field.
func (o *PostWatermarkEmbed200Response) SetEmbedMs(v float32) {
	o.EmbedMs = &v
}

// GetFormat returns the Format field value if set, zero value otherwise.
func (o *PostWatermarkEmbed200Response) GetFormat() string {
	if o == nil || IsNil(o.Format) {
		var ret string
		return ret
	}
	return *o.Format
}

// GetFormatOk returns a tuple with the Format field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostWatermarkEmbed200Response) GetFormatOk() (*string, bool) {
	if o == nil || IsNil(o.Format) {
		return nil, false
	}
	return o.Format, true
}

// HasFormat returns a boolean if a field has been set.
func (o *PostWatermarkEmbed200Response) HasFormat() bool {
	if o != nil && !IsNil(o.Format) {
		return true
	}

	return false
}

// SetFormat gets a reference to the given string and assigns it to the Format field.
func (o *PostWatermarkEmbed200Response) SetFormat(v string) {
	o.Format = &v
}

// GetImageBase64 returns the ImageBase64 field value if set, zero value otherwise.
func (o *PostWatermarkEmbed200Response) GetImageBase64() string {
	if o == nil || IsNil(o.ImageBase64) {
		var ret string
		return ret
	}
	return *o.ImageBase64
}

// GetImageBase64Ok returns a tuple with the ImageBase64 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostWatermarkEmbed200Response) GetImageBase64Ok() (*string, bool) {
	if o == nil || IsNil(o.ImageBase64) {
		return nil, false
	}
	return o.ImageBase64, true
}

// HasImageBase64 returns a boolean if a field has been set.
func (o *PostWatermarkEmbed200Response) HasImageBase64() bool {
	if o != nil && !IsNil(o.ImageBase64) {
		return true
	}

	return false
}

// SetImageBase64 gets a reference to the given string and assigns it to the ImageBase64 field.
func (o *PostWatermarkEmbed200Response) SetImageBase64(v string) {
	o.ImageBase64 = &v
}

// GetImageName returns the ImageName field value if set, zero value otherwise.
func (o *PostWatermarkEmbed200Response) GetImageName() string {
	if o == nil || IsNil(o.ImageName) {
		var ret string
		return ret
	}
	return *o.ImageName
}

// GetImageNameOk returns a tuple with the ImageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostWatermarkEmbed200Response) GetImageNameOk() (*string, bool) {
	if o == nil || IsNil(o.ImageName) {
		return nil, false
	}
	return o.ImageName, true
}

// HasImageName returns a boolean if a field has been set.
func (o *PostWatermarkEmbed200Response) HasImageName() bool {
	if o != nil && !IsNil(o.ImageName) {
		return true
	}

	return false
}

// SetImageName gets a reference to the given string and assigns it to the ImageName field.
func (o *PostWatermarkEmbed200Response) SetImageName(v string) {
	o.ImageName = &v
}

// GetPayload returns the Payload field value if set, zero value otherwise.
func (o *PostWatermarkEmbed200Response) GetPayload() string {
	if o == nil || IsNil(o.Payload) {
		var ret string
		return ret
	}
	return *o.Payload
}

// GetPayloadOk returns a tuple with the Payload field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostWatermarkEmbed200Response) GetPayloadOk() (*string, bool) {
	if o == nil || IsNil(o.Payload) {
		return nil, false
	}
	return o.Payload, true
}

// HasPayload returns a boolean if a field has been set.
func (o *PostWatermarkEmbed200Response) HasPayload() bool {
	if o != nil && !IsNil(o.Payload) {
		return true
	}

	return false
}

// SetPayload gets a reference to the given string and assigns it to the Payload field.
func (o *PostWatermarkEmbed200Response) SetPayload(v string) {
	o.Payload = &v
}

func (o PostWatermarkEmbed200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostWatermarkEmbed200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CapacityChars) {
		toSerialize["capacity_chars"] = o.CapacityChars
	}
	if !IsNil(o.EmbedMs) {
		toSerialize["embed_ms"] = o.EmbedMs
	}
	if !IsNil(o.Format) {
		toSerialize["format"] = o.Format
	}
	if !IsNil(o.ImageBase64) {
		toSerialize["image_base64"] = o.ImageBase64
	}
	if !IsNil(o.ImageName) {
		toSerialize["image_name"] = o.ImageName
	}
	if !IsNil(o.Payload) {
		toSerialize["payload"] = o.Payload
	}
	return toSerialize, nil
}

type NullablePostWatermarkEmbed200Response struct {
	value *PostWatermarkEmbed200Response
	isSet bool
}

func (v NullablePostWatermarkEmbed200Response) Get() *PostWatermarkEmbed200Response {
	return v.value
}

func (v *NullablePostWatermarkEmbed200Response) Set(val *PostWatermarkEmbed200Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostWatermarkEmbed200Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostWatermarkEmbed200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostWatermarkEmbed200Response(val *PostWatermarkEmbed200Response) *NullablePostWatermarkEmbed200Response {
	return &NullablePostWatermarkEmbed200Response{value: val, isSet: true}
}

func (v NullablePostWatermarkEmbed200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostWatermarkEmbed200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


