/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PostTextConvertRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTextConvertRequest{}

// PostTextConvertRequest struct for PostTextConvertRequest
type PostTextConvertRequest struct {
	// 待转换的文本内容
	Text string `json:"text"`
	// 源格式类型
	From string `json:"from"`
	// 目标格式类型
	To string `json:"to"`
	// 可选参数（预留，当前未使用）
	Options map[string]interface{} `json:"options,omitempty"`
}

type _PostTextConvertRequest PostTextConvertRequest

// NewPostTextConvertRequest instantiates a new PostTextConvertRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTextConvertRequest(text string, from string, to string) *PostTextConvertRequest {
	this := PostTextConvertRequest{}
	this.Text = text
	this.From = from
	this.To = to
	return &this
}

// NewPostTextConvertRequestWithDefaults instantiates a new PostTextConvertRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTextConvertRequestWithDefaults() *PostTextConvertRequest {
	this := PostTextConvertRequest{}
	return &this
}

// GetText returns the Text field value
func (o *PostTextConvertRequest) GetText() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Text
}

// GetTextOk returns a tuple with the Text field value
// and a boolean to check if the value has been set.
func (o *PostTextConvertRequest) GetTextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Text, true
}

// SetText sets field value
func (o *PostTextConvertRequest) SetText(v string) {
	o.Text = v
}

// GetFrom returns the From field value
func (o *PostTextConvertRequest) GetFrom() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *PostTextConvertRequest) GetFromOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *PostTextConvertRequest) SetFrom(v string) {
	o.From = v
}

// GetTo returns the To field value
func (o *PostTextConvertRequest) GetTo() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *PostTextConvertRequest) GetToOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *PostTextConvertRequest) SetTo(v string) {
	o.To = v
}

// GetOptions returns the Options field value if set, zero value otherwise.
func (o *PostTextConvertRequest) GetOptions() map[string]interface{} {
	if o == nil || IsNil(o.Options) {
		var ret map[string]interface{}
		return ret
	}
	return o.Options
}

// GetOptionsOk returns a tuple with the Options field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTextConvertRequest) GetOptionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Options) {
		return map[string]interface{}{}, false
	}
	return o.Options, true
}

// HasOptions returns a boolean if a field has been set.
func (o *PostTextConvertRequest) HasOptions() bool {
	if o != nil && !IsNil(o.Options) {
		return true
	}

	return false
}

// SetOptions gets a reference to the given map[string]interface{} and assigns it to the Options field.
func (o *PostTextConvertRequest) SetOptions(v map[string]interface{}) {
	o.Options = v
}

func (o PostTextConvertRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTextConvertRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["text"] = o.Text
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	if !IsNil(o.Options) {
		toSerialize["options"] = o.Options
	}
	return toSerialize, nil
}

func (o *PostTextConvertRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"text",
		"from",
		"to",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPostTextConvertRequest := _PostTextConvertRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPostTextConvertRequest)

	if err != nil {
		return err
	}

	*o = PostTextConvertRequest(varPostTextConvertRequest)

	return err
}

type NullablePostTextConvertRequest struct {
	value *PostTextConvertRequest
	isSet bool
}

func (v NullablePostTextConvertRequest) Get() *PostTextConvertRequest {
	return v.value
}

func (v *NullablePostTextConvertRequest) Set(val *PostTextConvertRequest) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextConvertRequest) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextConvertRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextConvertRequest(val *PostTextConvertRequest) *NullablePostTextConvertRequest {
	return &NullablePostTextConvertRequest{value: val, isSet: true}
}

func (v NullablePostTextConvertRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextConvertRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


