/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// PostTextMarkdownToPdf413Response - struct for PostTextMarkdownToPdf413Response
type PostTextMarkdownToPdf413Response struct {
	Markdown *Markdown
	PostTextMarkdownToPdf413ResponseOneOf *PostTextMarkdownToPdf413ResponseOneOf
}

// MarkdownAsPostTextMarkdownToPdf413Response is a convenience function that returns Markdown wrapped in PostTextMarkdownToPdf413Response
func MarkdownAsPostTextMarkdownToPdf413Response(v *Markdown) PostTextMarkdownToPdf413Response {
	return PostTextMarkdownToPdf413Response{
		Markdown: v,
	}
}

// PostTextMarkdownToPdf413ResponseOneOfAsPostTextMarkdownToPdf413Response is a convenience function that returns PostTextMarkdownToPdf413ResponseOneOf wrapped in PostTextMarkdownToPdf413Response
func PostTextMarkdownToPdf413ResponseOneOfAsPostTextMarkdownToPdf413Response(v *PostTextMarkdownToPdf413ResponseOneOf) PostTextMarkdownToPdf413Response {
	return PostTextMarkdownToPdf413Response{
		PostTextMarkdownToPdf413ResponseOneOf: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *PostTextMarkdownToPdf413Response) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into Markdown
	err = newStrictDecoder(data).Decode(&dst.Markdown)
	if err == nil {
		jsonMarkdown, _ := json.Marshal(dst.Markdown)
		if string(jsonMarkdown) == "{}" { // empty struct
			dst.Markdown = nil
		} else {
			if err = validator.Validate(dst.Markdown); err != nil {
				dst.Markdown = nil
			} else {
				match++
			}
		}
	} else {
		dst.Markdown = nil
	}

	// try to unmarshal data into PostTextMarkdownToPdf413ResponseOneOf
	err = newStrictDecoder(data).Decode(&dst.PostTextMarkdownToPdf413ResponseOneOf)
	if err == nil {
		jsonPostTextMarkdownToPdf413ResponseOneOf, _ := json.Marshal(dst.PostTextMarkdownToPdf413ResponseOneOf)
		if string(jsonPostTextMarkdownToPdf413ResponseOneOf) == "{}" { // empty struct
			dst.PostTextMarkdownToPdf413ResponseOneOf = nil
		} else {
			if err = validator.Validate(dst.PostTextMarkdownToPdf413ResponseOneOf); err != nil {
				dst.PostTextMarkdownToPdf413ResponseOneOf = nil
			} else {
				match++
			}
		}
	} else {
		dst.PostTextMarkdownToPdf413ResponseOneOf = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.Markdown = nil
		dst.PostTextMarkdownToPdf413ResponseOneOf = nil

		return fmt.Errorf("data matches more than one schema in oneOf(PostTextMarkdownToPdf413Response)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(PostTextMarkdownToPdf413Response)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src PostTextMarkdownToPdf413Response) MarshalJSON() ([]byte, error) {
	if src.Markdown != nil {
		return json.Marshal(&src.Markdown)
	}

	if src.PostTextMarkdownToPdf413ResponseOneOf != nil {
		return json.Marshal(&src.PostTextMarkdownToPdf413ResponseOneOf)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *PostTextMarkdownToPdf413Response) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.Markdown != nil {
		return obj.Markdown
	}

	if obj.PostTextMarkdownToPdf413ResponseOneOf != nil {
		return obj.PostTextMarkdownToPdf413ResponseOneOf
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj PostTextMarkdownToPdf413Response) GetActualInstanceValue() (interface{}) {
	if obj.Markdown != nil {
		return *obj.Markdown
	}

	if obj.PostTextMarkdownToPdf413ResponseOneOf != nil {
		return *obj.PostTextMarkdownToPdf413ResponseOneOf
	}

	// all schemas are nil
	return nil
}

type NullablePostTextMarkdownToPdf413Response struct {
	value *PostTextMarkdownToPdf413Response
	isSet bool
}

func (v NullablePostTextMarkdownToPdf413Response) Get() *PostTextMarkdownToPdf413Response {
	return v.value
}

func (v *NullablePostTextMarkdownToPdf413Response) Set(val *PostTextMarkdownToPdf413Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextMarkdownToPdf413Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextMarkdownToPdf413Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextMarkdownToPdf413Response(val *PostTextMarkdownToPdf413Response) *NullablePostTextMarkdownToPdf413Response {
	return &NullablePostTextMarkdownToPdf413Response{value: val, isSet: true}
}

func (v NullablePostTextMarkdownToPdf413Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextMarkdownToPdf413Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


