/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostImageOcr503Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostImageOcr503Response{}

// PostImageOcr503Response struct for PostImageOcr503Response
type PostImageOcr503Response struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewPostImageOcr503Response instantiates a new PostImageOcr503Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostImageOcr503Response() *PostImageOcr503Response {
	this := PostImageOcr503Response{}
	return &this
}

// NewPostImageOcr503ResponseWithDefaults instantiates a new PostImageOcr503Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostImageOcr503ResponseWithDefaults() *PostImageOcr503Response {
	this := PostImageOcr503Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PostImageOcr503Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostImageOcr503Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PostImageOcr503Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PostImageOcr503Response) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PostImageOcr503Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostImageOcr503Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PostImageOcr503Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PostImageOcr503Response) SetMessage(v string) {
	o.Message = &v
}

func (o PostImageOcr503Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostImageOcr503Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePostImageOcr503Response struct {
	value *PostImageOcr503Response
	isSet bool
}

func (v NullablePostImageOcr503Response) Get() *PostImageOcr503Response {
	return v.value
}

func (v *NullablePostImageOcr503Response) Set(val *PostImageOcr503Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostImageOcr503Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostImageOcr503Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostImageOcr503Response(val *PostImageOcr503Response) *NullablePostImageOcr503Response {
	return &NullablePostImageOcr503Response{value: val, isSet: true}
}

func (v NullablePostImageOcr503Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostImageOcr503Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


