/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetSocialBilibiliVideoinfo200ResponseHonorReply type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetSocialBilibiliVideoinfo200ResponseHonorReply{}

// GetSocialBilibiliVideoinfo200ResponseHonorReply 视频荣誉信息。
type GetSocialBilibiliVideoinfo200ResponseHonorReply struct {
	// 荣誉列表。
	Honor []GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner `json:"honor,omitempty"`
}

// NewGetSocialBilibiliVideoinfo200ResponseHonorReply instantiates a new GetSocialBilibiliVideoinfo200ResponseHonorReply object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetSocialBilibiliVideoinfo200ResponseHonorReply() *GetSocialBilibiliVideoinfo200ResponseHonorReply {
	this := GetSocialBilibiliVideoinfo200ResponseHonorReply{}
	return &this
}

// NewGetSocialBilibiliVideoinfo200ResponseHonorReplyWithDefaults instantiates a new GetSocialBilibiliVideoinfo200ResponseHonorReply object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetSocialBilibiliVideoinfo200ResponseHonorReplyWithDefaults() *GetSocialBilibiliVideoinfo200ResponseHonorReply {
	this := GetSocialBilibiliVideoinfo200ResponseHonorReply{}
	return &this
}

// GetHonor returns the Honor field value if set, zero value otherwise.
func (o *GetSocialBilibiliVideoinfo200ResponseHonorReply) GetHonor() []GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner {
	if o == nil || IsNil(o.Honor) {
		var ret []GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner
		return ret
	}
	return o.Honor
}

// GetHonorOk returns a tuple with the Honor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseHonorReply) GetHonorOk() ([]GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner, bool) {
	if o == nil || IsNil(o.Honor) {
		return nil, false
	}
	return o.Honor, true
}

// HasHonor returns a boolean if a field has been set.
func (o *GetSocialBilibiliVideoinfo200ResponseHonorReply) HasHonor() bool {
	if o != nil && !IsNil(o.Honor) {
		return true
	}

	return false
}

// SetHonor gets a reference to the given []GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner and assigns it to the Honor field.
func (o *GetSocialBilibiliVideoinfo200ResponseHonorReply) SetHonor(v []GetSocialBilibiliVideoinfo200ResponseHonorReplyHonorInner) {
	o.Honor = v
}

func (o GetSocialBilibiliVideoinfo200ResponseHonorReply) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetSocialBilibiliVideoinfo200ResponseHonorReply) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Honor) {
		toSerialize["honor"] = o.Honor
	}
	return toSerialize, nil
}

type NullableGetSocialBilibiliVideoinfo200ResponseHonorReply struct {
	value *GetSocialBilibiliVideoinfo200ResponseHonorReply
	isSet bool
}

func (v NullableGetSocialBilibiliVideoinfo200ResponseHonorReply) Get() *GetSocialBilibiliVideoinfo200ResponseHonorReply {
	return v.value
}

func (v *NullableGetSocialBilibiliVideoinfo200ResponseHonorReply) Set(val *GetSocialBilibiliVideoinfo200ResponseHonorReply) {
	v.value = val
	v.isSet = true
}

func (v NullableGetSocialBilibiliVideoinfo200ResponseHonorReply) IsSet() bool {
	return v.isSet
}

func (v *NullableGetSocialBilibiliVideoinfo200ResponseHonorReply) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetSocialBilibiliVideoinfo200ResponseHonorReply(val *GetSocialBilibiliVideoinfo200ResponseHonorReply) *NullableGetSocialBilibiliVideoinfo200ResponseHonorReply {
	return &NullableGetSocialBilibiliVideoinfo200ResponseHonorReply{value: val, isSet: true}
}

func (v NullableGetSocialBilibiliVideoinfo200ResponseHonorReply) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetSocialBilibiliVideoinfo200ResponseHonorReply) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


