/*
UAPI

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostTextMarkdownToPdf400ResponseOneOf2 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostTextMarkdownToPdf400ResponseOneOf2{}

// PostTextMarkdownToPdf400ResponseOneOf2 struct for PostTextMarkdownToPdf400ResponseOneOf2
type PostTextMarkdownToPdf400ResponseOneOf2 struct {
	Code *string `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewPostTextMarkdownToPdf400ResponseOneOf2 instantiates a new PostTextMarkdownToPdf400ResponseOneOf2 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostTextMarkdownToPdf400ResponseOneOf2() *PostTextMarkdownToPdf400ResponseOneOf2 {
	this := PostTextMarkdownToPdf400ResponseOneOf2{}
	return &this
}

// NewPostTextMarkdownToPdf400ResponseOneOf2WithDefaults instantiates a new PostTextMarkdownToPdf400ResponseOneOf2 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostTextMarkdownToPdf400ResponseOneOf2WithDefaults() *PostTextMarkdownToPdf400ResponseOneOf2 {
	this := PostTextMarkdownToPdf400ResponseOneOf2{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) SetCode(v string) {
	o.Code = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *PostTextMarkdownToPdf400ResponseOneOf2) SetMessage(v string) {
	o.Message = &v
}

func (o PostTextMarkdownToPdf400ResponseOneOf2) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostTextMarkdownToPdf400ResponseOneOf2) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullablePostTextMarkdownToPdf400ResponseOneOf2 struct {
	value *PostTextMarkdownToPdf400ResponseOneOf2
	isSet bool
}

func (v NullablePostTextMarkdownToPdf400ResponseOneOf2) Get() *PostTextMarkdownToPdf400ResponseOneOf2 {
	return v.value
}

func (v *NullablePostTextMarkdownToPdf400ResponseOneOf2) Set(val *PostTextMarkdownToPdf400ResponseOneOf2) {
	v.value = val
	v.isSet = true
}

func (v NullablePostTextMarkdownToPdf400ResponseOneOf2) IsSet() bool {
	return v.isSet
}

func (v *NullablePostTextMarkdownToPdf400ResponseOneOf2) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostTextMarkdownToPdf400ResponseOneOf2(val *PostTextMarkdownToPdf400ResponseOneOf2) *NullablePostTextMarkdownToPdf400ResponseOneOf2 {
	return &NullablePostTextMarkdownToPdf400ResponseOneOf2{value: val, isSet: true}
}

func (v NullablePostTextMarkdownToPdf400ResponseOneOf2) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostTextMarkdownToPdf400ResponseOneOf2) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


