/*
UAPI OpenAPI

Generated from UAPI JSON. Code is the interactive documentation: rich descriptions, examples, and x-extensions preserved.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the PostImageDecode503Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PostImageDecode503Response{}

// PostImageDecode503Response struct for PostImageDecode503Response
type PostImageDecode503Response struct {
	Error *string `json:"error,omitempty"`
}

// NewPostImageDecode503Response instantiates a new PostImageDecode503Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPostImageDecode503Response() *PostImageDecode503Response {
	this := PostImageDecode503Response{}
	return &this
}

// NewPostImageDecode503ResponseWithDefaults instantiates a new PostImageDecode503Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPostImageDecode503ResponseWithDefaults() *PostImageDecode503Response {
	this := PostImageDecode503Response{}
	return &this
}

// GetError returns the Error field value if set, zero value otherwise.
func (o *PostImageDecode503Response) GetError() string {
	if o == nil || IsNil(o.Error) {
		var ret string
		return ret
	}
	return *o.Error
}

// GetErrorOk returns a tuple with the Error field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PostImageDecode503Response) GetErrorOk() (*string, bool) {
	if o == nil || IsNil(o.Error) {
		return nil, false
	}
	return o.Error, true
}

// HasError returns a boolean if a field has been set.
func (o *PostImageDecode503Response) HasError() bool {
	if o != nil && !IsNil(o.Error) {
		return true
	}

	return false
}

// SetError gets a reference to the given string and assigns it to the Error field.
func (o *PostImageDecode503Response) SetError(v string) {
	o.Error = &v
}

func (o PostImageDecode503Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PostImageDecode503Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Error) {
		toSerialize["error"] = o.Error
	}
	return toSerialize, nil
}

type NullablePostImageDecode503Response struct {
	value *PostImageDecode503Response
	isSet bool
}

func (v NullablePostImageDecode503Response) Get() *PostImageDecode503Response {
	return v.value
}

func (v *NullablePostImageDecode503Response) Set(val *PostImageDecode503Response) {
	v.value = val
	v.isSet = true
}

func (v NullablePostImageDecode503Response) IsSet() bool {
	return v.isSet
}

func (v *NullablePostImageDecode503Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePostImageDecode503Response(val *PostImageDecode503Response) *NullablePostImageDecode503Response {
	return &NullablePostImageDecode503Response{value: val, isSet: true}
}

func (v NullablePostImageDecode503Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePostImageDecode503Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


