/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscHotboard200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscHotboard200Response{}

// GetMiscHotboard200Response struct for GetMiscHotboard200Response
type GetMiscHotboard200Response struct {
	// 热榜条目列表。
	List []GetMiscHotboard200ResponseListInner `json:"list,omitempty"`
	Type *string `json:"type,omitempty"`
	UpdateTime *string `json:"update_time,omitempty"`
}

// NewGetMiscHotboard200Response instantiates a new GetMiscHotboard200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscHotboard200Response() *GetMiscHotboard200Response {
	this := GetMiscHotboard200Response{}
	return &this
}

// NewGetMiscHotboard200ResponseWithDefaults instantiates a new GetMiscHotboard200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscHotboard200ResponseWithDefaults() *GetMiscHotboard200Response {
	this := GetMiscHotboard200Response{}
	return &this
}

// GetList returns the List field value if set, zero value otherwise.
func (o *GetMiscHotboard200Response) GetList() []GetMiscHotboard200ResponseListInner {
	if o == nil || IsNil(o.List) {
		var ret []GetMiscHotboard200ResponseListInner
		return ret
	}
	return o.List
}

// GetListOk returns a tuple with the List field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200Response) GetListOk() ([]GetMiscHotboard200ResponseListInner, bool) {
	if o == nil || IsNil(o.List) {
		return nil, false
	}
	return o.List, true
}

// HasList returns a boolean if a field has been set.
func (o *GetMiscHotboard200Response) HasList() bool {
	if o != nil && !IsNil(o.List) {
		return true
	}

	return false
}

// SetList gets a reference to the given []GetMiscHotboard200ResponseListInner and assigns it to the List field.
func (o *GetMiscHotboard200Response) SetList(v []GetMiscHotboard200ResponseListInner) {
	o.List = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *GetMiscHotboard200Response) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200Response) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *GetMiscHotboard200Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *GetMiscHotboard200Response) SetType(v string) {
	o.Type = &v
}

// GetUpdateTime returns the UpdateTime field value if set, zero value otherwise.
func (o *GetMiscHotboard200Response) GetUpdateTime() string {
	if o == nil || IsNil(o.UpdateTime) {
		var ret string
		return ret
	}
	return *o.UpdateTime
}

// GetUpdateTimeOk returns a tuple with the UpdateTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscHotboard200Response) GetUpdateTimeOk() (*string, bool) {
	if o == nil || IsNil(o.UpdateTime) {
		return nil, false
	}
	return o.UpdateTime, true
}

// HasUpdateTime returns a boolean if a field has been set.
func (o *GetMiscHotboard200Response) HasUpdateTime() bool {
	if o != nil && !IsNil(o.UpdateTime) {
		return true
	}

	return false
}

// SetUpdateTime gets a reference to the given string and assigns it to the UpdateTime field.
func (o *GetMiscHotboard200Response) SetUpdateTime(v string) {
	o.UpdateTime = &v
}

func (o GetMiscHotboard200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscHotboard200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.List) {
		toSerialize["list"] = o.List
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.UpdateTime) {
		toSerialize["update_time"] = o.UpdateTime
	}
	return toSerialize, nil
}

type NullableGetMiscHotboard200Response struct {
	value *GetMiscHotboard200Response
	isSet bool
}

func (v NullableGetMiscHotboard200Response) Get() *GetMiscHotboard200Response {
	return v.value
}

func (v *NullableGetMiscHotboard200Response) Set(val *GetMiscHotboard200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscHotboard200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscHotboard200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscHotboard200Response(val *GetMiscHotboard200Response) *NullableGetMiscHotboard200Response {
	return &NullableGetMiscHotboard200Response{value: val, isSet: true}
}

func (v NullableGetMiscHotboard200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscHotboard200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


