/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetNetworkIcp404Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNetworkIcp404Response{}

// GetNetworkIcp404Response struct for GetNetworkIcp404Response
type GetNetworkIcp404Response struct {
	Code *string `json:"code,omitempty"`
	Details map[string]interface{} `json:"details,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewGetNetworkIcp404Response instantiates a new GetNetworkIcp404Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNetworkIcp404Response() *GetNetworkIcp404Response {
	this := GetNetworkIcp404Response{}
	return &this
}

// NewGetNetworkIcp404ResponseWithDefaults instantiates a new GetNetworkIcp404Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNetworkIcp404ResponseWithDefaults() *GetNetworkIcp404Response {
	this := GetNetworkIcp404Response{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetNetworkIcp404Response) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkIcp404Response) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetNetworkIcp404Response) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetNetworkIcp404Response) SetCode(v string) {
	o.Code = &v
}

// GetDetails returns the Details field value if set, zero value otherwise.
func (o *GetNetworkIcp404Response) GetDetails() map[string]interface{} {
	if o == nil || IsNil(o.Details) {
		var ret map[string]interface{}
		return ret
	}
	return o.Details
}

// GetDetailsOk returns a tuple with the Details field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkIcp404Response) GetDetailsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Details) {
		return map[string]interface{}{}, false
	}
	return o.Details, true
}

// HasDetails returns a boolean if a field has been set.
func (o *GetNetworkIcp404Response) HasDetails() bool {
	if o != nil && !IsNil(o.Details) {
		return true
	}

	return false
}

// SetDetails gets a reference to the given map[string]interface{} and assigns it to the Details field.
func (o *GetNetworkIcp404Response) SetDetails(v map[string]interface{}) {
	o.Details = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetNetworkIcp404Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNetworkIcp404Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetNetworkIcp404Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetNetworkIcp404Response) SetMessage(v string) {
	o.Message = &v
}

func (o GetNetworkIcp404Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNetworkIcp404Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Details) {
		toSerialize["details"] = o.Details
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableGetNetworkIcp404Response struct {
	value *GetNetworkIcp404Response
	isSet bool
}

func (v NullableGetNetworkIcp404Response) Get() *GetNetworkIcp404Response {
	return v.value
}

func (v *NullableGetNetworkIcp404Response) Set(val *GetNetworkIcp404Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNetworkIcp404Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNetworkIcp404Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNetworkIcp404Response(val *GetNetworkIcp404Response) *NullableGetNetworkIcp404Response {
	return &NullableGetNetworkIcp404Response{value: val, isSet: true}
}

func (v NullableGetNetworkIcp404Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNetworkIcp404Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


