/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscWeather200ResponseLifeIndicesSunscreen type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscWeather200ResponseLifeIndicesSunscreen{}

// GetMiscWeather200ResponseLifeIndicesSunscreen 防晒指数
type GetMiscWeather200ResponseLifeIndicesSunscreen struct {
	Level *string `json:"level,omitempty"`
	Brief *string `json:"brief,omitempty"`
	Advice *string `json:"advice,omitempty"`
}

// NewGetMiscWeather200ResponseLifeIndicesSunscreen instantiates a new GetMiscWeather200ResponseLifeIndicesSunscreen object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscWeather200ResponseLifeIndicesSunscreen() *GetMiscWeather200ResponseLifeIndicesSunscreen {
	this := GetMiscWeather200ResponseLifeIndicesSunscreen{}
	return &this
}

// NewGetMiscWeather200ResponseLifeIndicesSunscreenWithDefaults instantiates a new GetMiscWeather200ResponseLifeIndicesSunscreen object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscWeather200ResponseLifeIndicesSunscreenWithDefaults() *GetMiscWeather200ResponseLifeIndicesSunscreen {
	this := GetMiscWeather200ResponseLifeIndicesSunscreen{}
	return &this
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) SetLevel(v string) {
	o.Level = &v
}

// GetBrief returns the Brief field value if set, zero value otherwise.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) GetBrief() string {
	if o == nil || IsNil(o.Brief) {
		var ret string
		return ret
	}
	return *o.Brief
}

// GetBriefOk returns a tuple with the Brief field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) GetBriefOk() (*string, bool) {
	if o == nil || IsNil(o.Brief) {
		return nil, false
	}
	return o.Brief, true
}

// HasBrief returns a boolean if a field has been set.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) HasBrief() bool {
	if o != nil && !IsNil(o.Brief) {
		return true
	}

	return false
}

// SetBrief gets a reference to the given string and assigns it to the Brief field.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) SetBrief(v string) {
	o.Brief = &v
}

// GetAdvice returns the Advice field value if set, zero value otherwise.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) GetAdvice() string {
	if o == nil || IsNil(o.Advice) {
		var ret string
		return ret
	}
	return *o.Advice
}

// GetAdviceOk returns a tuple with the Advice field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) GetAdviceOk() (*string, bool) {
	if o == nil || IsNil(o.Advice) {
		return nil, false
	}
	return o.Advice, true
}

// HasAdvice returns a boolean if a field has been set.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) HasAdvice() bool {
	if o != nil && !IsNil(o.Advice) {
		return true
	}

	return false
}

// SetAdvice gets a reference to the given string and assigns it to the Advice field.
func (o *GetMiscWeather200ResponseLifeIndicesSunscreen) SetAdvice(v string) {
	o.Advice = &v
}

func (o GetMiscWeather200ResponseLifeIndicesSunscreen) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscWeather200ResponseLifeIndicesSunscreen) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.Brief) {
		toSerialize["brief"] = o.Brief
	}
	if !IsNil(o.Advice) {
		toSerialize["advice"] = o.Advice
	}
	return toSerialize, nil
}

type NullableGetMiscWeather200ResponseLifeIndicesSunscreen struct {
	value *GetMiscWeather200ResponseLifeIndicesSunscreen
	isSet bool
}

func (v NullableGetMiscWeather200ResponseLifeIndicesSunscreen) Get() *GetMiscWeather200ResponseLifeIndicesSunscreen {
	return v.value
}

func (v *NullableGetMiscWeather200ResponseLifeIndicesSunscreen) Set(val *GetMiscWeather200ResponseLifeIndicesSunscreen) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscWeather200ResponseLifeIndicesSunscreen) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscWeather200ResponseLifeIndicesSunscreen) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscWeather200ResponseLifeIndicesSunscreen(val *GetMiscWeather200ResponseLifeIndicesSunscreen) *NullableGetMiscWeather200ResponseLifeIndicesSunscreen {
	return &NullableGetMiscWeather200ResponseLifeIndicesSunscreen{value: val, isSet: true}
}

func (v NullableGetMiscWeather200ResponseLifeIndicesSunscreen) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscWeather200ResponseLifeIndicesSunscreen) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


