/*
UAPI

UAPI 官方接口文档

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package uapi

import (
	"encoding/json"
)

// checks if the GetMiscTrackingDetect200ResponseDataAlternativesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetMiscTrackingDetect200ResponseDataAlternativesInner{}

// GetMiscTrackingDetect200ResponseDataAlternativesInner struct for GetMiscTrackingDetect200ResponseDataAlternativesInner
type GetMiscTrackingDetect200ResponseDataAlternativesInner struct {
	// 快递公司编码
	Code *string `json:"code,omitempty"`
	// 快递公司名称
	Name *string `json:"name,omitempty"`
}

// NewGetMiscTrackingDetect200ResponseDataAlternativesInner instantiates a new GetMiscTrackingDetect200ResponseDataAlternativesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetMiscTrackingDetect200ResponseDataAlternativesInner() *GetMiscTrackingDetect200ResponseDataAlternativesInner {
	this := GetMiscTrackingDetect200ResponseDataAlternativesInner{}
	return &this
}

// NewGetMiscTrackingDetect200ResponseDataAlternativesInnerWithDefaults instantiates a new GetMiscTrackingDetect200ResponseDataAlternativesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetMiscTrackingDetect200ResponseDataAlternativesInnerWithDefaults() *GetMiscTrackingDetect200ResponseDataAlternativesInner {
	this := GetMiscTrackingDetect200ResponseDataAlternativesInner{}
	return &this
}

// GetCode returns the Code field value if set, zero value otherwise.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) GetCode() string {
	if o == nil || IsNil(o.Code) {
		var ret string
		return ret
	}
	return *o.Code
}

// GetCodeOk returns a tuple with the Code field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) GetCodeOk() (*string, bool) {
	if o == nil || IsNil(o.Code) {
		return nil, false
	}
	return o.Code, true
}

// HasCode returns a boolean if a field has been set.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) HasCode() bool {
	if o != nil && !IsNil(o.Code) {
		return true
	}

	return false
}

// SetCode gets a reference to the given string and assigns it to the Code field.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) SetCode(v string) {
	o.Code = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *GetMiscTrackingDetect200ResponseDataAlternativesInner) SetName(v string) {
	o.Name = &v
}

func (o GetMiscTrackingDetect200ResponseDataAlternativesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetMiscTrackingDetect200ResponseDataAlternativesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Code) {
		toSerialize["code"] = o.Code
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableGetMiscTrackingDetect200ResponseDataAlternativesInner struct {
	value *GetMiscTrackingDetect200ResponseDataAlternativesInner
	isSet bool
}

func (v NullableGetMiscTrackingDetect200ResponseDataAlternativesInner) Get() *GetMiscTrackingDetect200ResponseDataAlternativesInner {
	return v.value
}

func (v *NullableGetMiscTrackingDetect200ResponseDataAlternativesInner) Set(val *GetMiscTrackingDetect200ResponseDataAlternativesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetMiscTrackingDetect200ResponseDataAlternativesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetMiscTrackingDetect200ResponseDataAlternativesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetMiscTrackingDetect200ResponseDataAlternativesInner(val *GetMiscTrackingDetect200ResponseDataAlternativesInner) *NullableGetMiscTrackingDetect200ResponseDataAlternativesInner {
	return &NullableGetMiscTrackingDetect200ResponseDataAlternativesInner{value: val, isSet: true}
}

func (v NullableGetMiscTrackingDetect200ResponseDataAlternativesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetMiscTrackingDetect200ResponseDataAlternativesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


